<div class="all-features">
	<div class="row features-heading">
		<div class="col-md-12 text-center"><h2>Membership Management</h2></div>
	</div>
	<div class="row">	
		<div class="col-md-5 col-md-offset-1">
			<h3>
				Self Serve Sign-Up</h3>
			<p>
				Save time by having your customers sign-up on your website.</p>
		</div>


		<div class="col-md-5">
			<h3>
				Total Customer Management</h3>
			<p>
				Quickly create, view, email, download customer information, shares subscription, products, invoices and payments</p>
		</div>
	</div>
	<div class="row">
		<div class="col-md-5 col-md-offset-1">
			<h3>
				Smart Product and Share Offerings</h3>
			<p>
				Easily create product and share offerings with content fields that make sense for farms and food.</p>
		</div>

		<div class="col-md-5">
			<h3>
				Printable Delivery Reports</h3>
			<p>
				Easily print product packing lists for each location, multiple locations, or all locations</p>
		</div>
	</div>
	<div class="row">
		<div class="col-md-5 col-md-offset-1">
			<h3>
				Downloadable Excel Reports</h3>
			<p>
				Export all data to do analysis in Excel. Track member churn-rates, sales, sign-up etc.</p>
		</div>

		<div class="col-md-5">
			<h3>
				Automatic Email Notifications</h3>
			<p>
				Never miss an order, payment, or invoice. You receive printable order, payment, and invoice emails.</p>
		</div>
	</div>

	<div class="row features-heading">
		<div class="col-md-12 text-center"><h2>Marketing</h2></div>
	</div>
	<div class="row">
		<div class="col-md-5 col-md-offset-1">
			<h3>
				Easy Content Editor</h3>
			<p>
				Easily edit any content on your website (photos, text, videos, links)</p>
		</div>
		<div class="col-md-5">
			<h3>
				Website Builder and Themes</h3>
			<p>
				Create a website in minutes, no HTML knowledge necessary. Choose a website theme, select a banner, and start entering your content. Contact us for custom website design</p>
		</div>
	</div>
	<div class="row">	
		<div class="col-md-5 col-md-offset-1">
			<h3>
				Blog</h3>
			<p>
				Built in blogging capability (option to enable or disable) with keywords, categories, and optional synchronization with social media.</p>
		</div>


		<div class="col-md-5">
			<h3>
				Search Engine Optimization (SEO) Ready</h3>
			<p>
				Search engine optimized and sitemaps automatically sent to Google, Bing, and Yahoo.</p>
		</div>
	</div>
	<div class="row">
		<div class="col-md-5 col-md-offset-1">
			<h3>
				Website Traffic Reporting and Analytics</h3>
			<p>
				Track your website&rsquo;s traffic, inbound links, outbound links, search terms and keywords.</p>
		</div>
		<div class="col-md-5">
			<h3>
				Free HarvestHand.com Domain Name</h3>
			<p>
				Every account comes with a free HarestHand domain name. E.G. yourfarm.harvesthand.com</p>
		</div>
	</div>
	<div class="row">
		<div class="col-md-5 col-md-offset-1">
			<h3>
				Social Media Integration</h3>
			<p>
				Facebook and Twitter buttons on every page of your website. Auto-post blog and newsletter to Facebook and Twitter (optional)</p>
		</div>
		<div class="col-md-5">
			<h3>
				Email Newsletter</h3>
			<p>
				Send UNLIMITED number of emails to customer lists. Easy to use newsletter program with integrated membership database, segmented emails by customer lists, and email autofill (delivery lists, names etc.)</p>
		</div>
	</div>

	<div class="row features-heading">
		<div class="col-md-12 text-center"><h2>E-Commerce</h2></div>
	</div>

	<div class="row">
		<div class="col-md-5 col-md-offset-1">
			<h3>
				Online Payment Processing</h3>
			<p>
				Paypal integration (optional), e-transfers with trackable customer numbers, scheduled bank payments.</p>
		</div>
		<div class="col-md-5">
			<h3>
				Distribution Network (NEW)</h3>
			<p>
				Create a distribution network with another farm or within a farmers market. Sell through other farms in HarvestHand.</p>
		</div>
	</div>

	<div class="row button-row">
		<div class="col-md-12 text-center">
			<a href="/shares/register" class="btn btn-hh btn-lg">Signup for Free!</a>
		</div>
	</div>
</div>