<?php $this->loader()->append('jquery_validate'); ?>
<?php $this->placeholder('foot')->captureStart() ?>
<script type="text/javascript">
    $(document).ready(function(){
        $("#login").validate();
    });
</script>
<?php $this->placeholder('foot')->captureEnd() ?>

<form 
    id="login" 
    action="/login"
    method="post"
    class="cmxform full"
    accept-charset="utf-8">

    <fieldset>
        <legend><?= $this->translate('Login'); ?></legend>

        <p>
            <label for="userName" class="required"><?= $this->translate('User Name'); ?></label>
            <input 
                id="userName"
                type="text"
                name="userName"
                maxlength="50"
                title="<?= $this->translate('Please enter your user name'); ?>"
                value="<?= (!empty($_POST['userName'])) ? $this->escape($_POST['userName']) : null; ?>"
                class="<?= (!empty($this->errorMessages['userName'])) ? 'required error' : 'required'; ?>" />
        </p>
        <p>
            <label for="password" class="required"><?= $this->translate('Password'); ?></label>
            <input 
                id="password"
                type="password"
                name="password"
                maxlength="30"
                title="<?= $this->translate('Please enter your password'); ?>"
                class="<?= (!empty($this->errorMessages['password'])) ? 'required error' : 'required'; ?>" />
        </p>
        <p>
            <button type="submit" class="submit ui-button ui-widget ui-corner-all ui-button-text-icon-primary ui-state-default">
                <span class="ui-button-icon-primary ui-icon ui-icon-key"></span>
                <span class="ui-button-text">
                    <?= $this->translate('Login'); ?>
                </span>
            </button>
        </p>
        
        <p>
            <?= $this->translate('Lost password?') ?>
            <a href="/customers/password_reset">
                <?= $this->translate('Reset it') ?>
            </a>
        </p>
    </fieldset>
</form>