<?php
    $currentYear = null;
    $currentWeek = null;
    $initWeek = false;
    $date = new Zend_Date();
    $date->set(3, Zend_Date::WEEKDAY_8601);

    $this->loader()->append('jquery_dropdown');

    $this->headLink()
        ->appendStylesheet('/_farms/css/themes/default/shares.css');

    if (!empty($this->year) && !empty($this->week)) {

        $date->setYear($this->year)
            ->setWeek($this->week);

        $date->set(1, Zend_Date::WEEKDAY_8601);

        $startDate = $date->toString('MMM dd');
        $date->set(7, Zend_Date::WEEKDAY_8601);
        $endDate = $date->toString('MMM dd, YYYY');

        $title = $this->translate(
            '%s Deliveries: %s - %s',
            ucfirst($this->farm->getPreferences()->get('shares', 'shares', 'shares')),
            $startDate,
            $endDate
        );


    } else {
        $title = ucfirst($this->farm->getPreferences()->get('shares', 'shares', 'shares'));
    }

    $options = array();

    $this->headTitle($title);
?>

<div class="btn-group" style="float:right">
    <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
        <?= $this->translate('Follow') ?>
        <span class="caret"></span>
    </a>
    <ul class="dropdown-menu pull-right">
        <li>
            <a href="/shares?format=rss">
                <?= $this->translate(
                    '%s RSS Feed',
                    ucfirst($this->farm->getPreferences()->get('shares', 'shares', 'shares'))
                ) ?>
            </a>
            <?php if (!empty($this->farmer) && $this->farmer['role'] == HH_Domain_Farmer::ROLE_MEMBER) { ?>
                <a href="/shares?t=<?= $this->farmer['userToken'] ?>&format=ics">
                    <?= $this->translate(
                        'My %s iCalendar Feed',
                        ucfirst($this->farm->getPreferences()->get('shares', 'shares', 'shares'))
                    ) ?>
                </a>
            <?php } else { ?>
                <a href="/shares?format=ics">
                    <?= $this->translate(
                        '%s iCalendar Feed',
                        ucfirst($this->farm->getPreferences()->get('shares', 'shares', 'shares'))
                    ) ?>
                </a>
            <?php } ?>
            <?php if (!empty($this->farmer) && $this->farmer['role'] == HH_Domain_Farmer::ROLE_MEMBER) { ?>
                <a href="https://www.google.com/calendar/render?cid=<?= urlencode($this->farm->getBaseUri() . 'shares?t=' . $this->farmer['userToken'] . '&format=ics') ?>">
                    <?= $this->translate(
                        'Add To Google Calendar',
                        ucfirst($this->farm->getPreferences()->get('shares', 'shares', 'shares'))
                    ) ?>
                </a>
            <?php } else { ?>
                <a href="https://www.google.com/calendar/render?cid=<?= urlencode($this->farm->getBaseUri() . 'shares?format=ics') ?>">
                    <?= $this->translate(
                        'Add To Google Calendar',
                        ucfirst($this->farm->getPreferences()->get('shares', 'shares', 'shares'))
                    ) ?>
                </a>
            <?php } ?>
        </li>
    </ul>
</div>

<h2>
    <?= $title ?>
</h2>

<?php if (!empty($this->deliveries)) { ?>
    <?php foreach ($this->deliveries as $delivery) { ?>
        <?php
            list($year, $week) = explode('W', $delivery['week']);
        ?>
        <?php if ($year != $currentYear) { ?>
            <?php
                $currentYear = $year;
                $currentWeek = null;
                $options[$currentYear] = array();
            } ?>
        <?php if ($this->week == $week && $this->year == $year) { ?>
            <?php if ($currentWeek != $week) { ?>
                <?php
                    $date = new Zend_Date();
                    $date->set(3, Zend_Date::WEEKDAY_8601);

                    $date->setYear($year)
                        ->setWeek($week)
                        ->set(1, Zend_Date::WEEKDAY_8601);

                    $label = $date->toString('EEE, MMM dd') . ' - ';
                    $date->set(7, Zend_Date::WEEKDAY_8601);
                    $label .= $date->toString('EEE, MMM dd');
                ?>

                <dl id="deliveries">
                <?php
                    $currentWeek = $week;
                    $initWeek = true;
                    $options[$currentYear][$currentYear . 'W' . $currentWeek] = $label;
                ?>
            <?php } ?>

                <dt class="delivery-share">
                    <?= $this->escape($delivery->getShare()->name); ?>
                </dt>

                <dd>
                    <dl class="delivery-share-items">
                <?php foreach ($delivery->getItems() as $item) { ?>
                        <dt>
                            <?= $this->escape($item->item); ?> -
                            <?php
                                $sizes = array();
                            if (!empty($item->quantity_0_25)) {
                                foreach ($delivery->getShare()->sizes as $size) {
                                    if ($size->size == 0.25) {

                                        $sizes[] = array(
                                            'name' => $size->name,
                                            'qty' => $item->quantity_0_25
                                        );

                                        break;
                                    }
                                }
                            }

                                if (!empty($item->quantity_0_5)) {
                                    foreach ($delivery->getShare()->sizes as $size) {
                                        if ($size->size == 0.5) {

                                            $sizes[] = array(
                                                'name' => $size->name,
                                                'qty' => $item->quantity_0_5
                                            );

                                            break;
                                        }
                                    }
                                }

                            if (!empty($item->quantity_0_75)) {
                                foreach ($delivery->getShare()->sizes as $size) {
                                    if ($size->size == 0.75) {

                                        $sizes[] = array(
                                            'name' => $size->name,
                                            'qty' => $item->quantity_0_75
                                        );

                                        break;
                                    }
                                }
                            }

                                if (!empty($item->quantity_1)) {
                                    foreach ($delivery->getShare()->sizes as $size) {
                                        if ($size->size == 1) {

                                            $sizes[] = array(
                                                'name' => $size->name,
                                                'qty' => $item->quantity_1
                                            );

                                            break;
                                        }
                                    }
                                }

                                if (!empty($item->quantity_2)) {
                                    foreach ($delivery->getShare()->sizes as $size) {
                                        if ($size->size == 2) {

                                            $sizes[] = array(
                                                'name' => $size->name,
                                                'qty' => $item->quantity_2
                                            );

                                            break;
                                        }
                                    }
                                }

                                if (!empty($sizes)) {
//                                    if (count($sizes) == 1) {
//                                        echo $sizes[0]['qty'];
//                                    } else {
                                        for ($x = 0, $c = count($sizes); $x < $c; ++$x) {
                                            echo $sizes[$x]['qty'] . ' (' . $sizes[$x]['name'] . ')';
                                            if ($x + 1 != $c) {
                                                echo '; ';
                                            }
                                        }
//                                    }
                                }
                            ?>
                        </dt>
                        <dd>
                            <?php if (!empty($item->source)) { ?>
                                <?= $this->escape($item->source) ?> -
                            <?php } ?>
                            <?php
                                switch ($item->certification) {
                                    case HHF_Domain_Certification::ORGANIC:
                                        echo $this->translate('Certified Organic');
                                        break;
                                    case HHF_Domain_Certification::BIODYNAMIC:
                                        echo $this->translate('Biodynamic');
                                        break;
                                    case HHF_Domain_Certification::CERTIFIED_NATURAL:
                                        echo $this->translate('Certified Naturally Grown');
                                        break;
                                    case HHF_Domain_Certification::NATURAL:
                                        echo $this->translate('Naturally Grown');
                                        break;
                                    case HHF_Domain_Certification::GRASS:
                                        echo $this->translate('Pastured');
                                        break;
                                    case HHF_Domain_Certification::TRANSITIONAL:
                                        echo $this->translate('Transition to Organic');
                                        break;
                                    case HHF_Domain_Certification::CONVENTIONAL:
                                        echo $this->translate('Non Organic');
                                        break;
                                    case HHF_Domain_Certification::SPRAY_FREE:
                                        echo $this->translate('Spray Free');
                                        break;
                                }
                            ?>
                        </dd>
                <?php } ?>
                    </dl>
                </dd>

        <?php } else if ($currentWeek != $week) { ?>
            <?php if ($initWeek == true) { ?>
                    </dl>
            <?php $initWeek = false; } ?>
            <?php
                $date = new Zend_Date();

                $date->setYear($year)
                    ->setWeek($week)
                    ->set(1, Zend_Date::WEEKDAY_8601);

                $label = $date->toString('EEE, MMM dd') . ' - ';
                $date->set(7, Zend_Date::WEEKDAY_8601);
                $label .= $date->toString('EEE, MMM dd');

            ?>
            <?php
                $currentWeek = $week;
                $options[$currentYear][$currentYear . 'W' . $currentWeek] = $label;
            ?>
        <?php } ?>

    <?php } ?>

    <?php if ($initWeek == true) { ?>
            </dl>
    <?php } ?>

<?php } else { ?>

    <p><?= $this->translate(
        'No %s To Display',
        ucfirst($this->farm->getPreferences()->get('shares', 'shares', 'shares'))
    ); ?></p>

<?php } ?>

<?php if (!empty($options)) { ?>
    <form action="<?= $this->escape($this->Url()) ?>" method="get" class="cmxform full">
        <fieldset>
            <legend><?= $this->escape($this->translate('Choose Another Week')) ?></legend>
            <p>
                <label>
                    <?= $this->translate('Week') ?>
                </label>
                <?php
                    echo $this->formSelect(
                        'week',
                        $this->year . 'W' . sprintf('%02d', $this->week),
                        array(),
                        $options
                    );
                ?>
            </p>
            <p>
                <label></label>
                <button type="submit" class="submit ui-button ui-widget ui-corner-all ui-button-text-only ui-state-default">
                    <span class="ui-button-text">
                        <i class="fa fa-calendar"></i>
                        <?= $this->escape($this->translate('Change')) ?>
                    </span>
                </button>
            </p>
        </fieldset>
    </form>
<?php } ?>
