<h2><?= $this->translate('Paid!'); ?></h2>

<section class="info ui-widget ui-state-highlight ui-corner-all">
    <div>
        <i class="fa fa-info-circle"></i>
        <strong><?= $this->translate('Paid!'); ?></strong>
        <?= $this->translate('We received your payment from Paypal'); ?>
    </div>
</section>

<p><?= $this->translate('Thank you for your payment. Your transaction has been completed, and a receipt for your purchase has been emailed to you.') ?></p>

