<?php
    $this->headTitle($this->translate('Add On Products Purchase History'));

    $this->loader()->append('jquery_dataTables');
?>

<?php $this->placeholder('foot')->captureStart() ?>
<style>
	td.right .btn {
		color: white;
	}
</style>
<script type="text/javascript">
    $(document).ready(function(){
        
        var table = $("#invoices").dataTable({
            "bJQueryUI": true,
            "bAutoWidth": false,
            "bDeferRender": true,
            "bLengthChange": false,
            "bProcessing": true,
            "iDisplayLength": 50,
            "iDeferLoading": <?= $this->foundRows ?>,
            "aaSorting": [[1, "desc"]],
            "aoColumns": [ 
                {
                    "sType": "string",
                    "mDataProp": "id"
                },
                {
                    "sType": "text",
                    "mDataProp": "dueDate",
                    "fnRender": function (oObj) {
                        if (!oObj.aData.hasOwnProperty("DT_RowId")) {
                            return oObj.aData.dueDate;
                        } else {
                            return oObj.aData.dueDate.replace(/&/g,'&amp;')
                                    .replace(/</g,'&lt;')
                                    .replace(/>/g,'&gt;');
                        }
                    }
                },
                {
                    "sType": "text",
                    "mDataProp": "total"
                },
                {
                    "sType": "text",
                    "mDataProp": "outstandingAmount"
                },
                { 
                    "bSortable": false,
                    "bSearchable": false,
                    "mDataProp": "_actions",
                    "sClass": "right",
                    "fnRender": function (oObj) {
                        if (!oObj.aData.hasOwnProperty("DT_RowId")) {
                            return oObj.aData._actions;
                        }

                        var menu = '<form action="/shares/purchase-history-invoice" method="get">' +
                            '<input type="hidden" name="id" value="' + parseInt(oObj.aData.id) + '" />' +
                            '<button title="<?= $this->translate('Details') ?>" type="submit" class="btn btn-default">' +
                            '<i class="fa fa-info-circle"></i></button></form>';

                        return menu;
                    }
                }
            ],
            "bSortClasses": false,
            "sAjaxSource": "<?= addslashes($this->Url()) ?>/d/1/cid/<?= $this->customerId ?>",
            "bServerSide": true,
            "sDom": '<"H"<"clear">r<"right"ip>>t<"F"<"right"ip>>'
        })
        .delegate("tbody tr", "mouseover mouseout", function(e) {
            if (e.type == "mouseover") {
                $(e.currentTarget).addClass('hover');
            } else {
                $(e.currentTarget).removeClass('hover');
            }
        });
    });
</script>
<?php $this->placeholder('foot')->captureEnd() ?>

<h2><?= $this->translate('Invoices History') ?></h2>

<?php if (count($this->invoices)) { ?>
        
    <table id="invoices" class="display">
        <thead>
            <tr>
                <th
                    width="9%"
                    title="<?= $this->translate('Invoice ID') ?>">
                        <?= $this->translate('ID'); ?>
                </th>
                <th
                    width="30%"
                    title="<?= $this->translate('Due Date') ?>">
                        <?= $this->translate('Due Date') ?>
                </th>
                <th
                    width="22%"
                    title="<?= $this->translate('Invoice Total') ?>">
                        <?= $this->translate('Total') ?>
                </th>
                <th
                    width="22%"
                    title="<?= $this->translate('Outstanding Amount') ?>">
                        <?= $this->translate('Due') ?>
                </th>
                <th
                    width="17%"
                    title="<?= $this->translate('Invoice Actions') ?>">
                </th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->invoices as $invoice) { ?>
                <tr>
                    <td>
                        <?= $this->escape($invoice['id']); ?>
                    </td>
                    <td>
                        <?= $this->escape($invoice['dueDate']->toString('yyyy-MM-dd')); ?>
                    </td>
                    <td>
                        <?= $this->currency($invoice['total']) ?>
                    </td>
                    <td>
                        <?= $this->currency($invoice['outstandingAmount']) ?>
                    </td>
                    <td class="right">
                        <form action="/shares/purchase-history-invoice" method="get">
                            <input type="hidden" name="id" value="<?= (int) $invoice->id ?>" />
                            <button
                                title="<?= $this->translate('Details') ?>"
                                type="submit"
                                class="btn btn-default">
                                <i class="fa fa-info-circle"></i>
                            </button>
                        </form>
                    </td>
                </tr>
            <?php } ?>
        </tbody>
    </table>

    <?php 
        if ($this->embedded) { 
            echo $this->placeholder('foot');
        }
    ?>

<?php } else { ?>

    <p><?=
        $this->translate(
            'You haven\'t purchased any %s add ons yet.  <a href="%s">Would you like to view %s add ons available for purchase?.</a>',
            $this->farm->getPreferences()->get('share', 'shares', 'share'),
            '/shares',
            $this->farm->getPreferences()->get('share', 'shares', 'share')
        ); ?></p>

<?php } ?>

