<?php
    $total = 0;
    
    if ($this->order->getPaymentPlan()->canHaveInstalments() && $this->order->getPaymentPlan()->count()) {
        $total = $this->order->getPaymentPlan()->getUpfrontTotal();
    } else {
        $total = $this->order->getTotal();
    }
    
    $registrationDueDate = null;
    
    if (!$this->order->getPaymentPlan()->canHaveInstalments()) {
        $dueDate = $this->order->getPaymentPlan()
            ->getInstalmentStartDate();

        if ($dueDate->compareDate(Zend_Date::now()) != 0) {
            $registrationDueDate = $dueDate;
        }
    }
?>

<?php $this->placeholder('foot')->captureStart() ?>
    <script type="text/javascript">
        $(document).ready(function(){
            $(".paypal").button({
                    icons : {
                        primary:'ui-icon-locked'
                    }
                });
        });
    </script>
<?php $this->placeholder('foot')->captureEnd() ?>

<section class="info ui-widget ui-state-highlight ui-corner-all">
    <div>
        <i class="fa fa-info-circle"></i>
        <strong><?= $this->translate('Registered!'); ?></strong>
        <?= $this->translate(
            'You have successfully signed up for your %s!',
            $this->farm->getPreferences()->get('shares', 'shares', 'shares')
        ); ?>
    </div>
</section>

<p><?= $this->translate('Thank you for your registration!  Please print out this receipt for your records.') ?></p>

<?php if ($this->paymentMethod == HHF_Domain_Transaction::TYPE_PAYPAL) { ?>

    <?php if (!empty($total)) { ?>

        <?php if ($registrationDueDate instanceof Zend_Date) { ?>

            <p><?= $this->translate(
                'Payment for your purchase is due %s.  If you wish to pay this amount now, click the below button and you will be redirected to Paypal:',
                $registrationDueDate->get(Zend_Date::DATE_FULL)
            ); ?></p>

        <?php } else { ?>

            <p><?= $this->translate('To complete payment for your purchase, you will be redirected to Paypal.  Click here to continue:'); ?></p>

        <?php } ?>

        <div align="center">
            <?php echo $this->paypalButton(
                $this->farm,
                $this->translate(
                    '%s %s Sign Up Fee',
                    $this->farm->name,
                    ucfirst($this->farm->getPreferences()->get('share', 'shares', 'share'))
                ),
                $this->orderId,
                $total
            ); ?>
        </div>
            
    <?php } ?>
    
    <br />

<?php } else { ?>

    <?php if (!empty($total)) { ?>
    
        <?php if ($registrationDueDate instanceof Zend_Date) { ?>
    
            <p><?= $this->translate(
                'To complete registration for your purchase, please send a cheque for %s referencing your customer number %s by %s to:',
                $this->escape($this->currency($total)),
                $this->escape($this->order->getCustomer()->id),
                $registrationDueDate->get(Zend_Date::DATE_FULL)
            ) ?></p>
    
        <?php } else { ?>
    
            <p><?= $this->translate(
                'To complete registration for your purchase, please send a cheque for %s referencing your customer number %s to:',
                $this->escape($this->currency($total)),
                $this->escape($this->order->getCustomer()->id)
            ) ?></p>
            
        <?php } ?>

        <p id="farm-address">
            <?php
                $paymentTo = $this->farm->getPreferences()->get('paymentTo', 'shares');
            ?>
            <?php if (!empty($paymentTo)) { ?>
                <?= $this->escape($paymentTo); ?><br />
            <?php } ?>
            <?= $this->escape($this->farm->name) ?><br />
            <?= $this->escape($this->farm->address) ?><br />
            <?php if (!empty($this->farm->address2)) { ?>
            <?= $this->escape($this->farm->address2) ?><br />
            <?php } ?>
            <?= $this->escape($this->farm->city); ?>, <?= $this->escape($this->farm->state); ?>  <?= $this->escape($this->farm->zipCode); ?>
        </p>
    <?php } ?>
    
<?php } ?>
       
<?php
    $this->orderEdit = false;
    $this->mapLinks = true;
    echo $this->render('public/register-order-summary.phtml'); 
?>
