<nav id="body-subnav" class="grid_3">
    <h3><?= $this->translate('Where To?'); ?></h3>
    <ul>
        <li>
            <a href="/admin/shares/shares"
               title="<?= $this->translate('View and edit existing shares') ?>">
                <?= $this->translate('Shares'); ?>
            </a>
            <ul>
                <li>
                    <a href="/admin/shares/shares"
                        title="<?= $this->translate('View and edit existing shares') ?>">
                        
                        <i class="fa fa-folder"></i>
                        <?= $this->translate('View'); ?>
                    </a>
                </li>
                <li>
                    <a href="/admin/shares/share"
                       title="<?= $this->translate('Add new share') ?>">
                        
                        <i class="fa fa-plus"></i>
                        <?= $this->translate('New'); ?>
                    </a>
                </li>
            </ul>
        </li>
        <li>
            <a href="/admin/shares/deliveries"
               title="<?= $this->translate('View and edit existing share deliveries') ?>">
                <?= $this->translate('Deliveries'); ?>
            </a>
            <ul>
                <li>
                    <a href="/admin/shares/deliveries"
                        title="<?= $this->translate('View and edit existing share deliveries') ?>">
                        
                        <i class="fa fa-folder"></i>
                        <?= $this->translate('View'); ?>
                    </a>
                </li>
                <li>
                    <a href="/admin/shares/delivery"
                       title="<?= $this->translate('Add new share delivery') ?>">
                        
                        <i class="fa fa-plus"></i>
                        <?= $this->translate('New'); ?>
                    </a>
                </li>
                <li>
                    <a href="/admin/shares/delivery-reports"
                        title="<?= $this->translate('View share delivery reports') ?>">

                        <i class="fa fa-file-o"></i>
                        <?= $this->translate('Reports'); ?>
                    </a>
                </li>
            </ul>
        </li>
        <li>
            <a href="/admin/shares/locations"
               title="<?= $this->translate('View and edit existing pickup or delivery locations') ?>">
                <?= $this->translate('Locations'); ?>
            </a>
            <ul>
                <li>
                    <a href="/admin/shares/locations"
                       title="<?= $this->translate('View and edit existing pickup or delivery locations') ?>">
                        
                        <i class="fa fa-folder"></i>
                        <?= $this->translate('View'); ?>
                    </a>
                </li>
                <li>
                    <a href="/admin/shares/location"
                       title="<?= $this->translate('Add new pickup or delivery location') ?>">
                        
                        <i class="fa fa-plus"></i>
                        <?= $this->translate('New'); ?>
                    </a>
                </li>
            </ul>
        </li>
        <li>
            <a href="/admin/shares/addons"
               title="<?= $this->translate('View and edit existing share add on products') ?>">
                <?= $this->translate('Products'); ?>
            </a>
            <ul>
                <li>
                    <a href="/admin/shares/addons"
                       title="<?= $this->translate('View and edit existing share add on products') ?>">
                        
                        <i class="fa fa-folder"></i>
                        <?= $this->translate('View'); ?>
                    </a>
                </li>
                <li>
                    <a href="/admin/shares/addon"
                       title="<?= $this->translate('Add new share add on product') ?>">
                        
                        <i class="fa fa-plus"></i>
                        <?= $this->translate('New'); ?>
                    </a>
                </li>
            </ul>
        </li>
        <li>
            <a href="/admin/shares/addons-categories"
               title="<?= $this->translate('View and edit existing share add on product categories') ?>">
                <?= $this->translate('Product Categories'); ?>
            </a>
            <ul>
                <li>
                    <a href="/admin/shares/addons-categories"
                       title="<?= $this->translate('View and edit existing share add on product categories') ?>">

                        <i class="fa fa-folder"></i>
                        <?= $this->translate('View'); ?>
                    </a>
                </li>
                <li>
                    <a href="/admin/shares/addon-category"
                       title="<?= $this->translate('Add new share add on product category') ?>">

                        <i class="fa fa-plus"></i>
                        <?= $this->translate('New'); ?>
                    </a>
                </li>
            </ul>
        </li>
    </ul>
</nav>
