<?php

/**
 * Test class for Bootstrap.
 * Generated by PHPUnit on 2010-09-18 at 12:08:09.
 */
class BootstrapTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var Bootstrap
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Bootstrap;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @todo Implement testInit().
     */
    public function testInit()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testAutoloadHandler().
     */
    public function testAutoloadHandler()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    public function testGet()
    {
        $this->assertEquals('Zend_Session', Bootstrap::get('Zend_Session'));
        $this->assertType('Zend_View', Bootstrap::get('Zend_View'));
    }

    public function testGetZendDb()
    {
        $this->assertType('Zend_Db_Adapter_Abstract', Bootstrap::getZendDb());
    }

    public function testGetZendConfig()
    {
        $this->assertType('Zend_Config', Bootstrap::getZendConfig());
    }

    public function testGetZendMailTransport()
    {
        $this->assertType('Zend_Mail_Transport_Smtp', Bootstrap::getZendMailTransport());
    }

    public function testGetZendCache()
    {
        $this->assertType('Zend_Cache_Core', Bootstrap::getZendCache());
    }

    public function testGetZendTranslate()
    {
        $this->assertType('HH_Translate', Bootstrap::getZendTranslate());
    }
}