<?php
$facebookPageLink = $this->farm->getPreferences()->get('pageLink', 'facebook');
$twitterScreenName = $this->farm->getPreferences()->get('screenName', 'twitter');
$blogEnabled = $this->farm->getPreferences()->get('blogEnabled', 'website', true);
$disclaimer = $this->farm->getPreferences()->get('disclaimer', 'website', '');

$this->headLink()->headLink(array(
                                'rel'   => 'alternate',
                                'href'  => '/shares?format=rss',
                                'type'  => 'application/rss+xml',
                                'title' => $this->translate('%s Shares RSS Feed', $this->farm->name)
                            ));
$this->headLink()->headLink(array(
                                'rel'   => 'alternate',
                                'href'  => '/shares?format=atom',
                                'type'  => 'application/atom+xml',
                                'title' => $this->translate('%s Shares Atom Feed', $this->farm->name)
                            ));

if($blogEnabled){
    $this->headLink()->headLink(array(
                                    'rel'   => 'alternate',
                                    'href'  => '/blog?format=rss',
                                    'type'  => 'application/rss+xml',
                                    'title' => $this->translate('%s Blog', $this->farm->name)
                                ));
    $this->headLink()->headLink(array(
                                    'rel'   => 'alternate',
                                    'href'  => '/blog?format=atom',
                                    'type'  => 'application/atom+xml',
                                    'title' => $this->translate('%s Blog', $this->farm->name)
                                ));
}
?>
<!doctype html>
<!--[if lt IE 7 ]>
<html class="no-js ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>
<html class="no-js ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>
<html class="no-js ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>
<html class="no-js ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!-->
<html lang="en" class="no-js"> <!--<![endif]-->
<head>
    <!--Public-->
    <div class="test"></div>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta http-equiv="X-UA-Compatible" content="chrome=1">
    <meta charset="utf-8">
    <?php echo $this->headTitle() ?>
    <link rel="shortcut icon" href="/_images/favicon.png">
    <script src="/_js/modernizr.js"></script>
    <script src="/_js/jquery-2.1.4.min.js"></script>
    <script src="/_js/bootstrap.min.js"></script>
    <script src="/_js/jquery/jquery.fitvids.js"></script>
    <?php echo $this->headStyle() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->placeholder('head'); ?>
</head>

<?php if($this->farm->id == 5){ ?>
    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] || function () {

                    (i[r].q = i[r].q || []).push(arguments)
                }, i[r].l = 1 * new Date();
            a = s.createElement(o),

                m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)

        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
        ga('create', 'UA-42628849-1', 'strawberryhillfarm.ca');
        ga('send', 'pageview');
    </script>
<?php } ?>

<body>
<div class="container">
    <header id="masthead">
        <div class="row">
            <div class="col-xs-12">
                <?php
                $headerImage = $this->farm->getPreferences()->get('headerImage', 'website', false);
                ?>
                <?php if(!empty($headerImage)){ ?>
                    <div class="parent" id="masthead-logo">
                        <img class="img-responsive child-img"
                             src="/default/file/id/<?= $this->escape($headerImage) ?>/s/<?= HHF_Domain_File::IMAGE_LARGE ?>"
                             onclick="document.location = '/';">
                    </div>
                <?php } else{ ?>
                    <div id="masthead-logo" onclick="document.location = '/';">
                        <h1><?= $this->escape($this->farm->name); ?></h1>
                    </div>
                <?php } ?>
                <nav class="navbar navbar-default">
                    <div class="container-fluid">
                        <!-- Brand and toggle get grouped for better mobile display -->
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        </div>

                        <!-- Collect the nav links, forms, and other content for toggling -->
                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                            <?= $this->navigation(Bootstrap::get('Zend_Navigation'))->menu()->renderMenu(null, array(
                                'ulClass' => 'nav navbar-nav'
                            )) ?>
                        </div>
                        <!-- /.navbar-collapse -->
                    </div>
                    <!-- /.container-fluid -->
                </nav>
            </div>
        </div>
    </header>

    <div id="main-content">
        <div class="row" style="margin-top: 15px">
            <?php $sideBar = $this->layout()->sideBar; ?>
            <?php if(!empty($sideBar)){ ?>
                <section id="<?= $this->contentId ?>" class="col-xs-12">
                    <section class="col-md-8">
                        <?php echo $this->layout()->content ?>
                    </section>
                    <nav class="col-md-4">
                        <?= $sideBar ?>
                    </nav>
                </section>
            <?php } else{ ?>
                <section id="<?= $this->contentId ?>" class="col-xs-12 nopadding ">
                    <?php echo $this->layout()->content ?>
                </section>
            <?php } ?>
        </div>
    </div>
</div>
<div id="wrapper">
<footer id="footer">
    <div id="footer-company" class="col-md-4 vcard alpha">
        <h3 class="org"><?= $this->farm->name ?></h3>

        <div class="adr">
            <div class="street-address">
                <?= $this->escape($this->farm->address) ?>
                <?php if(!empty($this->farm->address2)){ ?>
                    <br/><?= $this->escape($this->farm->address2) ?>
                <?php } ?>
            </div>
            <span class="locality"><?= $this->escape($this->farm->city) ?></span>,
            <span class="region"><?= $this->escape($this->farm->state) ?></span>,
            <span class="postal-code"><?= $this->escape($this->farm->zipCode) ?></span>
        </div>
        <?php if(!empty($this->farm->telephone)){ ?>
            <div class="tel"><?= $this->escape($this->farm->telephone) ?></div>
        <?php } ?>
    </div>
    <div id="footer-contact" class="col-md-4">
        <h3 class="hidden-xs hidden-sm"><?= $this->translate('Stay in Touch'); ?></h3>
        <ul>
            <?php if(!empty($this->farm->email)){ ?>
                <li><a href="/contact" title="<?= $this->translate('Email') ?>"><span
                            class="icon-social icon-social-email"></span></a></li>
            <?php } ?>
            <?php if($blogEnabled){ ?>
                <li><a href="/blog?format=rss" title="<?= $this->translate('RSS'); ?>"><span
                            class="icon-social icon-social-rss"></span></a></li>
            <?php } ?>
            <?php if(!empty($facebookPageLink)){ ?>
                <li><a href="<?= $this->escape($facebookPageLink); ?>" title="<?= $this->translate('Facebook'); ?>"><span
                            class="icon-social icon-social-facebook"></span></a></li>
            <?php } ?>
            <?php if(!empty($twitterScreenName)){ ?>
                <li><a href="http://twitter.com/<?= $this->escape($twitterScreenName) ?>"
                       title="<?= $this->translate('Twitter'); ?>"><span class="icon-social icon-social-twitter"></span></a>
                </li>
            <?php } ?>
        </ul>
    </div>
    <div id="footer-support" class="col-md-4 omega hidden-xs hidden-sm">
        <h3><?= $this->translate('HarvestHand') ?></h3>

        <?php if(!empty($disclaimer)){ ?>
            <a href="/disclaimer" title="<?= $this->translate('Website Disclaimer') ?>">
                <?= $this->translate('Disclaimer') ?></a>

            |
        <?php } ?>

        <a href="/admin" title="<?= $this->translate('Go To My Farm Dashboard') ?>">
            <?= $this->translate('Admin Dashboard'); ?></a>

        |

        <a href="http://www.<?= Bootstrap::$rootDomain ?>/"
           title="<?= $this->translate('This site is powered by local food communities and HarvestHand') ?>">
            <?= $this->translate('HarvestHand') ?></a>

    </div>
</footer>
</div>
<?php
echo $this->loader()->prepend(array(
                                  'jquery',
                                  'jquery_ui',
                                  'hh'
                              ))->toString(HH_View_Helper_Loader::JS);
?>
<?php echo $this->headScript() ?>
<?php echo $this->placeholder('foot'); ?>
<?php
$piwikId = $this->farm->getPreferences()->get('piwikId', 'website', false);
?>

<?php if(!empty($piwikId)){ ?>
    <script type="text/javascript">
        document.write(unescape("%3Cscript src='/_stats/piwik.js' type='text/javascript'%3E%3C/script%3E"));
    </script>
    <script type="text/javascript">
        try {
            var piwikTracker = Piwik.getTracker("/_stats/piwik.php", <?= (int) $piwikId ?>);
            piwikTracker.trackPageView();
            piwikTracker.enableLinkTracking();
        } catch (err) {
        }
    </script>
    <noscript><p><img src="/_stats/piwik.php?idsite=<?= (int)$piwikId ?>" style="border:0" alt=""/></p></noscript>
<?php } ?>
<?php if(!empty($this->farm->domain) && !empty($_SESSION['session']['transfer'])){ ?>
    <img width="1"
         height="1"
         alt="t"
         border="0"
         style="border: 0"
         src="http://www.<?= Bootstrap::$rootDomain ?>/service/default/sync/i.gif?i=<?= urlencode(HH_Crypto::encrypt(Zend_Session::getId())); ?>"/>
<?php } ?>

<?php if($this->farm->id == 5){ ?>
    <!-- Google Code for Remarketing Tag -->
    <!--------------------------------------------------
    Remarketing tags may not be associated with personally identifiable information or placed on pages related to sensitive categories. See more information and instructions on how to setup the tag on: http://google.com/ads/remarketingsetup
    --------------------------------------------------->
    <script type="text/javascript">
        /* <![CDATA[ */
        var google_conversion_id = 979870194;
        var google_custom_params = window.google_tag_params;
        var google_remarketing_only = true;
        /* ]]> */
    </script>
    <script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
    </script>
    <noscript>
        <div style="display:inline;">
            <img height="1" width="1" style="border-style:none;" alt=""
                 src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/979870194/?value=0&amp;guid=ON&amp;script=0"/>
        </div>
    </noscript>
<?php } ?>

<script>
    // Script to make large user uploaded images fit on mobile screens.
    $("img").addClass("img-responsive")

    // This opens drop downs on click instead of hover for mobile sites.
    // It also prepends parent links to the drop downs, as clicking them
    // no longer redirects to their href.

    var $elem = "nav li a";
    if ($(window).width() < 979){

        $($elem).each(function() {
            if($(this).siblings(".dropdown-menu").length){

                $var = $(this).siblings(".dropdown-menu");
                $var.prepend(
                    $('<li>').append(
                        $(this).clone().remove(".dropdown-menu").removeAttr("id")
                    )
                );

                $(this).addClass("dropdown-toggle");
                $(this).attr("data-hover", "dropdown");
                $(this).attr("data-toggle", "dropdown");

            }
        });
    }
</script>
</body>
</html>
