<?php if ($this->pageCount) { ?>
    <nav class="paginationControl">
        <!-- Previous page link -->
        <?php if (isset($this->previous)) { ?>
            <a href="<?= $this->url(array('page' => $this->previous)); ?>">&lt; <?= $this->translate('Previous') ?></a> |
        <?php } else { ?>
            <span class="disabled">&lt; <?= $this->translate('Previous'); ?></span> |
        <?php } ?>

        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page) { ?>
            <?php if ($page != $this->current) { ?>
                <a href="<?= $this->url(array('page' => $page)); ?>"><?= $page; ?></a> |
            <?php } else { ?>
                <?= $page; ?> |
            <?php } ?>
        <?php } ?>

        <!-- Next page link -->
        <?php if (isset($this->next)) { ?>
            <a href="<?= $this->url(array('page' => $this->next)); ?>"><?= $this->translate('Next') ?> &gt;</a>
        <?php } else { ?>
            <span class="disabled"><?= $this->translate('Next') ?> &gt;</span>
        <?php } ?>
    </nav>
<?php } ?>