<?php
$this->headTitle($this->translate('Product Categories'));

$this->loader()->append('jquery_dataTables')
    ->append('jquery_dropdown');

Bootstrap::getZendCurrency();
?>

<?php $this->placeholder('foot')->captureStart() ?>
<script type="text/javascript">
$(document).ready(function(){

    $.fn.dataTableExt.aoFeatures.push({
        "fnInit": function(oSettings) {
            return $('<ul class="dataTables_add dropdown-container"><li class="dropdown btn-group">' +
            '<a href="#" title="<?= $this->translate('Actions') ?>" class="btn">' +
            '<?= addslashes($this->translate('Actions')) ?></a>' +
            '<button type="button" class="btn dropdown-toggle" data-toggle="dropdown">' +
            '<span class="caret"></span></button>' +
            '<ul class="dropdown-menu">' +
            '<li><a href="/admin/shares/addon-category" title="<?= $this->translate('Add product') ?>">' +
            '<?= $this->translate('Add product category') ?></a></li>' +
            '<li><a href="/admin/shares/addons-categories/format/csv/" title="<?= $this->translate('Export to a spreadsheet program') ?>">' +
            '<?= $this->translate('Export to CSV') ?></a></li></ul></li></ul>')[0];
        },
        "cFeature": "a",
        "sFeature": "Add"
    });

    var table = $("#collection").dataTable({
        "bJQueryUI": true,
        "bAutoWidth": false,
        "bDeferRender": true,
        "bLengthChange": false,
        "bProcessing": true,
        "iDisplayLength": 50,
        "iDeferLoading": <?= $this->foundRows ?>,
        "aaSorting": [[0, "asc"]],
        "aoColumns": [
            {
                "sType": "html",
                "mDataProp": "name",
                "fnRender": function (oObj) {
                    if (!oObj.aData.hasOwnProperty("id")) {
                        return oObj.aData.name;
                    } else {
                        return '<a href="/admin/shares/addon?id=' + oObj.aData.id + '">' +
                        oObj.aData.name.replace(/&/g,'&amp;')
                            .replace(/</g,'&lt;')
                            .replace(/>/g,'&gt;') + '</a>';
                    }
                }
            },
            {
                "bSortable": false,
                "bSearchable": false,
                "mDataProp": "_actions",
                "sClass": "right",
                "fnRender": function (oObj) {
                    if (!oObj.aData.hasOwnProperty("id")) {
                        return oObj.aData._actions;
                    }
                    var button = '<ul class="dropdown-container">' +
                        '<li class="dropdown btn-group">' +
                        '<a href="/admin/shares/addon-category?id=' + parseInt(oObj.aData.id) + '"' +
                        ' title="<?= $this->translate('Edit product category') ?>" class="btn">' +
                        '<?= addslashes($this->translate('Edit')) ?></a>' +
                        '<button type="button" class="btn dropdown-toggle" data-toggle="dropdown">' +
                        '<span class="caret"></span></button>' +
                        '<ul class="dropdown-menu">';

                        button += '<li class="divider"></li><li><a class="delete" title="<?= addslashes($this->translate('Delete product category')) ?>" ' +
                        ' href="/admin/shares/addon-category?a=delete&id=' + oObj.aData.id + '"><?= addslashes($this->translate('Delete')) ?></a></li>';

                    button += '</ul></li></ul>';

                    return button;
                }
            }
        ],
        "bSortClasses": false,
        "sAjaxSource": "<?= addslashes($this->Url()) ?>",
        "bServerSide": true,
        "sDom": '<"H"a<"clear">f<"clear">r<"right"ip>>t<"F"<"right"ip>>'
    })
        .delegate("tbody tr", "mouseover mouseout", function(e) {
            if (e.type == "mouseover") {
                $(e.currentTarget).addClass('hover');
            } else {
                $(e.currentTarget).removeClass('hover');
            }
        })
        .delegate(".delete", "click", function(){
            return window.confirm("<?= $this->translate('Are you sure you want to delete this product?  No turning back after a product delete.'); ?>");
        })
        .fnSetFilteringDelay(1000);

    new FixedHeader(table);

    $('.dropdown-toggle').dropdown();
});
</script>
<?php $this->placeholder('foot')->captureEnd() ?>

<h2>
    <span class="icon-menu icon-menu-shares" style="float: left; margin: -10px 7px 0 0;"></span>
    <?= $this->translate('Product Categories') ?>
</h2>

<section class="container_12">
    <article class="grid_9">

        <?php if (!empty($this->messages)) { ?>
            <section class="info ui-widget ui-state-highlight ui-corner-all">
                <div>
                    <i class="fa fa-info-circle"></i>
                    <strong><?= $this->translate('Hey!'); ?></strong>
                    <?= $this->escape(implode('; ', $this->messages)); ?>
                </div>
            </section>
        <?php } ?>

        <?php if (count($this->collection)) { ?>
            <table id="collection" class="display">
                <thead>
                <tr>
                    <th
                        width="85%"
                        title="<?= $this->translate('Product Category Name') ?>">
                        <?= $this->translate('Name'); ?>
                    </th>
                    <th
                        width="15%"
                        title="<?= $this->translate('Product Category Actions') ?>">
                    </th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($this->collection as $item) { ?>
                    <tr>
                        <td>
                            <a href="/admin/shares/addon-category?id=<?= $item->id ?>">
                                <?= $this->escape($item->name); ?>
                            </a>
                        </td>
                        <td class="right">
                            <ul class="dropdown-container">
                                <li class="dropdown btn-group">
                                    <a href="/admin/shares/addon-category?id=<?= $item->id ?>"
                                       title="<?= $this->translate('Edit product category') ?>"
                                       class="btn">
                                        <?= $this->translate('Edit') ?>
                                    </a>
                                    <button type="button"
                                            class="btn dropdown-toggle"
                                            data-toggle="dropdown">
                                        <span class="caret"></span>
                                    </button>

                                    <?php if (count($this->collection) > 1) { ?>

                                    <ul class="dropdown-menu">
                                        <li class="divider"></li>
                                        <li><a class="delete"
                                               title="<?= $this->translate('Delete product') ?>"
                                               href="/admin/shares/addon-category?a=delete&id=<?= $item->id ?>"><?= $this->translate('Delete') ?></a></li>
                                    </ul>

                                    <?php } ?>
                                </li>
                            </ul>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>

        <?php } else { ?>

            <p><?=
                $this->translate(
                    'You haven\'t added a product yet.  <a href="%s">Let\'s add one now.</a>',
                    '/admin/shares/addon'
                ); ?></p>

        <?php } ?>
    </article>

    <?= $this->render('admin-sub-nav.phtml'); ?>
</section>
