<?php
    $this->headTitle($this->translate('Deliveries'));

    $this->loader()->append('jquery_dataTables')
        ->append('jquery_dropdown');
    $this->loadDatejs(Bootstrap::$locale);
?>

<?php $this->placeholder('foot')->captureStart() ?>
<script type="text/javascript">

    $(document).ready(function(){

        $.fn.dataTableExt.aoFeatures.push({
            "fnInit": function(oSettings) {
                return $('<ul class="dataTables_add dropdown-container"><li class="dropdown btn-group">' +
                    '<a href="#" title="<?= $this->translate('Actions') ?>" class="btn">' +
                    '<?= addslashes($this->translate('Actions')) ?></a>' +
                    '<button type="button" class="btn dropdown-toggle" data-toggle="dropdown">' +
                    '<span class="caret"></span></button>' +
                    '<ul class="dropdown-menu">' +
                    '<li><a href="/admin/shares/delivery" title="<?= $this->translate('Add delivery') ?>">' +
                    '<?= $this->translate('Add delivery') ?></a></li>' +
                    '<li><a href="/admin/shares/deliveries/format/csv/year/<?= (int) $this->year ?>" title="<?= $this->translate('Export to a spreadsheet program') ?>">' +
                    '<?= $this->translate('Export to CSV') ?></a></li></ul></li></ul>')[0];
            },
            "cFeature": "a",
            "sFeature": "Add"
        });

        $.fn.dataTableExt.aoFeatures.push({
            "fnInit": function(oSettings) {
                return $(
                    '<form class="dataTables_year" action="/admin/shares/deliveries" method="get" style="float: left; padding-right: 10px">' +
                    <?php if (count($this->years) > 1) { ?>
                        '<label for="year"><?= addslashes($this->translate('Year')); ?>: </label>' +
                        '<?=
                            addslashes(str_replace("\n", '', $this->formSelect(
                                'year',
                                $this->year,
                                array(),
                                $this->years
                            )));
                        ?>' +
                    <?php } ?>
                    '</form> '
                )[0];
            },
            "cFeature": "y",
            "sFeature": "Year"
        });

        var table = $("#deliveries").dataTable({
            "bJQueryUI": true,
            "bAutoWidth": false,
            "bDeferRender": true,
            "bLengthChange": false,
            "bProcessing": true,
            "iDisplayLength": 50,
            "iDeferLoading": <?= $this->foundRows ?>,
            "aaSorting": [[1, "desc"]],
            "aoColumns": [
                {
                    "sType": "string",
                    "mDataProp": "shareName",
                    "fnRender": function (oObj) {
                        return oObj.aData.shareName
                            .replace(/&/g,'&amp;')
                            .replace(/</g,'&lt;')
                            .replace(/>/g,'&gt;');
                    }
                },
                {
                    "sType": "html",
                    "mDataProp": "week",
                    "fnRender": function (oObj) {
                        if (!oObj.aData.hasOwnProperty("id")) {
                            return oObj.aData.week;
                        } else {
                            var weekArray = oObj.aData.week.split("W");
                            var week = weekArray[1],
                                year = weekArray[0],
                                date = new Date(),
                                range = "";

                                date.setYear(year);
                                date.setWeek(week);

                                if (date.getDay() > 1) {
                                    date.setDate(date.getDate() - (date.getDay() - 1));
                                } else if (date.getDay() < 1) {
                                    date.setDate(date.getDate() + 1);
                                }

                                range = date.toString("yyyy-MM-dd") + " - ";

                                date.setDate(date.getDate() + 6);

                                range += date.toString("yyyy-MM-dd");

                            return '<a href="/admin/shares/delivery?id=' +
                                parseInt(oObj.aData.id) + '">' + range + '</a>';
                        }
                    }
                },
                {
                    "sType": "string",
                    "mDataProp": "enabled",
                    "fnRender": function(oObj) {
                        if (!oObj.aData.hasOwnProperty("id")) {
                            return oObj.aData.enabled;
                        }
                        if (parseInt(oObj.aData.enabled) == true) {
                            return "<?= addslashes($this->translate('Yes')) ?>";
                         } else {
                             return "<?= addslashes($this->translate('No')) ?>";
                         }
                    }
                },
                {
                    "bSortable": false,
                    "bSearchable": false,
                    "mDataProp": "_actions",
                    "sClass": "right",
                    "fnRender": function (oObj) {
                        if (!oObj.aData.hasOwnProperty("id")) {
                            return oObj.aData._actions;
                        }
                        return '<ul class="dropdown-container">' +
                            '<li class="dropdown btn-group">' +
                            '<a href="/admin/shares/delivery?id=' + parseInt(oObj.aData.id) + '"' +
                            ' title="<?= $this->translate('Edit delivery') ?>" class="btn">' +
                            '<?= addslashes($this->translate('Edit')) ?></a>' +
                            '<button type="button" class="btn dropdown-toggle" data-toggle="dropdown">' +
                            '<span class="caret"></span></button>' +
                            '<ul class="dropdown-menu"><li class="divider"></li>' +
                            '<li><a class="delete" title="<?= addslashes($this->translate('Delete delivery')) ?>" ' +
                            ' href="/admin/shares/delivery?a=delete&id=' + parseInt(oObj.aData.id) + '"><?= addslashes($this->translate('Delete')) ?></a></li>' +
                            '</ul></li></ul>';
                    }
                }
            ],
            "bSortClasses": false,
            "sAjaxSource": "<?= addslashes($this->Url()) ?>",
            "bServerSide": true,
            "sDom": '<"H"ya<"clear">r<"right"ip>>t<"F"<"right"ip>>'
        })
        .delegate("tbody tr", "mouseover mouseout", function(e) {
            if (e.type == "mouseover") {
                $(e.currentTarget).addClass('hover');
            } else {
                $(e.currentTarget).removeClass('hover');
            }
        })
        .delegate(".delete", "click", function(){
            return window.confirm("<?= $this->translate('Are you sure you want to delete this delivery?  No turning back after a delivery delete.'); ?>");
        });

        new FixedHeader(table);

        $(".dataTables_year select").change(function(){
            window.location = '/admin/shares/deliveries/year/' + $(this).val();
        });

        $('.dropdown-toggle').dropdown();
    });
</script>
<?php $this->placeholder('foot')->captureEnd() ?>

<h2>
    <span class="icon-menu icon-menu-shares" style="float: left; margin: -10px 7px 0 0;"></span>
    <?= $this->translate('Deliveries') ?>
</h2>

<section class="container_12">
    <article class="grid_9">

        <?php if (!empty($this->messages)) { ?>
            <section class="info ui-widget ui-state-highlight ui-corner-all">
                <div>
                    <i class="fa fa-info-circle"></i>
                    <strong><?= $this->translate('Hey!'); ?></strong>
                    <?= $this->escape(implode('; ', $this->messages)); ?>
                </div>
            </section>
        <?php } ?>

        <?php if (count($this->deliveries) || !empty($this->years)) { ?>

            <table id="deliveries" class="display">
                <thead>
                    <tr>
                        <th
                            width="40%"
                            title="<?= $this->translate('Share Name') ?>">
                                <?= $this->translate('Share'); ?>
                        </th>
                        <th
                            width="30%"
                            title="<?= $this->translate('Delivery Date') ?>">
                                <?= $this->translate('Date') ?>
                        </th>
                        <th
                            width="15%"
                            title="<?= $this->translate('Delivery Status') ?>">
                                <?= $this->translate('Enabled') ?>
                        </th>
                        <th
                            width="15%"
                            title="<?= $this->translate('Delivery Actions') ?>">
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->deliveries as $delivery) { ?>
                        <tr>
                            <td>
                                <?= $this->escape($delivery->shareName); ?>
                            </td>
                            <td>
                                <?php
                                    list($year , $week) = explode('W', $delivery->week);

                                    $date = new Zend_Date();
                                    $date->setYear($year);
                                    $date->setWeek($week);
                                    $date->set(1, Zend_Date::WEEKDAY_8601);
                                    $timestamp = $date->getTimestamp();

                                    $range = $date->toString('yyyy-MM-dd') . ' - ';
                                    $date->set(7, Zend_Date::WEEKDAY_8601);
                                    $range .= $date->toString('yyyy-MM-dd');
                                ?>
                                <a data-timestamp="<?= $timestamp ?>" href="/admin/shares/delivery?id=<?= (int) $delivery->id ?>">
                                    <?= $this->escape($range); ?>
                                </a>
                            </td>
                            <td>
                                <?= ($delivery->enabled) ?
                                        $this->translate('Yes') :
                                        $this->translate('No');
                                ?>
                            </td>
                            <td class="right">
                                <ul class="dropdown-container">
                                    <li class="dropdown btn-group">
                                        <a href="/admin/shares/delivery?id=<?= (int) $delivery->id ?>"
                                           title="<?= $this->translate('Edit delivery') ?>"
                                           class="btn">
                                            <?= $this->translate('Edit') ?>
                                        </a>
                                        <button type="button"
                                                class="btn dropdown-toggle"
                                                data-toggle="dropdown">
                                            <span class="caret"></span>
                                        </button>

                                        <ul class="dropdown-menu">
                                            <li class="divider"></li>
                                            <li><a class="delete"
                                                   title="<?= $this->translate('Delete delivery') ?>"
                                                   href="/admin/shares/delivery?a=delete&id=<?= (int) $delivery->id ?>"><?= $this->translate('Delete') ?></a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </td>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>

        <?php } else { ?>

            <?php if (!empty($this->deliveries)) { ?>
                <p><?=
                    $this->translate(
                        'You haven\'t added a delivery yet.  <a href="%s">Let\'s add one now.</a>',
                        '/admin/shares/delivery'
                    ); ?></p>
            <?php } else { ?>
                <p><?=
                    $this->translate(
                        'You haven\'t added a share yet.  <a href="%s">Let\'s add one now.</a>',
                        '/admin/shares/share'
                    ); ?></p>
            <?php } ?>
        <?php } ?>
    </article>

    <?= $this->render('admin-sub-nav.phtml'); ?>
</section>
