<?php
    $this->headTitle($this->translate('Delivery & Pickup Locations'));

    $this->loader()->append('jquery_dataTables')
        ->append('jquery_dropdown');

    $year = date('Y');;
    $this->loadDatejs(Bootstrap::$locale);
?>

<?php $this->placeholder('foot')->captureStart() ?>
<script type="text/javascript">
    $(document).ready(function(){

        $.fn.dataTableExt.aoFeatures.push({
            "fnInit": function(oSettings) {
                return $('<ul class="dataTables_add dropdown-container"><li class="dropdown btn-group">' +
                    '<a href="/admin/shares/location" title="<?= $this->translate('Add location') ?>" class="btn">' +
                    '<?= addslashes($this->translate('Add')) ?></a></li></ul>')[0];
            },
            "cFeature": "a",
            "sFeature": "Add"
        });

        var table = $("#locations").dataTable({
            "bJQueryUI": true,
            "bAutoWidth": false,
            "bDeferRender": true,
            "bLengthChange": false,
            "bProcessing": true,
            "iDisplayLength": 50,
            "iDeferLoading": <?= $this->foundRows ?>,
            "aaSorting": [[1, "asc"]],
            "aoColumns": [
                {
                    "sType": "html",
                    "mDataProp": "name",
                    "fnRender": function (oObj) {
                        if (!oObj.aData.hasOwnProperty("id")) {
                            return oObj.aData.name;
                        } else {
                            return '<a href="/admin/shares/location?id=' +
                                parseInt(oObj.aData.id) + '">' + oObj.aData.name
                                    .replace(/&/g,'&amp;')
                                    .replace(/</g,'&lt;')
                                    .replace(/>/g,'&gt;') + '</a>';
                        }
                    }
                },
                {
                    "sType": "text",
                    "mDataProp": "city",
                    "fnRender": function (oObj) {
                        if (!oObj.aData.hasOwnProperty("id")) {
                            return oObj.aData.city;
                        } else {
                            return oObj.aData.city
                                    .replace(/&/g,'&amp;')
                                    .replace(/</g,'&lt;')
                                    .replace(/>/g,'&gt;');
                        }
                    }
                },
                {
                    "sType": "text",
                    "mDataProp": "time",
                    "fnRender": function (oObj) {
                        if (!oObj.aData.hasOwnProperty("id")) {
                            return oObj.aData.time;
                        } else {
                            var timeStart = oObj.aData.timeStart.split(":"),
                                timeEnd = oObj.aData.timeEnd.split(":"),
                                day = new Date(),
                                dayOfWeek = oObj.aData.dayOfWeek,
                                result = "";

                            if (dayOfWeek == 7) {
                                dayOfWeek = 0;
                            }

                            while (day.getDay() != dayOfWeek) {
                                day.addDays(1);
                            }

                            day.setHours(timeStart[0], timeStart[1]);

                            result = day.toString("ddd h:mm tt");

                            day.setHours(timeEnd[0], timeEnd[1]);

                            result += day.toString(" h:mm tt");

                            return result;
                        }
                    }
                },
                {
                    "sType": "text",
                    "mDataProp": "enabled",
                    "fnRender": function (oObj) {
                        if (!oObj.aData.hasOwnProperty("id")) {
                            return oObj.aData.enabled;
                        } else {
                            return oObj.aData.enabled ? '<?= addslashes($this->translate('Yes')) ?>' : '<?= addslashes($this->translate('No')) ?>';
                        }
                    }
                },
                {
                    "bSortable": false,
                    "bSearchable": false,
                    "mDataProp": "_actions",
                    "sClass": "right",
                    "fnRender": function (oObj) {
                        if (!oObj.aData.hasOwnProperty("id")) {
                            return oObj.aData._actions;
                        }
                        var menu = '<ul class="dropdown-container">' +
                            '<li class="dropdown btn-group">' +
                            '<a href="/admin/shares/location?id=' + parseInt(oObj.aData.id) + '"'+
                            ' title="<?= addslashes($this->translate('Edit location')) ?>"' +
                            ' class="btn"><?= addslashes($this->translate('Edit')) ?></a>' +
                            '<button type="button" class="btn dropdown-toggle" data-toggle="dropdown">' +
                            '<span class="caret"></span></button>' +
                            '<ul class="dropdown-menu">';

                        menu += '<li><a href="/admin/newsletter/issue?recipients[]=LOCATION:' + parseInt(oObj.aData.id) + '|' + new Date().getFullYear() + '"' +
                            ' title="<?= addslashes($this->translate('Send a group email to all subscribers of this delivery location')) ?>">' +
                            ' <?= addslashes($this->translate('Email Subscribers')) ?>' +
                            '</a></li>';

                        menu += '<li class="divider"></li>' +
                            '<li><a class="delete" title="<?= addslashes($this->translate('Delete location')) ?>" ' +
                            ' href="/admin/shares/location?a=delete&id=' + parseInt(oObj.aData.id) + '"><?= addslashes($this->translate('Delete')) ?></a></li>'
                            '</ul></li></ul>';

                        return menu;
                    }
                }
            ],
            "bSortClasses": false,
            "sAjaxSource": "<?= addslashes($this->Url()) ?>",
            "bServerSide": true,
            "sDom": '<"H"af<"clear">r<"right"ip>>t<"F"<"right"ip>>'
        })
        .delegate("tbody tr", "mouseover mouseout", function(e) {
            if (e.type == "mouseover") {
                $(e.currentTarget).addClass('hover');
            } else {
                $(e.currentTarget).removeClass('hover');
            }
        })
        .delegate(".delete", "click", function(){
            return window.confirm("<?= $this->translate('Are you sure you want to delete this location?  All shares
            using this location will be deleted.'); ?>");
        })
        .fnSetFilteringDelay(1000);

        new FixedHeader(table);

        $('.dropdown-toggle').dropdown();
    });
</script>
<?php $this->placeholder('foot')->captureEnd() ?>

<h2>
    <span class="icon-menu icon-menu-shares" style="float: left; margin: -10px 7px 0 0;"></span>
    <?= $this->escape($this->translate('Delivery & Pickup Locations')) ?>
</h2>

<section class="container_12">
    <article class="grid_9">

        <?php if (!empty($this->messages)) { ?>
            <section class="info ui-widget ui-state-highlight ui-corner-all">
                <div>
                    <i class="fa fa-info-circle"></i>
                    <strong><?= $this->translate('Hey!'); ?></strong>
                    <?= $this->escape(implode('; ', $this->messages)); ?>
                </div>
            </section>
        <?php } ?>

        <?php if (count($this->locations)) { ?>

            <table id="locations" class="display">
                <thead>
                    <tr>
                        <th
                            width="30%"
                            title="<?= $this->translate('Location Name') ?>">
                                <?= $this->translate('Name'); ?>
                        </th>
                        <th
                            width="20%"
                            title="<?= $this->translate('Location Town or City') ?>">
                                <?= $this->translate('Town') ?>
                        </th>
                        <th
                            width="20%"
                            title="<?= $this->translate('Location Pickup Day and Time') ?>">
                                <?= $this->translate('Time') ?>
                        </th>
                        <th
                            width="15%"
                            title="<?= $this->translate('Location Enabled?') ?>">
                                <?= $this->translate('Enabled') ?>
                        </th>
                        <th
                            width="15%"
                            title="<?= $this->translate('Location Actions') ?>">
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->locations as $location) { ?>
                        <tr>
                            <td>
                                <a href="/admin/shares/location?id=<?= (int) $location->id ?>">
                                    <?= $this->escape($location->name); ?>
                                </a>
                            </td>
                            <td>
                                <?= $this->escape($location->city); ?>
                            </td>
                            <td>
                                <?php
                                    list ($hour, $minute) = explode(':', $location->timeStart);
                                    $day = Zend_Date::now()
                                        ->setWeekday($location->dayOfWeek)
                                        ->setHour($hour)
                                        ->setMinute($minute);
                                ?>
                                <?= $day->toString('EEE h:mm a'); ?>
                                <?php
                                    list ($hour, $minute) = explode(':', $location->timeEnd);
                                    $day->setHour($hour)
                                        ->setMinute($minute);
                                ?> -
                                <?= $day->toString('h:mm a'); ?>
                            </td>
                            <td>
                                <?= ($location->enabled) ?
                                        $this->translate('Yes') :
                                        $this->translate('No');
                                ?>
                            </td>
                            <td class="right">
                                <ul class="dropdown-container">
                                    <li class="dropdown btn-group">
                                        <a href="/admin/shares/location?id=<?= (int) $location->id ?>"
                                           title="<?= $this->translate('Edit location') ?>"
                                           class="btn">
                                            <?= $this->translate('Edit') ?>
                                        </a>
                                        <button type="button"
                                                class="btn dropdown-toggle"
                                                data-toggle="dropdown">
                                            <span class="caret"></span>
                                        </button>

                                        <ul class="dropdown-menu">
                                            <li><a href="/admin/newsletter/issue?recipients[]=LOCATION:<?= (int) $location->id ?>|<?= (int) $year ?>"
                                                   title="<?= $this->translate('Send a group email to all subscribers of this location') ?>">
                                                <?= $this->translate('Email Subscribers') ?>
                                                </a></li>
                                            <li class="divider"></li>
                                            <li><a class="delete"
                                                   title="<?= $this->translate('Delete location') ?>"
                                                   href="/admin/shares/location?a=delete&id=<?= (int) $location->id ?>"><?= $this->translate('Delete') ?></a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </td>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>

        <?php } else { ?>

            <p><?=
                $this->translate(
                    'You haven\'t added a delivery or pickup location yet.  <a href="%s">Let\'s add one now.</a>',
                    '/admin/shares/location'
                ); ?></p>

        <?php } ?>
    </article>

    <?= $this->render('admin-sub-nav.phtml'); ?>
</section>