<?php
    $this->headTitle($this->translate('Shares'));

    $this->loader()->append('jquery_dataTables')
        ->append('jquery_dropdown');

    $year = date('Y');
?>

<?php $this->placeholder('foot')->captureStart() ?>
<script type="text/javascript">
    $(document).ready(function(){

        $.fn.dataTableExt.aoFeatures.push({
            "fnInit": function(oSettings) {
                return $('<ul class="dataTables_add dropdown-container"><li class="dropdown btn-group">' +
                    '<a href="/admin/shares/share" title="<?= $this->translate('Add share') ?>" class="btn">' +
                    '<?= addslashes($this->translate('Add')) ?></a></li></ul>')[0];
            },
            "cFeature": "a",
            "sFeature": "Add"
        });

        $.fn.dataTableExt.aoFeatures.push({
            "fnInit": function(oSettings) {
                return $(
                    '<form class="dataTables_year" action="/admin/shares/shares" method="get" style="float: left; padding-right: 10px">' +
                    <?php if (count($this->years) > 1) { ?>
                        '<label for="year"><?= addslashes($this->translate('Year')); ?>: </label>' +
                        '<?=
                            addslashes(str_replace("\n", '', $this->formSelect(
                                'year',
                                $this->year,
                                array(),
                                $this->years
                            )));
                        ?>' +
                    <?php } ?>
                    '</form> '
                )[0];
            },
            "cFeature": "y",
            "sFeature": "Year"
        });

        var table = $("#shares").dataTable({
            "bJQueryUI": true,
            "bAutoWidth": false,
            "bDeferRender": true,
            "bLengthChange": false,
            "bProcessing": true,
            "iDisplayLength": 50,
            "iDeferLoading": <?= $this->foundRows ?>,
            "aaSorting": [[0, "asc"]],
            "aoColumns": [
                {
                    "sType": "html",
                    "mDataProp": "name",
                    "fnRender": function (oObj) {
                        if (!oObj.aData.hasOwnProperty("id")) {
                            return oObj.aData.name;
                        } else {
                            return '<a href="/admin/shares/share?id=' +
                                parseInt(oObj.aData.id) + '">' + oObj.aData.name
                                    .replace(/&/g,'&amp;')
                                    .replace(/</g,'&lt;')
                                    .replace(/>/g,'&gt;') + '</a>';
                        }
                    }
                },
                {
                    "sType": "text",
                    "mDataProp": "deliverySchedule",
                    "fnRender": function (oObj) {
                        if (!oObj.aData.hasOwnProperty("id")) {
                            return oObj.aData.deliverySchedule;
                        } else {
                            switch (oObj.aData.deliverySchedule) {
                                case '<?= HHF_Domain_Share::DELIVERY_SCHEDULE_WEEKLY ?>' :
                                    return '<?= $this->translate('Weekly') ?>';
                                    break;
                                case '<?= HHF_Domain_Share::DELIVERY_SCHEDULE_SEMI_MONTHLY ?>' :
                                    return '<?= $this->translate('Semi-Monthly') ?>';
                                    break;
                                case '<?= HHF_Domain_Share::DELIVERY_SCHEDULE_MONTHLY ?>' :
                                    return '<?= $this->translate('Monthly') ?>';
                                    break;
                            }
                        }
                    }
                },
                {
                    "sType": "text",
                    "mDataProp": "enabled",
                    "fnRender": function (oObj) {
                        if (!oObj.aData.hasOwnProperty("id")) {
                            return oObj.aData.enabled;
                        } else {
                            return oObj.aData.enabled ? '<?= addslashes($this->translate('Yes')) ?>' : '<?= addslashes($this->translate('No')) ?>';
                        }
                    }
                },
                {
                    "bSortable": false,
                    "bSearchable": false,
                    "mDataProp": "_actions",
                    "sClass": "right",
                    "fnRender": function (oObj) {
                        if (!oObj.aData.hasOwnProperty("id")) {
                            return oObj.aData._actions;
                        }
                        var menu = '<ul class="dropdown-container">' +
                            '<li class="dropdown btn-group">' +
                            '<a href="/admin/shares/share?id=' + parseInt(oObj.aData.id) + '"'+
                            ' title="<?= addslashes($this->translate('Edit share')) ?>"' +
                            ' class="btn"><?= addslashes($this->translate('Edit')) ?></a>' +
                            '<button type="button" class="btn dropdown-toggle" data-toggle="dropdown">' +
                            '<span class="caret"></span></button>' +
                            '<ul class="dropdown-menu">';

                        if (oObj.aData.year + 1 >= new Date().getFullYear()) {
                            menu += '<li><a href="/admin/newsletter/issue?recipients[]=SHARE:' + parseInt(oObj.aData.id) + '|' + parseInt(oObj.aData.year) + '"' +
                                ' title="<?= addslashes($this->translate('Send a group email to all subscribers of this share')) ?>">' +
                                ' <?= addslashes($this->translate('Email Subscribers')) ?>' +
                                '</a></li>';
                        }

                        menu += '<li class="divider"></li>' +
                            '<li><a class="delete" title="<?= addslashes($this->translate('Delete share')) ?>" ' +
                            ' href="/admin/shares/share?a=delete&id=' + parseInt(oObj.aData.id) + '"><?= addslashes($this->translate('Delete')) ?></a></li>'
                            '</ul></li></ul>';

                        return menu;
                    }
                }
            ],
            "bSortClasses": false,
            "sAjaxSource": "<?= addslashes($this->Url()) ?>",
            "bServerSide": true,
            "sDom": '<"H"yaf<"clear">r<"right"ip>>t<"F"<"right"ip>>'
        })
        .delegate("tbody tr", "mouseover mouseout", function(e) {
            if (e.type == "mouseover") {
                $(e.currentTarget).addClass('hover');
            } else {
                $(e.currentTarget).removeClass('hover');
            }
        })
        .delegate(".delete", "click", function(){
            return window.confirm("<?= $this->translate('Are you sure you want to delete this share?  No turning back after a share delete.'); ?>");
        })
        .fnSetFilteringDelay(1000);

        new FixedHeader(table);

        $(".dataTables_year select").change(function(){
            window.location = '/admin/shares/shares/year/' + $(this).val();
        });

        $('.dropdown-toggle').dropdown();
    });
</script>
<?php $this->placeholder('foot')->captureEnd() ?>

<h2>
    <span class="icon-menu icon-menu-shares" style="float: left; margin: -10px 7px 0 0;"></span>
    <?= $this->translate('Shares') ?>
</h2>

<section class="container_12">
    <article class="grid_9">

        <?php if (!empty($this->messages)) { ?>
            <section class="info ui-widget ui-state-highlight ui-corner-all">
                <div>
                    <i class="fa fa-info-circle"></i>
                    <strong><?= $this->translate('Hey!'); ?></strong>
                    <?= $this->escape(implode('; ', $this->messages)); ?>
                </div>
            </section>
        <?php } ?>

        <?php if (count($this->shares) || !empty($this->years)) { ?>

            <table id="shares" class="display">
                <thead>
                    <tr>
                        <th
                            width="40%"
                            title="<?= $this->translate('Share Name') ?>">
                                <?= $this->translate('Name'); ?>
                        </th>
                        <th
                            width="25%"
                            title="<?= $this->translate('Share Delivery Schedule') ?>">
                                <?= $this->translate('Delivery') ?>
                        </th>
                        <th
                            width="20%"
                            title="<?= $this->translate('Share Status') ?>">
                                <?= $this->translate('Enabled') ?>
                        </th>
                        <th
                            width="15%"
                            title="<?= $this->translate('Share Actions') ?>">
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->shares as $share) { ?>
                        <tr>
                            <td>
                                <a href="/admin/shares/share?id=<?= (int) $share->id ?>">
                                    <?= $this->escape($share->name); ?>
                                </a>
                            </td>
                            <td>
                                <?php

                                    switch ($share->deliverySchedule) {
                                        case HHF_Domain_Share::DELIVERY_SCHEDULE_WEEKLY :
                                            echo $this->translate('Weekly');
                                            break;
                                        case HHF_Domain_Share::DELIVERY_SCHEDULE_SEMI_MONTHLY :
                                            echo $this->translate('Semi-Monthly');
                                            break;
                                        case HHF_Domain_Share::DELIVERY_SCHEDULE_MONTHLY :
                                            echo $this->translate('Monthly');
                                            break;
                                    }
                                ?>
                            </td>
                            <td>
                                <?= ($share->enabled) ?
                                        $this->translate('Yes') :
                                        $this->translate('No');
                                ?>
                            </td>
                            <td class="right">
                                <ul class="dropdown-container">
                                    <li class="dropdown btn-group">
                                        <a href="/admin/shares/share?id=<?= (int) $share->id ?>"
                                           title="<?= $this->translate('Edit share') ?>"
                                           class="btn">
                                            <?= $this->translate('Edit') ?>
                                        </a>
                                        <button type="button"
                                                class="btn dropdown-toggle"
                                                data-toggle="dropdown">
                                            <span class="caret"></span>
                                        </button>

                                        <ul class="dropdown-menu">
                                            <?php if ($share->year + 1 >= $year) { ?>
                                            <li><a href="/admin/newsletter/issue?recipients[]=SHARE:<?= (int) $share->id ?>|<?= (int) $share->year ?>"
                                                   title="<?= $this->translate('Send a group email to all subscribers of this share') ?>">
                                                <?= $this->translate('Email Subscribers') ?>
                                                </a></li>
                                            <?php } ?>
                                            <li class="divider"></li>
                                            <li><a class="delete"
                                                   title="<?= $this->translate('Delete share') ?>"
                                                   href="/admin/shares/share?a=delete&id=<?= (int) $share->id ?>"><?= $this->translate('Delete') ?></a></li>
                                        </ul>
                                    </li>
                                </ul>

                            </td>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>

        <?php } else { ?>

            <p><?=
                $this->translate(
                    'You haven\'t added a share yet.  <a href="%s">Let\'s add one now.</a>',
                    '/admin/shares/share'
                ); ?></p>

        <?php } ?>
    </article>

    <?= $this->render('admin-sub-nav.phtml'); ?>
</section>
