<?php

if(empty($this->share)){
    $title = $this->translate('New Share');

} else{
    $title = $this->translate('Edit Share');
}

$this->headTitle($title);

$this->loader()->append('jquery_validate')->append('jquery_metadata')->append('jquery_ui_multiselect.js')->append('ckeditor_ckeditor.js')->append('ckeditor_adapters_jquery.js')->append('jquery_tmpl');

$this->loadDatejs(Bootstrap::$locale);

$sizes = $this->getFormValue(null, 'sizes');
$sizes = count($sizes);
if($sizes == 0){
    $sizes = 1;
}

$durations = $this->getFormValue(null, 'durations');
$durations = count($durations);
if($durations == 0){
    $durations = 1;
}

$year = date('Y');

$years = array($year => $year, $year + 1 => $year + 1,);

$currentYear = ($this->getFormValue('year')) ? $this->getFormValue('year') : $year;

$weeks = array('' => '');
$date = new Zend_Date();

if(!empty($this->share)){
    $date->setYear($this->getFormValue('year'));
}

for($x = 1; $x <= 52; ++$x){

    $date->setWeek($x);
    $date->setWeekday(1);

    $weeks[$x] = $this->translate('Week %s (%s - %s)', $x, $date->get('yyyy-MM-dd'), $date->setWeekday(7)->get('yyyy-MM-dd'));
}
?>
<?php $this->placeholder('head')->captureStart() ?>
<script type="text/javascript">
    window.CKEDITOR_BASEPATH = '<?= (!empty($_SERVER['HTTPS'])) ? 'https://static.' : 'http://static.' ?><?= Bootstrap::$rootDomain ?>/_js/ckeditor/';
</script>
<?php $this->placeholder('head')->captureEnd() ?>

<?php $this->placeholder('foot')->captureStart() ?>
<script type="text/javascript">

    var config = {
        customConfig: '',
        toolbar: [
            ['Bold', 'Italic', 'Underline', 'Strike'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', 'Blockquote'],
            ['Link', 'Unlink'],
            ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord'],
            ['Undo', 'Redo']
                ['RemoveFormat']
        ],
        colorButton_enableMore: false,
        disableNativeSpellChecker: false
    };

    function buildWeeks(year) {
        var date = new Date(),
            iCount = 1,
            range = '',
            options = '';

        date.setYear(year);
        if (date.getDay() > 1) {
            date.setDate(date.getDate() - (date.getDay() - 1));
        } else if (date.getDay() < 1) {
            date.setDate(date.getDate() + 1);
        }

        date.setWeek(1);

        while (iCount <= 53) {
            var week = date.getISOWeek(),
                copiedDate = new Date(date.getTime());

            if (iCount > 2 && week == '01') {
                break;
            }

            if (copiedDate.getDay() > 1) {
                copiedDate.setDate(copiedDate.getDate() - (copiedDate.getDay() - 1));
            } else if (copiedDate.getDay() < 1) {
                copiedDate.setDate(copiedDate.getDate() + 1);
            }

            range = '<?= addslashes($this->translate('Week')) ?> ' + iCount + ' (' + copiedDate.toString("yyyy-MM-dd") + " - ";

            copiedDate.setDate(copiedDate.getDate() + 6);

            range += copiedDate.toString("yyyy-MM-dd") + ')';

            if (week.toString().length == 1) {
                week = "0" + week.toString();
            }

            options += '<option value="' + iCount + '" label="' + range + '">' + range + '</option>';

            date.addWeeks(1);

            iCount++;
        }

        return options;
    }
    ;

    $(document).ready(function () {

        $('#year').change(function () {
            var $year = $(this)
            options = buildWeeks($year.val());

            // update startWeeks
            $('.startWeek, .cutOffWeek').each(function () {
                var selectElement = $(this),
                    val = selectElement.val();

                selectElement.empty();
                selectElement.append(options);
                selectElement.val(val);
            });
        });

        $("#purchaseStartDate").datepicker({
            dateFormat: 'yy-mm-dd'
        });

        $("#customerPurchaseStartDate").datepicker({
            dateFormat: 'yy-mm-dd'
        });

        $(".fullPaymentDueDate").datepicker({
            dateFormat: 'yy-mm-dd'
        });

        $('#details').ckeditor(
            function () {
                var editor = $('#details').ckeditorGet();
                editor.on("blur", function () {
                    this.updateElement();
                });
            },
            config
        );

        $('select.locations').multiselect({
            header: false
        });

        <?php for ($s = 0; $s < $sizes; ++$s) { ?>
        $('#sizes_<?= $s ?>_details').ckeditor(
            function () {
                var editor = $('#sizes_<?= $s ?>_details').ckeditorGet();
                editor.on("blur", function () {
                    this.updateElement();
                });
            },
            config
        );
        <?php } ?>

        $("#deliverySchedule").change(function () {
            var schedule = $(this).val();
            $("div.duration").each(function () {
                var iterations = $(this).find("select.iterations");
                var options = '<option label="" value=""></option>';
                var max = 52;

                switch (schedule) {
                    case '<?= HHF_Domain_Share::DELIVERY_SCHEDULE_WEEKLY ?>' :
                        max = 52;
                        break;
                    case '<?= HHF_Domain_Share::DELIVERY_SCHEDULE_SEMI_MONTHLY ?>' :
                        max = 26;
                        break;
                    case '<?= HHF_Domain_Share::DELIVERY_SCHEDULE_MONTHLY ?>' :
                        max = 12;
                        break;
                }

                for (var i = 1; i <= max; ++i) {
                    if (i == max) {
                        options += '<option label="' + i + '" value="' + i + '" selected="selected">' + i + '</option>';
                    } else {
                        options += '<option label="' + i + '" value="' + i + '">' + i + '</option>';
                    }
                }

                iterations.empty();
                iterations.append(options);
            });
        });

        $("#share").validate({
            rules: {},
            messages: {},
            errorContainer: $("#formError"),
            errorPlacement: function (error, element) {
                error.insertAfter(element.parent().children().last());
            },
            submitHandler: function (form) {
                var hasFull = false;

                $("div.size").each(function () {
                    var val = $(this).find("select").val();
                    if (val == '1') {
                        hasFull = true;
                    }
                });

                $('#details').ckeditorGet().updateElement();

                $(".sizes-details").each(function () {
                    $(this).ckeditorGet().updateElement();
                })

                if (!hasFull) {
                    alert("<?= $this->translate('Before you can save your share, at lease one full share size needs to be added.') ?>");
                } else {
                    form.submit();
                }
            }
        });

        $("button.size-add").click(function () {
            var $this = $(this), sizes = $("div.size"),
                count = 0, maxId = 0;

            count = sizes.length;

            sizes.each(function () {
                if ($(this).data("id") > maxId) {
                    maxId = $(this).data("id");
                }
            });

            if (count > 0) {
                var tmpl = $("#sizeTemplate")
                    .tmpl([{s: maxId + 1}]);

                tmpl.hide().insertAfter(sizes.last());
            } else {
                var tmpl = $("#sizeTemplate").tmpl([{s: maxId + 1}]);
                tmpl.find("button.size-remove").parent("p").hide();
                tmpl.hide();
                tmpl.insertAfter("#sizes-container legend");
            }

            tmpl.find(".tooltip").qtip({
                style: {
                    classes: 'ui-tooltip-shadow ui-tooltip-rounded',
                    widget: true
                },
                position: {
                    my: 'bottom right',
                    at: 'top center',
                    method: 'flip'
                }
            });

            $('#sizes_' + (maxId + 1) + '_details').ckeditor(
                function () {
                    var editor = $('#sizes_' + (maxId + 1) + '_details').ckeditorGet();
                    editor.on("blur", function () {
                        this.updateElement();
                    });
                },
                config
            );

            tmpl.show("normal", function () {
                $('#size_' + (maxId + 1) + '_size').focus();
            })
        });

        $("#sizes-container").delegate("button.size-remove", "click", function () {
            var $this = $(this), id = $this.data("id"), size = false, count = 0;
            $("div.size").each(function () {
                if ($(this).data("id") == id) {
                    size = $(this);
                }
                ++count;
            });

            if (size !== false) {
                try {
                    var editor = $('#sizes_' + id + '_details').ckeditorGet();
                    editor.destroy(true);
                } catch (e) {

                }

                size.hide("normal", function () {
                    $(this).remove();
                })
            }
        });

        $("button.duration-add").click(function () {
            var $this = $(this), durations = $("div.duration"),
                count = 0, maxId = 0;

            count = durations.length;

            durations.each(function () {
                if ($(this).data("id") > maxId) {
                    maxId = $(this).data("id");
                }
            });

            var schedule = $("#deliverySchedule").val();
            var options = '<option label="" value=""></option>';
            var max = 52;
            switch (schedule) {
                case '<?= HHF_Domain_Share::DELIVERY_SCHEDULE_WEEKLY ?>' :
                    max = 52;
                    break;
                case '<?= HHF_Domain_Share::DELIVERY_SCHEDULE_SEMI_MONTHLY ?>' :
                    max = 26;
                    break;
                case '<?= HHF_Domain_Share::DELIVERY_SCHEDULE_MONTHLY ?>' :
                    max = 12;
                    break;
            }

            for (var i = 1; i <= max; ++i) {
                if (i == max) {
                    options += '<option label="' + i + '" value="' + i + '" selected="selected">' + i + '</option>';
                } else {
                    options += '<option label="' + i + '" value="' + i + '">' + i + '</option>';
                }
            }

            if (count > 0) {
                var tmpl = $("#durationTemplate")
                    .tmpl([{d: maxId + 1}]);

                var iterations = tmpl.find("select.iterations");
                iterations.empty();
                iterations.append(options);

                var options = buildWeeks($('#year').val());

                // update startWeeks
                tmpl.find('.startWeek, .cutOffWeek').each(function () {
                    var selectElement = $(this);

                    selectElement.empty();
                    selectElement.append(options);
                });

                tmpl.hide().insertAfter(durations.last());
            } else {
                var tmpl = $("#durationTemplate").tmpl([{d: maxId + 1}]);
                tmpl.find("button.duration-remove").parent("p").hide();

                var iterations = tmpl.find("select.iterations");
                iterations.empty();
                iterations.append(options);

                var options = buildWeeks($('#year').val());

                // update startWeeks
                tmpl.find('.startWeek, .cutOffWeek').each(function () {
                    var selectElement = $(this);

                    selectElement.empty();
                    selectElement.append(options);
                });

                tmpl.hide();
                tmpl.insertAfter("#durations-container legend");
            }

            tmpl.find(".locations").multiselect({
                header: false
            });

            tmpl.find(".tooltip").qtip({
                style: {
                    classes: 'ui-tooltip-shadow ui-tooltip-rounded',
                    widget: true
                },
                position: {
                    my: 'bottom right',
                    at: 'top center',
                    method: 'flip'
                }
            });

            tmpl.find(".fullPaymentDueDate").datepicker({
                dateFormat: 'yy-mm-dd'
            });

            tmpl.show("normal", function () {
                $('#duration_' + (maxId + 1) + '_startWeek').focus();
            })
        });

        $("#durations-container").delegate("button.duration-remove", "click", function () {
            var $this = $(this),
                id = $this.data("id"),
                duration = false,
                count = 0;

            $("div.duration").each(function () {
                if ($(this).data("id") == id) {
                    duration = $(this);
                }
                ++count;
            });

            if (duration !== false) {
                duration.hide("normal", function () {
                    $(this).remove();
                })
            }
        });

        $(".tooltip").qtip({
            style: {
                classes: 'ui-tooltip-shadow ui-tooltip-rounded',
                widget: true
            },
            position: {
                my: 'bottom right',
                at: 'top center',
                method: 'flip'
            }
        });
    });
</script>
<script id="sizeTemplate" type="text/x-jquery-tmpl">
    <div class="size box" data-id="${s}">
        <p>
            <label for="sizes_${s}_size" class="required">
                <?= $this->translate('Share Size'); ?>:
                <abbr title="<?= $this->translate('This field is required'); ?>">*</abbr>
            </label>

            <?= $this->formSelect('sizes[' . $s . '][size]', null, array('id' => 'sizes_' . $s . '_size', 'class' => 'required'), array('0.5' => $this->translate('Half Share'), '1' => $this->translate('Full Share'), '2' => $this->translate('2x Share'),));
    ?>

            <span class="tooltip"
                  title="<?= $this->translate('You should have at least one share size defined.  If you have only one, it should be a full share.'); ?>">
                [?]
            </span>
        </p>

        <p>
            <label for="sizes_${s}_name" class="required" title="<?= $this->translate('Please enter a name for this share size'); ?>">
                <?= $this->translate('Name'); ?>:
                <abbr title="<?= $this->translate('This field is required'); ?>">*</abbr>
            </label>
            <input
                id="sizes_${s}_name"
                name="sizes[${s}][name]"
                type="text"
                title="<?= $this->translate('Please enter a name for this share size'); ?>"
                value=""
                class="required"
                maxlength="255" />

                <span class="tooltip"
                  title="<?= $this->translate('Enter a name for this share size.  The name should be descriptive of how much content one should expect in relationship to other share sizes.'); ?>">
                [?]
            </span>
        </p>

        <p>
            <label for="sizes_${s}_pricePerDelivery" class="required">
                <?= $this->translate('Price Per Delivery'); ?>:
                <abbr title="<?= $this->translate('This field is required'); ?>">*</abbr>
            </label>
            <input
                id="sizes_${s}_pricePerDelivery"
                name="sizes[${s}][pricePerDelivery]"
                type="text"
                class="required number"
                maxlength="6" />

            <span class="tooltip"
                  title="<?= $this->translate('Enter the price of this share size for a <strong>single delivery</strong>.  The price of a single delivery is used with the share duration deliveries to determine the total price for purchasing this share.'); ?>">
                [?]
            </span>
        </p>

        <p>
            <label for="sizes_${s}_fullPaymentDiscount">
                <?= $this->translate('Full Payment Discount'); ?>:
            </label>
            <input
                id="sizes_${s}_fullPaymentDiscount"
                name="sizes[${s}][fullPaymentDiscount]"
                type="text"
                value=""
                class="number"
                placeholder="<?= $this->translate('E.g.: 0.50') ?>"
                maxlength="6" />

            <span class="tooltip"
                  title="<?= $this->translate('Should a dollar discount be offered on the price per delivery when it is payed in full?  If so, how many dollars should be subtracted from the price per delivery?'); ?>">
                [?]
            </span>
        </p>

        <p>
            <label for="sizes_${s}_details" class="" title="<?= $this->translate('Please enter any details about this share size'); ?>">
                <?= $this->translate('Details'); ?>:
            </label>

            <textarea
                id="sizes_${s}_details"
                name="sizes[${s}][details]"
                title="<?= $this->translate('Please enter any details about this share size'); ?>"
                class="large sizes-details"
                cols="10"
                rows="10"></textarea>
        </p>

        <p>
            <label title="<?= $this->translate('Remove this size for this share'); ?>">
                <?= $this->translate('Remove'); ?>:
            </label>

            <button type="button" class="ui-button ui-widget ui-corner-all ui-button-icon-only ui-state-default size-remove" data-id="${s}">
                <span class="ui-button-icon-primary ui-icon ui-icon-minusthick"></span>
                <span class="ui-button-text">
                    <?= $this->translate('Remove This Size'); ?>
                </span>
            </button>
        </p>
    </div>




</script>

<script id="durationTemplate" type="text/x-jquery-tmpl">
    <div class="duration box" data-id="${d}">
        <input type="hidden" name="durations[${d}][sort]" value="${d}" />

        <p>
            <label for="durations_${d}_startWeek" class="required" title="<?= $this->translate('Please enter the week of the year that this share will start'); ?>">
                <?= $this->translate('Start Week'); ?>:
                <abbr title="<?= $this->translate('This field is required'); ?>">*</abbr>
            </label>

            <?= $this->formSelect('durations[${d}][startWeek]', null, array('id' => 'durations_${d}_startWeek', 'class' => 'required startWeek', 'title' => $this->translate('Please enter the week of the year that this share will start')));
    ?>

            <span class="tooltip"
                  title="<?= $this->translate('Enter the week of the year that this share will start.'); ?>">
                [?]
            </span>
        </p>

        <p>
            <label for="durations_${d}_fullPaymentDueDate">
                <?= $this->translate('Full Payment Due Date'); ?>:
            </label>
            <input
                id="durations_${d}_fullPaymentDueDate"
                name="durations[${d}][fullPaymentDueDate]"
                type="text"
                class="large fullPaymentDueDate"
                placeholder="<?= $this->translate('E.g.: ' . date('Y-m-d')) ?>"
                maxlength="255" />

            <span class="tooltip"
                  title="<?= $this->translate('Unless otherwise specified, when making a purchase and choosing to pay in full, the payment is due at the time of purchase.  You can optionally specify here a date when full payments are due.  If the order date is before this date, full payments will not require payment till this date.'); ?>">
                [?]
            </span>
        </p>

        <p>
            <label for="durations_${d}_cutOffWeek">
                <?= $this->translate('Purchase Cut Off'); ?>:
            </label>
            <?= $this->formSelect('durations[${d}][cutOffWeek]', null, array('id' => 'durations_${d}_cutOffWeek', 'class' => 'cutOffWeek', 'title' => $this->translate('Please enter the last week of the year that purchases are available to')));
    ?>
            <span class="tooltip"
                  title="<?= $this->translate('You can optionally specify a cut off point where the share will no longer be avilable for purchase, regardless of inventory.  To do so, enter the week of the year that purchases are available to.'); ?>">
                [?]
            </span>
        </p>
        <p>
            <label for="durations_${d}_iterations" class="required" title="<?= $this->translate('Please enter the number of deliveries per year'); ?>">
                <?= $this->translate('Deliveries a Year'); ?>:
                <abbr title="<?= $this->translate('This field is required'); ?>">*</abbr>
            </label>
            <?php
    $iterations = array('' => '');
    for($x = 1; $x <= 52; ++$x){

        $iterations[$x] = $x;
    }

    echo $this->formSelect('durations[${d}][iterations]', null, array('id' => 'durations_${d}_iterations', 'class' => 'required iterations'), $iterations);
    ?>
            <span class="tooltip"
                  title="<?= $this->translate('Enter the number of total deliveries that will be made for this share.'); ?>">
                [?]
            </span>
        </p>
        <p>
            <label for="durations_${d}_shares" class="required">
                <?= $this->translate('Full Shares for Purchase'); ?>:
                <abbr title="<?= $this->translate('This field is required'); ?>">*</abbr>
            </label>
            <input
                id="durations_${d}_shares"
                name="durations[${d}][shares]"
                type="text"
                value=""
                class="required number"
                maxlength="6" />

            <span class="tooltip"
                  title="<?= $this->translate('Enter the total number of <strong>full shares</strong> available for purchase.  This numberwill be used to determine share ordering capacity.  Once this has been reached, the share will be no longer available for purchase.'); ?>">
                [?]
            </span>
        </p>
        <p>
            <label for="durations_${d}_locations">
                <?= $this->translate('Limit to Locations'); ?>:
            </label>
            <?= $this->formSelectTitle('durations[${d}][locations][]', null, array('id' => 'durations_${d}_locations', 'class' => 'locations'), $this->locations);
    ?>

            <span class="tooltip"
                  title="<?= $this->translate('Specify which pickup or delivery locations this share duration should be limited to, or leave blank so that all locations will be available for selection.'); ?>">
                [?]
            </span>
        </p>
        <p>
            <label title="<?= $this->translate('Remove this duration for this share'); ?>">
                <?= $this->translate('Remove'); ?>:
            </label>

            <button type="button" class="ui-button ui-widget ui-corner-all ui-button-icon-only ui-state-default duration-remove" data-id="${d}">
                <span class="ui-button-icon-primary ui-icon ui-icon-minusthick"></span>
                <span class="ui-button-text">
                    <?= $this->translate('Remove This Duration'); ?>
                </span>
            </button>
        </p>
    </div>




</script>
<?php $this->placeholder('foot')->captureEnd() ?>

<style>
    .size, .duration {
        margin: 20px;
    }
</style>

<h2>
    <span class="icon-menu icon-menu-shares" style="float: left; margin: -10px 7px 0 0;"></span>
    <?= $title ?>
</h2>

<section class="container_12">
    <article class="grid_11">

        <form id="share" action="/admin/shares/share?<?= http_build_query($_GET) ?>" method="post"
              accept-charset="utf-8" class="cmxform large" enctype="multipart/form-data">

            <?php if (!empty($this->messages)) { ?>
                <section class="info ui-widget ui-state-highlight ui-corner-all">
                    <div>
                        <i class="fa fa-info-circle"></i>
                        <strong><?= $this->translate('Hey!'); ?></strong>
                        <?= $this->escape(implode('; ', $this->messages)); ?>
                    </div>
                </section>
            <?php } ?>

            <section id="formError" class="error ui-widget ui-state-error ui-corner-all"
                     style="<?= (!empty($this->errors)) ? '' : 'display:none;' ?>">
                <div>
                    <i class="fa fa-exclamation-triangle"></i>
                    <strong><?= $this->translate('Oh No!'); ?></strong>
                    <?= $this->translate('Something is not right with what you entered.  Check below for hints on how to fix things up.'); ?>
                </div>
            </section>

            <fieldset>
                <legend><?= $this->translate('General Info') ?></legend>

                <p>
                    <label for="year"
                           class="required">
                        <?= $this->translate('Year'); ?>:
                        <abbr title="<?= $this->translate('This field is required'); ?>">*</abbr>
                    </label>
                    <?php
                    if(empty($this->share)){

                        echo $this->formSelect('year', $this->getFormValue('year'), array('id' => 'year', 'class' => 'required', 'title' => $this->translate('Please enter the calendar year this share will be included in'), 'autofocus' => 'autofocus'), $years);
                        ?>
                        <span class="tooltip"
                              title="<?= $this->translate('Please enter the calendar year this share will be included in.  You can create shares that will be available for the current year or next year.'); ?>">
                        [?]
                    </span>

                    <?php } else{ ?>
                        <input
                            id="year"
                            name="year"
                            type="hidden"
                            value="<?= $this->getFormValue('year'); ?>"
                            maxlength="4"/>

                        <span>
                            <?= $this->getFormValue('year'); ?>
                        </span>

                    <?php } ?>
                    <?php if(!empty($this->errors['year'])){ ?>
                        <label for="year" class="error">
                            <?= implode('; ', $this->errors['year']) ?>
                        </label>
                    <?php } ?>
                </p>

                <p>
                    <label for="name" class="required">
                        <?= $this->translate('Name'); ?>:
                        <abbr title="<?= $this->translate('This field is required'); ?>">*</abbr>
                    </label>
                    <input
                        id="name"
                        name="name"
                        type="text"
                        value="<?= $this->getFormValue('name'); ?>"
                        class="required large"
                        maxlength="255"
                        placeholder="<?= $this->translate('E.g.: Veggie Share') ?>"
                        <?= (!empty($this->share)) ? 'autofocus="autofocus"' : ''; ?> />

                    <span class="tooltip"
                          title="<?= $this->escape($this->translate('Please enter a name for your share.  The share name should be short and to the point.  Something like "Veggie Share" is great.')); ?>">
                        [?]
                    </span>

                    <?php if(!empty($this->errors['name'])){ ?>
                        <label for="name" class="error">
                            <?= implode('; ', $this->errors['name']) ?>
                        </label>
                    <?php } ?>
                </p>

                <p>
                    <label for="deliverySchedule" class="required">
                        <?= $this->translate('Delivery Schedule'); ?>:
                        <abbr title="<?= $this->translate('This field is required'); ?>">*</abbr>
                    </label>
                    <?=
                    $this->formSelect('deliverySchedule', $this->getFormValue('deliverySchedule'), array('id' => 'deliverySchedule', 'class' => 'required'), array('' => '', HHF_Domain_Share::DELIVERY_SCHEDULE_WEEKLY => $this->translate('Weekly'), HHF_Domain_Share::DELIVERY_SCHEDULE_SEMI_MONTHLY => $this->translate('Semi-Monthly'), HHF_Domain_Share::DELIVERY_SCHEDULE_MONTHLY => $this->translate('Monthly'),));
                    ?>

                    <span class="tooltip"
                          title="<?= $this->escape($this->translate('Please enter the calendar delivery schedule this share will be following.  <ul><li>Weekly means there will be a delivery every week;</li><li>semi-monthly every two weeks;</li><li>and monthly means once a month</li></ul>')); ?>">
                        [?]
                    </span>

                    <?php if(!empty($this->errors['deliverySchedule'])){ ?>
                        <label for="deliverySchedule" class="error">
                            <?= implode('; ', $this->errors['deliverySchedule']) ?>
                        </label>
                    <?php } ?>
                </p>

                <p>
                    <label for="purchaseStartDate" class="required">
                        <?= $this->translate('Purchase Start Date'); ?>:
                        <abbr title="<?= $this->translate('This field is required'); ?>">*</abbr>
                    </label>
                    <input
                        id="purchaseStartDate"
                        name="purchaseStartDate"
                        type="text"
                        value="<?= $this->getFormValue('purchaseStartDate'); ?>"
                        class="required large"
                        placeholder="<?= $this->translate('E.g.: %s', date('Y-m-d')) ?>"
                        maxlength="255"/>

                    <span class="tooltip"
                          title="<?= $this->translate('Supply a date that this share will begin to be available for purchase.'); ?>">
                        [?]
                    </span>

                    <?php if(!empty($this->errors['purchaseStartDate'])){ ?>
                        <label for="purchaseStartDate" class="error">
                            <?= implode('; ', $this->errors['purchaseStartDate']) ?>
                        </label>
                    <?php } ?>
                </p>

                <p>
                    <label for="customerPurchaseStartDate">
                        <?= $this->translate('Customer Purchase Start Date'); ?>:
                    </label>
                    <input
                        id="customerPurchaseStartDate"
                        name="customerPurchaseStartDate"
                        type="text"
                        value="<?= $this->getFormValue('customerPurchaseStartDate'); ?>"
                        class="large"
                        placeholder="<?= $this->translate('E.g.: ' . date('Y-m-d')) ?>"
                        maxlength="255"/>

                    <span class="tooltip"
                          title="<?= $this->translate('Optionally supply a date that this share will begin to be available for purchase for existing customers.'); ?>">
                        [?]
                    </span>

                    <?php if(!empty($this->errors['customerPurchaseStartDate'])){ ?>
                        <label for="customerPurchaseStartDate" class="error">
                            <?= implode('; ', $this->errors['customerPurchaseStartDate']) ?>
                        </label>
                    <?php } ?>
                </p>

                <p>
                    <label for="locationPrice" class="required">
                        <?= $this->translate('Location Price'); ?>:
                        <abbr title="<?= $this->translate('This field is required'); ?>">*</abbr>
                    </label>
                    <input
                        id="locationPrice"
                        name="locationPrice"
                        type="checkbox"
                        value="1"
                        class=""
                        <?php echo(($this->getFormValue('locationPrice') == 1) ? 'checked="checked"' : '') ?> />

                    <span class="tooltip"
                          title="<?= $this->translate('When purchased, should location delivery prices be applied?'); ?>">
                        [?]
                    </span>

                    <?php if(!empty($this->errors['locationPrice'])){ ?>
                        <label for="locationPrice" class="error">
                            <?= implode('; ', $this->errors['locationPrice']) ?>
                        </label>
                    <?php } ?>
                </p>

                <p>
                    <label for="imageUpload">
                        <?= $this->translate('Image'); ?>:
                    </label>

                    <?php if($this->share != false && $this->share->image){ ?>
                        <img
                            src="/default/file/id/<?= $this->escape($this->share->image) ?>/s/<?= HHF_Domain_File::IMAGE_THUMBNAIL ?>"
                            alt="<?= $this->getFormValue('name') ?>"/>
                        <br style="clear:left;"/>
                    <?php } ?>

                    <input
                        id="image"
                        name="image"
                        type="hidden"
                        value="<?= $this->getFormValue('image'); ?>"/>

                    <input
                        id="imageUpload"
                        name="imageUpload"
                        type="file"
                        title="<?= $this->translate('Provide an image of your share'); ?>"
                        value=""
                        style="<?= ($this->share != false && $this->share->image) ? 'padding-left: 185px' : '' ?>"/>

                    <span class="tooltip"
                          title="<?= $this->translate('You can optionally supply an image to be displayed along side your share.  The image will show up on the sign up form.'); ?>">
                        [?]
                    </span>

                    <?php if(!empty($this->errors['imageUpload'])){ ?>
                        <label for="imageUpload" class="error">
                            <?= implode('; ', $this->errors['imageUpload']) ?>
                        </label>
                    <?php } ?>
                </p>

                <?php if($this->farm->getPreferences()->get('plansFixedDates', 'shares', false)){ ?>

                    <p>
                        <label for="planFixedDates">
                            <?= $this->translate('Fixed Payment Dates'); ?>:
                        </label>
                        <input
                            id="planFixedDates"
                            name="planFixedDates"
                            type="text"
                            value="<?= $this->getFormValue('planFixedDates'); ?>"
                            class="large"
                            placeholder="<?= $this->translate('E.g.: ' . $this->farm->getPreferences()->get('plansFixedDates', 'shares', date('Y-m-d'))) ?>"
                            maxlength="255"/>

                        <span class="tooltip"
                              title="<?= $this->escape($this->translate('What dates should fixed payments, for the fixed payment plan, be made on?  Enter a comma seperated list of year-month-days.  IE: "2020-08-15,2020-10-15,2020-12-15" for August 15, October 15, and December 15 2020.  This will override the default defined fixed payment dates')); ?>">
                            [?]
                        </span>

                        <?php if(!empty($this->errors['planFixedDates'])){ ?>
                            <label for="planFixedDates" class="error">
                                <?= implode('; ', $this->errors['planFixedDates']) ?>
                            </label>
                        <?php } ?>
                    </p>

                <?php } ?>

                <p>
                    <label for="enabled_1" class="required">
                        <?= $this->translate('Enabled'); ?>:
                        <abbr title="<?= $this->translate('This field is required'); ?>">*</abbr>
                    </label>

                    <input
                        id="enabled_0"
                        type="radio"
                        name="enabled"
                        value="0"
                        class="required"
                        title="<?= $this->translate('Don\'t enable share for purchase'); ?>"
                        <?php echo(($this->getFormValue('enabled') == '0') ? 'checked="checked"' : '') ?> />
                    <label for="enabled_0" class="radio"
                           title="<?= $this->translate('Don\'t enable share for purchase'); ?>">
                        <?= $this->translate('Disable'); ?>
                    </label>
                    <input
                        id="enabled_1"
                        type="radio"
                        name="enabled"
                        value="1"
                        title="<?= $this->translate('Share should be enabled for purchase'); ?>"
                        <?php
                        $value = $this->getFormValue('enabled');
                        if($value === null){
                            echo 'checked="checked"';
                        } else if($value == 1){
                            echo 'checked="checked"';
                        }
                        ?> />
                    <label for="enabled_1" class="radio"
                           title="<?= $this->translate('Share should be enabled for purchase'); ?>">
                        <?= $this->translate('Enable'); ?>
                    </label>

                    <span class="tooltip"
                          title="<?= $this->translate('Should this share be enabled for purchase on the sign up form?'); ?>">
                        [?]
                    </span>

                    <?php if(!empty($this->errors['enabled'])){ ?>
                        <label for="enabled" class="error">
                            <?= implode('; ', $this->errors['enabled']) ?>
                        </label>
                    <?php } ?>
                </p>

                <p>
                    <label for="details" class=""
                           title="<?= $this->translate('Please enter any details about this share'); ?>">
                        <?= $this->translate('Details'); ?>:
                    </label>

                    <textarea
                        id="details"
                        name="details"
                        title="<?= $this->translate('Please enter any details about this share'); ?>"
                        class="large"
                        cols="10"
                        rows="10"><?= $this->escape($this->getFormValue('details')); ?></textarea>
                    <?php if(!empty($this->errors['details'])){ ?>
                        <label for="details" class="error">
                            <?= implode('; ', $this->errors['details']) ?>
                        </label>
                    <?php } ?>
                </p>
            </fieldset>


            <fieldset id="durations-container">
                <legend>
                    <?= $this->translate('Durations') ?>

                    <span class="tooltip"
                          title="<?= $this->translate('A share duration marks what dates a share will be available from, and for how long.  You can have multiple durations for a share.  For example, I can have one veggie share with a year long option, as well as summer option.'); ?>">
                        [?]
                    </span>
                </legend>

                <?php for($d = 0; $d < $durations; ++$d){ ?>
                    <div class="duration box" data-id="<?= $d ?>">
                        <input type="hidden"
                               name="durations[<?= $d ?>][id]"
                               value="<?= $this->getFormValue('id', 'durations', $d) ?>"/>

                        <input type="hidden" name="durations[<?= $d ?>][sort]" value="<?= $d ?>"/>

                        <p>
                            <label for="durations_<?= $d ?>_startWeek" class="required">
                                <?= $this->translate('Start Week'); ?>:
                                <abbr title="<?= $this->translate('This field is required'); ?>">*</abbr>
                            </label>

                            <?= $this->formSelect('durations[' . $d . '][startWeek]', $this->getFormValue('startWeek', 'durations', $d), array('id' => 'durations_' . $d . '_startWeek', 'class' => 'required startWeek'), $weeks);
                            ?>

                            <span class="tooltip"
                                  title="<?= $this->translate('Enter the week of the year that this share will start.'); ?>">
                            [?]
                        </span>

                            <?php if(!empty($this->errors['durations'][$d]['startWeek'])){ ?>
                                <label for="durations_<?= $d ?>_startWeek" class="error">
                                    <?= implode('; ', $this->errors['durations'][$d]['startWeek']) ?>
                                </label>
                            <?php } ?>
                        </p>

                        <p>
                            <label for="durations_<?= $d ?>_fullPaymentDueDate">
                                <?= $this->translate('Full Payment Due Date'); ?>:
                            </label>
                            <input
                                id="durations_<?= $d ?>_fullPaymentDueDate"
                                name="durations[<?= $d ?>][fullPaymentDueDate]"
                                type="text"
                                value="<?= $this->getFormValue('fullPaymentDueDate', 'durations', $d); ?>"
                                class="large fullPaymentDueDate"
                                placeholder="<?= $this->translate('E.g.: ' . date('Y-m-d')) ?>"
                                maxlength="255"/>

                        <span class="tooltip"
                              title="<?= $this->translate('Unless otherwise specified, when making a purchase and choosing to pay in full, the payment is due at the time of purchase.  You can optionally specify here a date when full payments are due.  If the order date is before this date, full payments will not require payment till this date.'); ?>">
                            [?]
                        </span>

                            <?php if(!empty($this->errors['durations'][$d]['fullPaymentDueDate'])){ ?>
                                <label for="durations_<?= $d ?>_fullPaymentDueDate" class="error">
                                    <?= implode('; ', $this->errors['durations'][$d]['fullPaymentDueDate']) ?>
                                </label>
                            <?php } ?>
                        </p>

                        <p>
                            <label for="durations_<?= $d ?>_cutOffWeek">
                                <?= $this->translate('Purchase Cut Off'); ?>:
                            </label>

                            <?= $this->formSelect('durations[' . $d . '][cutOffWeek]', $this->getFormValue('cutOffWeek', 'durations', $d), array('id' => 'durations_' . $d . '_cutOffWeek', 'class' => 'cutOffWeek'), $weeks);
                            ?>

                            <span class="tooltip"
                                  title="<?= $this->translate('You can optionally specify a cut off point where the share will no longer be avilable for purchase, regardless of inventory.  To do so, enter the week of the year that purchases are available to.'); ?>">
                            [?]
                        </span>

                            <?php if(!empty($this->errors['durations'][$d]['cutOffWeek'])){ ?>
                                <label for="durations_<?= $d ?>_cutOffWeek" class="error">
                                    <?= implode('; ', $this->errors['durations'][$d]['cutOffWeek']) ?>
                                </label>
                            <?php } ?>
                        </p>

                        <p>
                            <label for="durations_<?= $d ?>_iterations" class="required">
                                <?= $this->translate('Deliveries a Year'); ?>:
                                <abbr title="<?= $this->translate('This field is required'); ?>">*</abbr>
                            </label>

                            <?php
                            $maxWeeks = 52;

                            switch($this->getFormValue('deliverySchedule')){
                                case HHF_Domain_Share::DELIVERY_SCHEDULE_MONTHLY :
                                    $maxWeeks = 12;
                                    break;
                                case HHF_Domain_Share::DELIVERY_SCHEDULE_SEMI_MONTHLY :
                                    $maxWeeks = 26;
                                    break;
                                case HHF_Domain_Share::DELIVERY_SCHEDULE_WEEKLY :
                                    $maxWeeks = 52;
                                    break;
                            }

                            $iterations = array('' => '');
                            for($x = 1; $x <= $maxWeeks; ++$x){

                                $iterations[$x] = $x;
                            }

                            echo $this->formSelect('durations[' . $d . '][iterations]', $this->getFormValue('iterations', 'durations', $d), array('id' => 'durations_' . $d . '_iterations', 'class' => 'required iterations'), $iterations);
                            ?>

                            <span class="tooltip"
                                  title="<?= $this->translate('Enter the number of total deliveries that will be made for this share.'); ?>">
                            [?]
                        </span>

                            <?php if(!empty($this->errors['durations'][$d]['iterations'])){ ?>
                                <label for="durations_<?= $d ?>_iterations" class="error">
                                    <?= implode('; ', $this->errors['durations'][$d]['iterations']) ?>
                                </label>
                            <?php } ?>
                        </p>

                        <p>
                            <label for="durations_<?= $d ?>_shares" class="required">
                                <?= $this->translate('Full Shares for Purchase'); ?>:
                                <abbr title="<?= $this->translate('This field is required'); ?>">*</abbr>
                            </label>
                            <input
                                id="durations_<?= $d ?>_shares"
                                name="durations[<?= $d ?>][shares]"
                                type="text"
                                value="<?= $this->getFormValue('shares', 'durations', $d); ?>"
                                class="required number"
                                maxlength="6"/>

                        <span class="tooltip"
                              title="<?= $this->translate('Enter the total number of <strong>full shares</strong> available for purchase.  This number will be used to determine share ordering capacity.  Once this has been reached, the share will be no longer available for purchase.'); ?>">
                            [?]
                        </span>

                            <?php if(!empty($this->errors['durations'][$d]['shares'])){ ?>
                                <label for="durations_<?= $d ?>_shares" class="error">
                                    <?= implode('; ', $this->errors['durations'][$d]['shares']) ?>
                                </label>
                            <?php } ?>
                        </p>

                        <p>
                            <label for="durations_<?= $d ?>_locations">
                                <?= $this->translate('Limit to Locations'); ?>:
                            </label>


                            <?= $this->formSelectTitle('durations[' . $d . '][locations][]', $this->getFormValue('locations', 'durations', $d), array('id' => 'durations_' . $d . '_locations', 'class' => 'locations', 'title' => $this->translate('Specify which pickup or delivery locations this share duration should be limited to')), $this->locations);
                            ?>

                            <span class="tooltip"
                                  title="<?= $this->translate('Specify which pickup or delivery locations this share duration should be limited to, or leave blank so that all locations will be available for selection.'); ?>">
                            [?]
                        </span>

                            <?php if(!empty($this->errors['durations'][$d]['locations'])){ ?>
                                <label for="durations_<?= $d ?>_locations" class="error">
                                    <?= implode('; ', $this->errors['durations'][$d]['locations']) ?>
                                </label>
                            <?php } ?>
                        </p>

                        <p style="<?= ($d == 0) ? 'display: none' : '' ?>">
                            <label title="<?= $this->translate('Remove this duration for this share'); ?>">
                                <?= $this->translate('Remove'); ?>:
                            </label>

                            <button type="button"
                                    class="ui-button ui-widget ui-corner-all ui-button-icon-only ui-state-default duration-remove"
                                    data-id="<?= $d ?>">
                                <span class="ui-button-icon-primary ui-icon ui-icon-minusthick"></span>
                            <span class="ui-button-text">
                                <?= $this->translate('Remove This Duration'); ?>
                            </span>
                            </button>
                        </p>
                    </div>
                <?php } ?>
                <p>
                    <label title="<?= $this->translate('Add a new duration for this share'); ?>">
                        <?= $this->translate('Add New'); ?>:
                    </label>

                    <button type="button"
                            class="ui-button ui-widget ui-corner-all ui-button-icon-only ui-state-default duration-add">
                        <span class="ui-button-icon-primary ui-icon ui-icon-plusthick"></span>
                        <span class="ui-button-text">
                            <?= $this->translate('Add New Duration'); ?>
                        </span>
                    </button>
                </p>

            </fieldset>

            <fieldset id="vacation-options-container">
                <legend>
                    <?= $this->translate('Vacation Options') ?>
                    <span class="tooltip"
                          title="<?= $this->translate('Specify what can be done with deliveries on weeks customers
                          are absent.
                          .'); ?>">
                        [?]
                    </span>
                </legend>
                <style>
                    #vaca-opt-form input[type=text] {
                        margin: 8px 0;
                    }

                    .box, button {
                        margin: 6px;
                    }
                </style>
                <div class="box">
                    <div id="vaca-opt-form">
                        <?php $numVacaOpt = 0; ?>
                        <?php foreach($this->v as $vacationOpt){
                            $numVacaOpt++;
                            ?>
                        <div id="vacation_<?php echo $numVacaOpt; ?>">
                        <label id="vacation_<?php echo $numVacaOpt; ?>_label" for="vacation_<?php echo $numVacaOpt;
                            ?>_option" class="required">
                            <?= $this->translate('Vacation Option'); ?> <?php echo $numVacaOpt; ?>:
                            <abbr title="<?= $this->translate('This field is required'); ?>">*</abbr>
                        </label>
                        <select
                            id="vacation_<?php echo $numVacaOpt; ?>_option"
                            name="vacation[<?php echo $numVacaOpt; ?>][option]"
                            class="required">
                            <?php
                            foreach(['Opt Out', 'Donate'] as $option){
                                if($vacationOpt->vacationOption == $option){
                                    echo ' <option selected value="'.$option.'">'
                                         .$option.'</option>';
                                } else {
                                    echo ' <option value="'.$option.'">'
                                         .$option.'</option>';
                                }
                            }
                            ?>
                        </select>

                        <button type="button" id="remove-vaca-opt"
                                class="ui-button ui-widget ui-corner-all ui-button-icon-only ui-state-default size-remove"
                                data-option="vacation_<?php echo $numVacaOpt; ?>">
                            <span class="ui-button-icon-primary ui-icon ui-icon-minusthick"></span>
                            <span class="ui-button-text">
                                <?= $this->translate('Remove This Size'); ?>
                            </span>
                        </button>
                        <br id="vacation_<?php echo $numVacaOpt; ?>_break">
                        </div>
                        <?php }
                        if($numVacaOpt == 0){
                            $numVacaOpt++;
                            ?>
                            <div id="vacation_<?php echo $numVacaOpt; ?>">
                            <label id="vacation_<?php echo $numVacaOpt; ?>_label"
                                   for="vacation_<?php echo $numVacaOpt; ?>_option" class="required">
                                <?= $this->translate('Vacation Option'); ?> <?php echo $numVacaOpt; ?>:
                                <abbr title="<?= $this->translate('This field is required'); ?>">*</abbr>
                            </label>

                            <select id="vacation_<?php echo $numVacaOpt; ?>_option"
                                    name="vacation[<?php echo $numVacaOpt; ?>][option]"
                                    class="required">
                                <option value="Donate">Donate</option>
                                <option value="Opt Out">Opt Out</option>
                            </select>

                            <button type="button" id="remove-vaca-opt"
                                    class="ui-button ui-widget ui-corner-all ui-button-icon-only ui-state-default size-remove"
                                    data-option="vacation_<?php echo $numVacaOpt; ?>">
                                <span class="ui-button-icon-primary ui-icon ui-icon-minusthick"></span>
                                <span class="ui-button-text">
                                    <?= $this->translate('Remove This Option'); ?>
                                </span>
                            </button>
                            <br id="vacation_<?php echo $numVacaOpt; ?>_break">
                            </div>
                        <?php } ?>
                    </div>
                    <input id="vaca-option-num" type="hidden" value="<?php echo $numVacaOpt + 1; ?>"/>
                </div>

                <label title="<?= $this->translate('Add a new vacation option for this share'); ?>">
                    <?= $this->translate('Add New'); ?>:
                </label>
                <button type="button"
                        class="ui-button ui-widget ui-corner-all ui-button-icon-only ui-state-default" onclick="addV()">
                    <span class="ui-button-icon-primary ui-icon ui-icon-plusthick"></span>
                    <span class="ui-button-text">
                        <?= $this->translate('Add New'); ?>
                    </span>
                </button>
            </fieldset>
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
            <script>
                numOpts = document.getElementById('vaca-option-num').value;

                function addV() {
                    var elem = '<div id="vacation_' + numOpts + '">';
                    elem += '<label id="vacation_' + numOpts + '_label" ';
                    elem += 'for="vacation_' + numOpts + '_option" class="required">';
                    elem += '<?= $this->translate("Vacation Option"); ?> ' + numOpts + ':';
                    elem += '<abbr title="<?= $this->translate("This field is required"); ?>">&nbsp;*</abbr></label>';
                    elem += '<select id="vacation_' + numOpts + '_option "';
                    elem += 'name="vacation[' + numOpts + '][option]" class="required">';
                    elem += '<option value="Donate">Donate</option>';
                    elem += '<option value="Opt Out">Opt Out</option></select>';
                    elem += '<button type="button" id="remove-vaca-opt" class="ui-button ui-widget ui-corner-all ' +
                    'ui-button-icon-only ';
                    elem += 'ui-state-default size-remove" data-option="vacation_' + numOpts + '">';
                    elem += '<span class="ui-button-icon-primary ui-icon ui-icon-minusthick"></span>';
                    elem += '<span class="ui-button-text"><?= $this->translate('Remove This Option'); ?></span>';
                    elem += '</button><br id="vacation_' + numOpts + '_break">';
                    elem += '</div>';

                    var div = document.getElementById('vaca-opt-form');
                    div.innerHTML += elem;

                    numOpts++;
                }

                $('#vaca-opt-form').on('click', '#remove-vaca-opt', function () {
                    var id = $(this).data("option");
                    $('#' + id).remove();
                    return false;
                });

            </script>

            <fieldset id="sizes-container">
                <legend>
                    <?= $this->translate('Sizes') ?>
                    <span class="tooltip"
                          title="<?= $this->translate('A share can be made available in one or more different sizes (full, half, double).  A share size determines price on purchase.'); ?>">
                        [?]
                    </span>
                </legend>

                <?php for($s = 0; $s < $sizes; ++$s){ ?>
                    <div class="size box" data-id="<?= $s ?>">

                        <input type="hidden"
                               name="sizes[<?= $s ?>][id]"
                               value="<?= $this->getFormValue('id', 'sizes', $s) ?>"/>

                        <p>
                            <label for="sizes_<?= $s ?>_size" class="required">
                                <?= $this->translate('Share Size'); ?>:
                                <abbr title="<?= $this->translate('This field is required'); ?>">*</abbr>
                            </label>

                            <?=
                            $this->formSelect('sizes[' . $s . '][size]', $this->getFormValue('size', 'sizes', $s), array('id' => 'sizes_' . $s . '_size', 'class' => 'required'), array('0.25' => $this->translate('Quarter Share'), '0.5' => $this->translate('Half Share'), '0.75' => $this->translate('Three Quarter Share'), '1' => $this->translate('Full Share'), '2' => $this->translate('2x Share'),));
                            ?>

                            <span class="tooltip"
                                  title="<?= $this->translate('You should have at least one share size defined.  If you have only one, it should be a full share.'); ?>">
                            [?]
                        </span>

                            <?php if(!empty($this->errors['sizes'][$s]['size'])){ ?>
                                <label for="sizes_<?= $s ?>_size" class="error">
                                    <?= implode('; ', $this->errors['sizes'][$s]['size']) ?>
                                </label>
                            <?php } ?>
                        </p>

                        <p>
                            <label for="sizes_<?= $s ?>_name" class="required">
                                <?= $this->translate('Name'); ?>:
                                <abbr title="<?= $this->translate('This field is required'); ?>">*</abbr>
                            </label>
                            <input
                                id="sizes_<?= $s ?>_name"
                                name="sizes[<?= $s ?>][name]"
                                type="text"
                                value="<?= $this->getFormValue('name', 'sizes', $s); ?>"
                                placeholder="<?= $this->translate('E.g.: Full Share') ?>"
                                class="required"
                                maxlength="255"/>

                        <span class="tooltip"
                              title="<?= $this->translate('Enter a name for this share size.  The name should be descriptive of how much content one should expect in relationship to other share sizes.'); ?>">
                            [?]
                        </span>

                            <?php if(!empty($this->errors['sizes'][$s]['name'])){ ?>
                                <label for="sizes_<?= $s ?>_name" class="error">
                                    <?= implode('; ', $this->errors['sizes'][$s]['name']) ?>
                                </label>
                            <?php } ?>
                        </p>

                        <p>
                            <label for="sizes_<?= $s ?>_pricePerDelivery" class="required">
                                <?= $this->translate('Price Per Delivery'); ?>:
                                <abbr title="<?= $this->translate('This field is required'); ?>">*</abbr>
                            </label>
                            <input
                                id="sizes_<?= $s ?>_pricePerDelivery"
                                name="sizes[<?= $s ?>][pricePerDelivery]"
                                type="text"
                                value="<?= $this->getFormValue('pricePerDelivery', 'sizes', $s); ?>"
                                class="required number"
                                placeholder="<?= $this->translate('E.g.: 15') ?>"
                                maxlength="6"/>

                        <span class="tooltip"
                              title="<?= $this->translate('Enter the price of this share size for a <strong>single delivery</strong>.  The price of a single delivery is used with the share duration deliveries to determine the total price for purchasing this share.'); ?>">
                            [?]
                        </span>

                            <?php if(!empty($this->errors['sizes'][$s]['pricePerDelivery'])){ ?>
                                <label for="sizes_<?= $s ?>_pricePerDelivery" class="error">
                                    <?= implode('; ', $this->errors['sizes'][$s]['pricePerDelivery']) ?>
                                </label>
                            <?php } ?>
                        </p>

                        <p>
                            <label for="sizes_<?= $s ?>_fullPaymentDiscount">
                                <?= $this->translate('Full Payment Discount'); ?>:
                            </label>
                            <input
                                id="sizes_<?= $s ?>_fullPaymentDiscount"
                                name="sizes[<?= $s ?>][fullPaymentDiscount]"
                                type="text"
                                value="<?= $this->getFormValue('fullPaymentDiscount', 'sizes', $s); ?>"
                                class="number"
                                placeholder="<?= $this->translate('E.g.: 0.50') ?>"
                                maxlength="6"/>

                        <span class="tooltip"
                              title="<?= $this->translate('Should a dollar discount be offered on the price per delivery when it is payed in full?  If so, how many dollars should be subtracted from the price per delivery?'); ?>">
                            [?]
                        </span>

                            <?php if(!empty($this->errors['sizes'][$s]['fullPaymentDiscount'])){ ?>
                                <label for="sizes_<?= $s ?>_fullPaymentDiscount" class="error">
                                    <?= implode('; ', $this->errors['sizes'][$s]['fullPaymentDiscount']) ?>
                                </label>
                            <?php } ?>
                        </p>

                        <p>
                            <label for="sizes_<?= $s ?>_details" class=""
                                   title="<?= $this->translate('Please enter any details about this share size'); ?>">
                                <?= $this->translate('Details'); ?>:
                            </label>

                        <textarea
                            id="sizes_<?= $s ?>_details"
                            name="sizes[<?= $s ?>][details]"
                            title="<?= $this->translate('Please enter any details about this share size'); ?>"
                            class="large sizes-details"
                            cols="10"
                            rows="10"><?= $this->escape($this->getFormValue('details', 'sizes', $s)); ?></textarea>
                            <?php if(!empty($this->errors['sizes'][$s]['details'])){ ?>
                                <label for="sizes_<?= $s ?>_details" class="error">
                                    <?= implode('; ', $this->errors['sizes'][$s]['details']) ?>
                                </label>
                            <?php } ?>
                        </p>

                        <p style="<?= ($s == 0) ? 'display: none' : '' ?>">
                            <label title="<?= $this->translate('Remove this size for this share'); ?>">
                                <?= $this->translate('Remove'); ?>:
                            </label>

                            <button type="button"
                                    class="ui-button ui-widget ui-corner-all ui-button-icon-only ui-state-default size-remove"
                                    data-id="<?= $s ?>">
                                <span class="ui-button-icon-primary ui-icon ui-icon-minusthick"></span>
                            <span class="ui-button-text">
                                <?= $this->translate('Remove This Size'); ?>
                            </span>
                            </button>
                        </p>
                    </div>
                <?php } ?>
                <p>
                    <label title="<?= $this->translate('Add a new size for this share'); ?>">
                        <?= $this->translate('Add New'); ?>:
                    </label>

                    <button type="button"
                            class="ui-button ui-widget ui-corner-all ui-button-icon-only ui-state-default size-add">
                        <span class="ui-button-icon-primary ui-icon ui-icon-plusthick"></span>
                        <span class="ui-button-text">
                            <?= $this->translate('Add New Size'); ?>
                        </span>
                    </button>
                </p>
            </fieldset>

            <p>
                <button type="submit"
                        class="submit fieldset-align ui-button ui-widget ui-corner-all ui-button-text-only ui-state-default">
                    <span class="ui-button-text">
                        <i class="fa fa-check"></i>
                        <?= $this->translate('Save!'); ?>
                    </span>
                </button>
            </p>
        </form>
    </article>
</section>
