<?php
    $this->headLink()->headLink(
        array(
            'rel' => 'alternate',
            'href' => '/?format=rss',
            'type' => 'application/rss+xml',
            'title' => $this->translate('Planet HarvestHand RSS Feed')
        )
    );
    $this->headLink()->headLink(
        array(
            'rel' => 'alternate',
            'href' => '/?format=atom',
            'type' => 'application/atom+xml',
            'title' => $this->translate('Planet HarvestHand ATOM Feed')
        )
    );
?>
<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!-- Consider adding a manifest.appcache: h5bp.com/d/Offline -->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width">
        <?php echo $this->headTitle() ?>
        <link rel="shortcut icon" href="/_images/favicon.png">
        <link rel="apple-touch-icon" href="/_images/apple-touch-icon.png">
        <link rel="stylesheet" href="/_css/planet.css?v=1">
        <?php echo $this->headStyle() ?>
        <script src="/_js/modernizr.js"></script>
        <?php echo $this->headLink() ?>
    </head>
    <body>
        <!--[if lt IE 7]><p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p><![endif]-->
        <header>
            <h1><?= $this->translate('Planet HarvestHand') ?></h1>
        </header>
        <div role="main">
            <?php echo $this->layout()->content ?>
        </div>
        <footer>
            <ul>
                <li><a href="http://www.<?= Bootstrap::$rootDomain ?>/" title="<?= $this->translate('HarvestHand'); ?>"><span class="icon-social icon-social-harvesthand"></span></a></li>
                <li><a href="mailto:farmnik@harvesthand.com" title="<?= $this->translate('Email'); ?>"><span class="icon-social icon-social-email"></span></a></li>
                <li><a href="http://planet.<?= Bootstrap::$rootDomain ?>/?format=rss" title="<?= $this->translate('RSS'); ?>"><span class="icon-social icon-social-rss"></span></a></li>
                <li><a href="http://www.facebook.com/pages/HarvestHand/143523832349725" title="<?= $this->translate('Facebook'); ?>"><span class="icon-social icon-social-facebook"></span></a></li>
                <li><a href="http://twitter.com/HarvestHand" title="<?= $this->translate('Twitter'); ?>"><span class="icon-social icon-social-twitter"></span></a></li>
                <li><a href="https://github.com/michaelcaplan/HH" title="<?= $this->translate('Github Code Repository'); ?>"><span class="icon-social icon-social-github"></span></a></li>
            </ul>
        </footer>
        <?php
            echo $this->loader()->prepend(
                array(
                    'jquery',
                    'jquery_ui',
                    'hh'
                )
            )->toString(HH_View_Helper_Loader::JS);
        ?>
        <?php echo $this->headScript() ?>
        <?php echo $this->placeholder('foot'); ?>
        <script type="text/javascript">
        document.write(unescape("%3Cscript src='/_stats/piwik.js' type='text/javascript'%3E%3C/script%3E"));
        </script><script type="text/javascript">
        try {
        var piwikTracker = Piwik.getTracker("/_stats/piwik.php", 9);
        piwikTracker.trackPageView();
        piwikTracker.enableLinkTracking();
        } catch( err ) {}
        </script><noscript><p><img src="/_stats/piwik.php?idsite=1" style="border:0" alt="" /></p></noscript>
    </body>
</html>