<nav id="body-subnav" class="grid_3">
    <h3><?= $this->translate('Where To?'); ?></h3>
    <ul>
        <li>
            <a href="/admin/website/pages"
               title="<?= $this->translate('View and edit existing web pages') ?>">
                <?= $this->translate('Pages'); ?>
            </a>
            <ul>
                <li>
                    <a href="/admin/website/pages"
                        title="<?= $this->translate('View and edit existing web pages') ?>">

                        <i class="fa fa-folder"></i>
                        <?= $this->translate('View'); ?>
                    </a>
                </li>
                <li>
                    <a href="/admin/website/page"
                       title="<?= $this->translate('Add new web page') ?>">
                        
                        <i class="fa fa-plus"></i>
                        <?= $this->translate('New'); ?>
                    </a>
                </li>
            </ul>
        </li>
        <li>
            <a href="/admin/website/blog"
               title="<?= $this->translate('View and edit existing blog entries') ?>">
                <?= $this->translate('Blog'); ?>
            </a>
            <ul>
                <li>
                    <a href="/admin/website/blog"
                       title="<?= $this->translate('View and edit existing blog entries') ?>">
                        
                        <i class="fa fa-folder"></i>
                        <?= $this->translate('View'); ?>
                    </a>
                </li>
                <li>
                    <a href="/admin/website/post"
                       title="<?= $this->translate('Add new blog entry') ?>">
                        
                        <i class="fa fa-plus"></i>
                        <?= $this->translate('New'); ?>
                    </a>
                </li>
            </ul>
        </li>
        <li>
            <a href="/admin/website/links"
               title="<?= $this->translate('View and edit existing links to related web sites') ?>">
                <?= $this->translate('Links'); ?>
            </a>
            <ul>
                <li>
                    <a href="/admin/website/links"
                       title="<?= $this->translate('View and edit existing links to related web sites') ?>">
                        
                        <i class="fa fa-folder"></i>
                        <?= $this->translate('View'); ?>
                    </a>
                </li>
                <li>
                    <a href="/admin/website/link"
                       title="<?= $this->translate('Add new link') ?>">
                        
                        <i class="fa fa-plus"></i>
                        <?= $this->translate('New'); ?>
                    </a>
                </li>
            </ul>
        </li>
        <li>
            <a href="/admin/website/stats"
               title="<?= $this->translate('View your web site usage statistics') ?>">
                <?= $this->translate('Statistics'); ?>
            </a>
            <ul>
                <li>
                    <a href="/admin/website/stats"
                       title="<?= $this->translate('View your web site visits summary') ?>">
                        
                        <i class="fa fa-calendar"></i>
                        <?= $this->translate('Summary'); ?>
                    </a>
                </li>
                <li>
                    <a href="/admin/website/stats?report=countries"
                       title="<?= $this->translate('View your web site visitors by country') ?>">
                        
                        <i class="fa fa-calendar"></i>
                        <?= $this->translate('Countries'); ?>
                    </a>
                </li>
                <li>
                    <a href="/admin/website/stats?report=live"
                       title="<?= $this->translate('View your web site visitors in real time') ?>">
                        
                        <i class="fa fa-calendar"></i>
                        <?= $this->translate('Real Time'); ?>
                    </a>
                </li>
                <li>
                    <a href="/admin/website/stats?report=pages"
                       title="<?= $this->translate('View your web site page requests') ?>">
                        
                        <i class="fa fa-calendar"></i>
                        <?= $this->translate('Pages'); ?>
                    </a>
                </li>
                <li>
                    <a href="/admin/website/stats?report=inlinks"
                       title="<?= $this->translate('View your web site inbound followed links') ?>">
                        
                        <i class="fa fa-calendar"></i>
                        <?= $this->translate('Inbound Links'); ?>
                    </a>
                </li>
                <li>
                    <a href="/admin/website/stats?report=outlinks"
                       title="<?= $this->translate('View your web site outbound followed links') ?>">
                        
                        <i class="fa fa-calendar"></i>
                        <?= $this->translate('Outbound Links'); ?>
                    </a>
                </li>
                <li>
                    <a href="/admin/website/stats?report=keywords"
                       title="<?= $this->translate('View your web site search keywords') ?>">
                        
                        <i class="fa fa-calendar"></i>
                        <?= $this->translate('Keywords'); ?>
                    </a>
                </li>
                <li>
                    <a href="/admin/website/stats?report=seo"
                       title="<?= $this->translate('View your web site search engine rankings') ?>">
                        
                        <i class="fa fa-calendar"></i>
                        <?= $this->translate('SEO'); ?>
                    </a>
                </li>
            </ul>
        </li>
        <!-- <li>
            <a href="/admin/website/recipes"
               title="<?= $this->translate('View and edit existing recipes') ?>">
                <?= $this->translate('Recipes'); ?>
            </a>
            <ul>
                <li>
                    <a href="/admin/website/recipes"
                       title="<?= $this->translate('View and edit existing recipes') ?>">
                        
                        <i class="fa fa-folder"></i>
                        <?= $this->translate('View'); ?>
                    </a>
                </li>
                <li>
                    <a href="/admin/website/recipe"
                       title="<?= $this->translate('New recipe') ?>">
                        
                        <i class="fa fa-plus"></i>
                        <?= $this->translate('New'); ?>
                    </a>
                </li>
            </ul>
        </li> -->
    </ul>
</nav>
