<nav id="body-subnav" class="grid_3">
    <h3><?= $this->translate('Where To?'); ?></h3>
    <ul>
        <li>
            <a href="/admin/customers/customers"
               title="<?= $this->translate('View and edit existing customers') ?>">
                <?= $this->translate('Customers'); ?>
            </a>
            <ul>
                <li>
                    <a href="/admin/customers/customers"
                        title="<?= $this->translate('View and edit existing customers') ?>">
                        
                        <i class="fa fa-folder"></i>
                        <?= $this->translate('View'); ?>
                    </a>
                </li>
                <li>
                    <a href="/admin/customers/customer"
                       title="<?= $this->translate('Add new customer') ?>">
                        
                        <i class="fa fa-plus"></i>
                        <?= $this->translate('New'); ?>
                    </a>
                </li>
            </ul>
        </li>
        <li>
            <a href="/admin/customers/subscriptions"
               title="<?= $this->translate('View and edit customer subscriptions') ?>">
                <?= $this->translate('Subscriptions'); ?>
            </a>
            <ul>
                <li>
                    <a href="/admin/customers/subscriptions"
                        title="<?= $this->translate('View and edit existing customer subscriptions') ?>">
                        
                        <i class="fa fa-folder"></i>
                        <?= $this->translate('View'); ?>
                    </a>
                </li>
                <li>
                    <a href="/admin/customers/subscription"
                       title="<?= $this->translate('Add new customer subscription') ?>">
                        
                        <i class="fa fa-plus"></i>
                        <?= $this->translate('New'); ?>
                    </a>
                </li>
            </ul>
        </li>
        <li>
            <a href="/admin/customers/addons"
               title="<?= $this->translate('View and edit customer products purchased') ?>">
                <?= $this->translate('Products'); ?>
            </a>
            <ul>
                <li>
                    <a href="/admin/customers/addons"
                        title="<?= $this->translate('View and edit existing customer products purchased') ?>">
                        
                        <i class="fa fa-folder"></i>
                        <?= $this->translate('View'); ?>
                    </a>
                </li>
                <li>
                    <a href="/admin/customers/addon"
                       title="<?= $this->translate('Add new customer purchased product') ?>">
                        
                        <i class="fa fa-plus"></i>
                        <?= $this->translate('New'); ?>
                    </a>
                </li>
            </ul>
        </li>
        <li>
            <a href="/admin/customers/invoices"
               title="<?= $this->translate('View and edit customer invoices') ?>">
                <?= $this->translate('Invoices'); ?>
            </a>
            <ul>
                <li>
                    <a href="/admin/customers/invoices"
                        title="<?= $this->translate('View and edit existing customer invoices') ?>">
                        
                        <i class="fa fa-folder"></i>
                        <?= $this->translate('View'); ?>
                    </a>
                </li>
            </ul>
        </li>
        <li>
            <a href="/admin/customers/transactions"
               title="<?= $this->translate('View and edit customer payments') ?>">
                <?= $this->translate('Payments'); ?>
            </a>
            <ul>
                <li>
                    <a href="/admin/customers/transactions"
                        title="<?= $this->translate('View and edit customer payments') ?>">
                        
                        <i class="fa fa-folder"></i>
                        <?= $this->translate('View'); ?>
                    </a>
                </li>
            </ul>
        </li>
    </ul>
</nav>
