<?php $this->headTitle($this->translate('Website')); ?>

<?php
    $piwikId = $this->farm->getPreferences()->get('piwikId', 'website', false);

    $statsParams = array(
        'module' => 'Widgetize',
        'action' => 'iframe',
        'moduleToWidgetize' => 'VisitsSummary',
        'actionToWidgetize' => 'index',
        'idSite' => $piwikId,
        'period' => 'day',
        'date' => Zend_Date::now()->get('yyyy-MM-dd'),
        'disableLink' => 1,
        'token_auth' => Bootstrap::getZendConfig()->resources->website->piwik->tokenAuth
    );
?>

<h2>
    <span class="icon-menu icon-menu-website" style="float: left; margin: -10px 7px 0 0;"></span>
    <?= $this->translate('Website'); ?>
</h2>

<section class="container_12">
    <article class="grid_9">
        <?php if (!empty($piwikId)) { ?>
        <div class="ui-widget-content ui-corner-all" style="padding: 0.4em; position: relative;">
            <h3 class="ui-widget-header ui-corner-all" style="margin: 0 0 0.8em 0; padding: 0.4em; text-align: center;">
                <?= $this->translate('Website Visitor Report') ?>
            </h3>
            <div id="widgetIframe">
                <iframe width="100%" height="600" src="/_stats/index.php?<?= http_build_query($statsParams) ?>" scrolling="no" frameborder="0" marginheight="0" marginwidth="0"></iframe>
            </div>
        </div>
        <?php } ?>
    </article>

    <?= $this->render('admin-sub-nav.phtml'); ?>
</section>