<?php
    $this->headTitle($this->translate('Links'));
    
    $this->loader()->append('jquery_dataTables')
        ->append('jquery_dropdown');
?>

<?php $this->placeholder('foot')->captureStart() ?>
<script type="text/javascript">
    $(document).ready(function(){

        $.fn.dataTableExt.aoFeatures.push({
            "fnInit": function(oSettings) {
                return $('<ul class="dataTables_add dropdown-container"><li class="dropdown btn-group">' +
                    '<a href="/admin/website/link" title="<?= $this->translate('Add link') ?>" class="btn">' +
                    '<?= addslashes($this->translate('Add')) ?></a></li></ul>')[0];
            },
            "cFeature": "a",
            "sFeature": "Add"
        });
        
        var table = $("#links").dataTable({
            "bJQueryUI": true,
            "bAutoWidth": false,
            "bDeferRender": true,
            "bLengthChange": false,
            "bProcessing": true,
            "iDisplayLength": 50,
            "iDeferLoading": <?= $this->foundRows ?>,
            "aaSorting": [[1, "asc"]],
            "aoColumns": [ 
                {
                    "sType": "html",
                    "mDataProp": "name",
                    "fnRender": function (oObj) {
                        if (!oObj.aData.hasOwnProperty("id")) {
                            return oObj.aData.name;
                        } else {
                            return '<a href="/admin/website/link?id=' + 
                                parseInt(oObj.aData.id) + '" title="' + oObj.aData.description
                                    .replace(/&/g,'&amp;')
                                    .replace(/</g,'&lt;')
                                    .replace(/>/g,'&gt;')
                                    .replace(/"/g, '&quot;') + '">' + oObj.aData.name
                                    .replace(/&/g,'&amp;')
                                    .replace(/</g,'&lt;')
                                    .replace(/>/g,'&gt;') + '</a>';
                        }
                    }
                },
                {
                    "sType": "html",
                    "mDataProp": "url",
                    "fnRender": function (oObj) {
                        if (!oObj.aData.hasOwnProperty("id")) {
                            return oObj.aData.url;
                        } else {
                            return '<a href="' + oObj.aData.url
                                    .replace(/&/g,'&amp;')
                                    .replace(/</g,'&lt;')
                                    .replace(/>/g,'&gt;') + '" title="' + oObj.aData.description
                                    .replace(/&/g,'&amp;')
                                    .replace(/</g,'&lt;')
                                    .replace(/>/g,'&gt;')
                                    .replace(/"/g, '&quot;') + '" target="_blank">' + oObj.aData.url
                                    .replace(/&/g,'&amp;')
                                    .replace(/</g,'&lt;')
                                    .replace(/>/g,'&gt;') + '</a>';
                        }
                    }
                },
                { 
                    "bSortable": false,
                    "bSearchable": false,
                    "mDataProp": "_actions",
                    "sClass": "right",
                    "fnRender": function (oObj) {
                        if (!oObj.aData.hasOwnProperty("id")) {
                            return oObj.aData._actions;
                        }
                        return '<ul class="dropdown-container">' +
                            '<li class="dropdown btn-group">' +
                            '<a href="/admin/website/link?id=' + parseInt(oObj.aData.id) + '"' +
                            ' title="<?= $this->translate('Edit link') ?>" class="btn">' +
                            '<?= addslashes($this->translate('Edit')) ?></a>' + 
                            '<button type="button" class="btn dropdown-toggle" data-toggle="dropdown">' +
                            '<span class="caret"></span></button><ul class="dropdown-menu">' +
                            '<li class="divider"></li>' +
                            '<li><a class="delete" title="<?= addslashes($this->translate('Delete link')) ?>" ' +
                            ' href="/admin/website/link?a=delete&id=' + parseInt(oObj.aData.id) + '"><?= addslashes($this->translate('Delete')) ?></a></li>' +                        
                            '</ul></li></ul>';
                    }
                }
            ],
            "bSortClasses": false,
            "sAjaxSource": "<?= addslashes($this->Url()) ?>",
            "bServerSide": true,
            "sDom": '<"H"af<"clear">r<"right"ip>>t<"F"<"right"ip>>'
        })
        .delegate("tbody tr", "mouseover mouseout", function(e) {
            if (e.type == "mouseover") {
                $(e.currentTarget).addClass('hover');
            } else {
                $(e.currentTarget).removeClass('hover');
            }
        })
        .delegate(".delete", "click", function(){
            return window.confirm("<?= $this->translate('Are you sure you want to delete this link?  No turning back after a link delete.'); ?>");
        })
        .fnSetFilteringDelay(1000);
        
        new FixedHeader(table);
        
        $('.dropdown-toggle').dropdown();
    });
</script>
<?php $this->placeholder('foot')->captureEnd() ?>

<h2>
    <span class="icon-menu icon-menu-website" style="float: left; margin: -10px 7px 0 0;"></span>
    <?= $this->translate('Links') ?>
</h2>

<section class="container_12">
    <article class="grid_9">

        <?php if (!empty($this->messages)) { ?>
            <section class="info ui-widget ui-state-highlight ui-corner-all">
                <div>
                    <i class="fa fa-info-circle"></i>
                    <strong><?= $this->translate('Hey!'); ?></strong>
                    <?= $this->escape(implode('; ', $this->messages)); ?>
                </div>
            </section>
        <?php } ?>

        <?php if (count($this->links)) { ?>

            <table id="links" class="display">
                <thead>
                    <tr>
                        <th 
                            width="40%"
                            title="<?= $this->translate('Link Name') ?>">
                                <?= $this->translate('Name'); ?>
                        </th>
                        <th 
                            width="45%"
                            title="<?= $this->translate('Link Domain') ?>">
                                <?= $this->translate('Link') ?>
                        </th>
                        <th 
                            width="15%"
                            title="<?= $this->translate('Link Actions') ?>">
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->links as $link) { ?>
                        <tr>
                            <td>
                                <a href="/admin/website/link?id=<?= (int) $link->id ?>"
                                   title="<?= $this->escape($link->description) ?>">
                                    <?= $this->escape($link->name); ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?= $link->url ?>" 
                                   title="<?= $this->escape($link->description) ?>"
                                   target="_blank">
                                    <?= 
                                        $this->escape(parse_url($link->url, PHP_URL_HOST)); 
                                    ?>
                                </a>
                            </td>
                            <td class="right">
                                <ul class="dropdown-container">
                                    <li class="dropdown btn-group">
                                        <a href="/admin/website/link?id=<?= (int) $link->id ?>"
                                           title="<?= $this->translate('Edit link') ?>"
                                           class="btn">
                                            <?= $this->translate('Edit') ?>
                                        </a>
                                        <button type="button"
                                                class="btn dropdown-toggle"
                                                data-toggle="dropdown">
                                            <span class="caret"></span>
                                        </button>

                                        <ul class="dropdown-menu">
                                            <li class="divider"></li>
                                            <li><a class="delete" 
                                                   title="<?= $this->translate('Delete link') ?>"
                                                   href="/admin/website/link?a=delete&id=<?= (int) $link->id ?>"><?= $this->translate('Delete') ?></a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </td>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>

        <?php } else { ?>

            <p><?=
                $this->translate(
                    'You haven\'t added any links.  <a href="%s">Let\'s add one now.</a>',
                    '/admin/website/link'
                ); ?></p>

        <?php } ?>
    </article>

    <?= $this->render('admin-sub-nav.phtml'); ?>
</section>
