<?php
    $this->headTitle($this->translate('Website Pages'));
    
    $this->loader()->append('jquery_dataTables')
        ->append('jquery_dropdown');
?>

<?php $this->placeholder('foot')->captureStart() ?>
<script type="text/javascript">
    $(document).ready(function(){

        $.fn.dataTableExt.aoFeatures.push({
            "fnInit": function(oSettings) {
                return $('<ul class="dataTables_add dropdown-container"><li class="dropdown btn-group">' +
                    '<a href="/admin/website/page" title="<?= $this->translate('Add page') ?>" class="btn">' +
                    '<?= addslashes($this->translate('Add')) ?></a></li></ul>')[0];
            },
            "cFeature": "a",
            "sFeature": "Add"
        });
        
        var table = $("#pages").dataTable({
            "bJQueryUI": true,
            "bAutoWidth": false,
            "bDeferRender": true,
            "bLengthChange": false,
            "bProcessing": true,
            "iDisplayLength": 50,
            "iDeferLoading": <?= $this->foundRows ?>,
            "aaSorting": [[1, "asc"]],
            "aoColumns": [ 
                {
                    "sType": "html",
                    "mDataProp": "title",
                    "fnRender": function (oObj) {
                        if (!oObj.aData.hasOwnProperty("id")) {
                            return oObj.aData.title;
                        } else {
                            return '<a href="/admin/website/page?id=' + 
                                parseInt(oObj.aData.id) + '">' + oObj.aData.title
                                    .replace(/&/g,'&amp;')
                                    .replace(/</g,'&lt;')
                                    .replace(/>/g,'&gt;') + '</a>';
                        }
                    }
                },
                {
                    "sType": "text",
                    "mDataProp": "parent",
                    "fnRender": function (oObj) {
                        if (!oObj.aData.hasOwnProperty("id")) {
                            return oObj.aData.parent;
                        } else {
                            return oObj.aData.placement.replace(/&/g,'&amp;')
                                    .replace(/</g,'&lt;')
                                    .replace(/>/g,'&gt;');
                        }
                    }
                },
                {
                    "sType": "text",
                    "mDataProp": "publish",
                    "fnRender": function (oObj) {
                        return oObj.aData.publish.toLowerCase().replace(/&/g,'&amp;')
                                .replace(/</g,'&lt;')
                                .replace(/>/g,'&gt;');
                    }
                },
                { 
                    "bSortable": false,
                    "bSearchable": false,
                    "mDataProp": "_actions",
                    "sClass": "right",
                    "fnRender": function (oObj) {
                        if (!oObj.aData.hasOwnProperty("id")) {
                            return oObj.aData._actions;
                        }
                        
                        var menu = '<ul class="dropdown-container">' +
                            '<li class="dropdown btn-group">' +
                            '<a href="/admin/website/page?id=' + parseInt(oObj.aData.id) + '"' +
                            ' title="<?= $this->translate('Edit page') ?>" class="btn">' +
                            '<?= addslashes($this->translate('Edit')) ?></a>' + 
                            '<button type="button" class="btn dropdown-toggle" data-toggle="dropdown">' +
                            '<span class="caret"></span></button><ul class="dropdown-menu">';
                        
                        if (!(oObj.aData.parent == '<?= addslashes($this->translate('Home Page')) ?>' && oObj.aData.sort == 0)) {
                            menu += '<li class="divider"></li>' +
                                '<li><a class="delete" title="<?= addslashes($this->translate('Delete page')) ?>" ' +
                                ' href="/admin/website/page?a=delete&id=' + parseInt(oObj.aData.id) + '"><?= addslashes($this->translate('Delete')) ?></a></li>';
                        }
                        
                        menu += '</ul></li></ul>';

                        return menu;
                    }
                }
            ],
            "bSortClasses": false,
            "sAjaxSource": "<?= addslashes($this->Url()) ?>",
            "bServerSide": true,
            "sDom": '<"H"af<"clear">r<"right"ip>>t<"F"<"right"ip>>'
        })
        .delegate("tbody tr", "mouseover mouseout", function(e) {
            if (e.type == "mouseover") {
                $(e.currentTarget).addClass('hover');
            } else {
                $(e.currentTarget).removeClass('hover');
            }
        })
        .delegate(".delete", "click", function(){
            return window.confirm("<?= $this->translate('Are you sure you want to delete this page?  No turning back after a page delete.'); ?>");
        });
        
        new FixedHeader(table);
        
        $('.dropdown-toggle').dropdown();
    });
</script>
<?php $this->placeholder('foot')->captureEnd() ?>

<h2>
    <span class="icon-menu icon-menu-website" style="float: left; margin: -10px 7px 0 0;"></span>
    <?= $this->translate('Website Pages') ?>
</h2>

<section class="container_12">
    <article class="grid_9">

        <?php if (!empty($this->messages)) { ?>
            <section class="info ui-widget ui-state-highlight ui-corner-all">
                <div>
                    <i class="fa fa-info-circle"></i>
                    <strong><?= $this->translate('Hey!'); ?></strong>
                    <?= $this->escape(implode('; ', $this->messages)); ?>
                </div>
            </section>
        <?php } ?>

        <?php if (count($this->pages)) { ?>

            <table id="pages" class="display">
                <thead>
                    <tr>
                        <th 
                            width="40%"
                            title="<?= $this->translate('Page Title') ?>">
                                <?= $this->translate('Title'); ?>
                        </th>
                        <th 
                            width="30%"
                            title="<?= $this->translate('Page Placement') ?>">
                                <?= $this->translate('Placement') ?>
                        </th>
                        <th 
                            width="15%"
                            title="<?= $this->translate('Page Status') ?>">
                                <?= $this->translate('Status') ?>
                        </th>
                        <th 
                            width="15%"
                            title="<?= $this->translate('Page Actions') ?>">
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->pages as $page) { ?>
                        <tr>
                            <td>
                                <a href="/admin/website/page?id=<?= (int) $page->id ?>">
                                    <?= $this->escape($page->title); ?>
                                </a>
                            </td>
                            <td>
                                <?php
                                    if ($page->parent === null && $page->sort == 0) {
                                        echo $this->translate('Home Page');
                                    } else if ($page->parent === null) {
                                        echo $this->translate('Top');
                                    } else {
                                        $parent = $this->pages->getParent($page);

                                        if ($parent === false) {
                                            echo $this->translate('Orphaned');
                                        } else {
                                            echo $this->escape(
                                                $this->translate(
                                                    'Under "%s"',
                                                    $parent->title
                                                )
                                            );
                                        }
                                    }
                                ?>
                            </td>
                            <td>
                                <?php
                                    if ($page->publish == 'DRAFT') {
                                        echo $this->translate('draft');
                                    } else if ($page->publish == 'PUBLISHED') {
                                        echo $this->translate('published');
                                    }
                                ?>
                            </td>
                            <td class="right">
                                <ul class="dropdown-container">
                                    <li class="dropdown btn-group">
                                        <a href="/admin/website/page?id=<?= (int) $page->id ?>"
                                           title="<?= $this->translate('Edit page') ?>"
                                           class="btn">
                                            <?= $this->translate('Edit') ?>
                                        </a>
                                        <button type="button"
                                                class="btn dropdown-toggle"
                                                data-toggle="dropdown">
                                            <span class="caret"></span>
                                        </button>

                                        <ul class="dropdown-menu">
                                            <?php if (!($page->parent === null && $page->sort == 0)) { ?>
                                            <li class="divider"></li>
                                            <li><a class="delete" 
                                                   title="<?= $this->translate('Delete page') ?>"
                                                   href="/admin/website/page?a=delete&id=<?= (int) $page->id ?>"><?= $this->translate('Delete') ?></a></li>
                                            <?php } ?>
                                        </ul>
                                    </li>
                                </ul>
                            </td>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>

        <?php } else { ?>

            <p><?=
                $this->translate(
                    'You haven\'t added a web page yet.  <a href="%s">Let\'s add one now.</a>',
                    '/admin/website/page'
                ); ?></p>

        <?php } ?>
    </article>

    <?= $this->render('admin-sub-nav.phtml'); ?>
</section>
