<?php
    $this->headTitle($this->translate('About HarvestHand'));
?>

<h2><?= $this->translate('About HarvestHand'); ?></h2>

<img src="/_images/logo_big.png" 
     align="right" 
     width="224" 
     height="390" 
     style="border: 1px solid #011205; padding: 20px; margin: 20px; background-color: #ffffff; -moz-border-radius: 4px; -webkit-border-radius: 4px; border-radius: 4px;">

<h3>HarvestHand begins...</h3>

<p>
    ...after relocating our family to the beautiful <a href="http://en.wikipedia.org/wiki/Annapolis_Valley" target="_blank">Annapolis Valley, Nova Scotia</a>, and joining the <a href="http://www.taprootfarms.ca/" target="_blank">Taproot Farms CSA run by Patricia and Josh</a>.
    Taproot is an exciting place, and Patricia and Josh are innovative young farmers.  
    They have a keen sense of <strong>community</strong>, a strong <strong>business sense</strong>, and a knack for <strong>growing excellent food</strong>.
    Stir in a city slicker relocated from Montreal who enjoys developing web applications for organizations both large and small and HarvestHand was born.
</p>

<h3>HarvestHand's goals are simple.</h3>

<p>
    We wish to see a total transformation of the dominant food production, distribution, and consumption system.
    Food needs to be <strong>fair</strong>, <strong>sustainable</strong>, <strong>healthy</strong>, and <strong>delicious</strong>.
    Food need to be an extention of <strong>a humanly scaled value system</strong>.
    We believe Community Supported Agriculture programs are an important tool for doing just that.
    HarvestHand aims to provide web-based software solutions that will facilitate the running of <strong>CSA farms</strong>, <strong>fisheries</strong>, and <strong>kitchens</strong> so that communities and food producers can be more successful at <strong>building the new food systems we need today</strong>.
</p>

<h3>HarvestHand is not a software product.</h3>

<p>
    It is more than that.  
    We are a medley of <strong>farmers</strong>, <strong>techies</strong>, and <strong>foodies</strong> who are committed to working with the CSA community to continously innovate solutions that will <strong>empower and transform CSA practices</strong>.
</p>

<h3>Who are we?</h3>

<div style="width: 100%">

    <figure style="width: 20%; float: left;">
        <img src="/_images/mike.jpg" alt="Mike Caplan" width="200" height="250" style=" border: 1px solid #011205; padding: 20px; background-color: #ffffff; -moz-border-radius: 4px; -webkit-border-radius: 4px; border-radius: 4px;" />
        <figcaption>
          <strong>My name is Mike</strong>
          <br />
            I've been a member of a few CSAs in both Quebec and Nova Scotia.  
            In Quebec, I founded a project that worked to connect the dots between grassroots social services and CSA farms.
            Professionally, I design and write web-based software.  Its a passion.  I've been doing this for over a decade.
        </figcaption>
    </figure>

    <figure style="width: 20%; float: left;">
        <img src="/_images/caplans.jpg" alt="The Caplans" width="200" height="250" style=" border: 1px solid #011205; padding: 20px; background-color: #ffffff; -moz-border-radius: 4px; -webkit-border-radius: 4px; border-radius: 4px;" />
        <figcaption>
          <strong>The Force</strong>
          <br />
            Cheri and our three kids&mdash;Max, Solomon, and Clara&mdash;fill our home located in Kentville.  
            Cheri's a student of Law and copy editor extraordinaire; Max's a student of the imagination; Solomon's a student of fun; and Clara's a student of play.
        </figcaption>
    </figure>

    <figure style="width: 20%; float: left;">
        <img src="/_images/taproot.jpg" width="200" height="250" style=" border: 1px solid #011205; padding: 20px; background-color: #ffffff; -moz-border-radius: 4px; -webkit-border-radius: 4px; border-radius: 4px;" />
        <figcaption>
          <strong>Patricia &amp; Josh</strong>
          <br />
          Josh and Patricia grew up farming, and the commitment to agriculture instilled in them is now being passed to their three children. 
          They run Taproot Farms, a CSA committed to the local food movement by providing fresh, delicious food to your homes.
        </figcaption>
    </figure>
</div>