<h2><?= $this->title ?></h2>

<p><?= $this->translate('You are independently responsible for complying with all applicable laws in all of your actions related to your use of HarvestHand\'s services, regardless of the purpose of the use. In addition, you must adhere to the terms of this Acceptable Use Policy.') ?></p>

<h3><?= $this->translate('Prohibited Activities') ?></h3>

<p><?= $this->translate('You may not use the HarvestHand service for activities that:'); ?></p>

<ul>
    <li><?= $this->translate('Violate any law, statute, ordinance or regulation;') ?></li>
    <li><?= $this->translate('Relate to sales of (a) narcotics, steroids, certain controlled substances or other products that present a risk to consumer safety, (b) drug paraphernalia, (c) items that encourage, promote, facilitate or instruct others to engage in illegal activity, (d) items that promote hate, violence, racial intolerance, or the financial exploitation of a crime, (e) items that are considered obscene, (f) items that infringe or violate any copyright, trademark, right of publicity or privacy or any other proprietary right under the laws of any jurisdiction, (g) certain sexually oriented materials or services, or (h) ammunition, firearms, or certain firearm parts or accessories, or (i) ,certain weapons or knives regulated under applicable law;') ?></li>
    <li><?= $this->translate('Relate to transactions that (a) show the personal information of third parties in violation of applicable law, (b) support pyramid or ponzi schemes, matrix programs, other “get rich quick” schemes or certain multi-level marketing programs, (c) are associated with purchases of real property, annuities or lottery contracts, lay-away systems, off-shore banking or transactions to finance or refinance debts funded by a credit card, (d) are by payment processors to collect payments on behalf of merchants, (e), are associated with the following Money Service Business activities: the sale of traveler’s checks or money orders, currency exchanges or check cashing,or (f) provide certain credit repair or debt settlement services;') ?></li>
    <li><?= $this->translate('Involve the sales of products or services identified by government agencies to have a high likelihood of being fraudulen;') ?></li>
    <li><?= $this->translate('Violate applicable laws or industry regulations regarding the sale of (a) tobacco products, or (b) prescription drugs and devices;') ?></li>
    <li><?= $this->translate('Involve gambling, gaming and/or any other activity with an entry fee and a prize, including, but not limited to casino games, sports betting, horse or greyhound racing, lottery tickets, other ventures that facilitate gambling, games of skill (whether or not it is legally defined as a lottery) and sweepstakes unless the operator has obtained prior approval from HarvestHand and the operator and customers are located exclusively in jurisdictions where such activities are permitted by law.;') ?></li>
</ul>

<h3><?= $this->translate('Violations of the Acceptable Use Policy') ?></h3>

<p><?= $this->translate(
    'We encourage you to report violations of this Acceptable Use Policy to HarvestHand immediately. If you have a question about whether a type of use of HarvestHand may violate the Acceptable Use Policy, you can email HarvestHand at: <a href="mailto:%1$s">%1$s</a>.',
    'farmnik@harvesthand.com'
) ?></p>