<h1><?= $this->escape($this->title) ?></h1>

<h2><?= $this->translate('Summary') ?></h2>

<dl>
    <dt><a href="#use"><?= $this->translate('Acceptable Use Policy') ?></a></dt>
    <dd>
        <ul>
            <li>
                <?= $this->translate('You can’t use HH for "gross," evil, or illegal things') ?>
            </li>
        </ul>
    </dd>

    <dt><a href="#privacy"><?= $this->translate('Privacy Policy') ?></a></dt>
    <dd>
        <ul>
            <li>
                <?= $this->translate('Where HH collects personal information, it will only be used in expected ways (IE: to make your experience with HH work).') ?>
            </li>
            <li>
                <?= $this->translate('We won\'t give your personal info away to the highest bidder, or even the lowest.') ?>
            </li>
            <li>
                <?= $this->translate('We take the protection of personal info serious.') ?>
            </li>
            <li>
                <?= $this->translate('We will use non identifying info to understand how HH is being used (or not used).') ?>
            </li>
            <li>
                <?= $this->translate('We will disclose this protected info if legally required.') ?>
            </li>
        </ul>
    </dd>

    <dt><a href="#terms"><?= $this->translate('Terms Of Use') ?></a></dt>
    <dd>
        <ul>
            <li>
                <?= $this->translate('Your content on HH is yours in every way.') ?>
            </li>
            <li>
                <?= $this->translate('HH is the steward of your content.  HH will interact with your content, modify, and even share your content in a means that you expect.') ?>
            </li>
            <li>
                <?= $this->translate('We offer no warranty on how others on the Inet interact with your content.  Further, 3rd party content is just that.') ?>
            </li>
            <li>
                <?= $this->translate('We give you licence to use HH, just be good to the system, and take reasonable steps to play safe.') ?>
            </li>
            <li>
                <?= $this->translate('If the sky falls, there are limits to our liability.') ?>
            </li>
        </ul>
    </dd>
</dl>

<p><?= $this->translate('As HH evolves, we\'ll do our best to let you know about changes to these docs.') ?></p>

<h2><?= $this->translate('Gory Details') ?></h2>

<a id="use"></a>
<h3><?= $this->translate('Acceptable Use Policy') ?></h3>

<p><?= $this->translate('You are responsible for complying with all applicable federal and provincial laws in all of your actions related to your use of HarvestHand\'s services, regardless of the purpose of the use. In addition, you must adhere to the terms of this Acceptable Use Policy.') ?></p>

<h4><?= $this->translate('Prohibited Activities') ?></h4>

<p><?= $this->translate('You may not use the HarvestHand service for activities that:'); ?></p>

<ul>
    <li><?= $this->translate('Violate any law, statute, ordinance or regulation;') ?></li>
    <li><?= $this->translate('Relate to sales of (a) narcotics, steroids, certain controlled substances or other products that present a risk to consumer safety, (b) drug paraphernalia, (c) items that encourage, promote, facilitate or instruct others to engage in illegal activity, (d) items that promote hate, violence, racial intolerance, or the financial exploitation of a crime, (e) items that are considered obscene, (f) items that infringe or violate any copyright, trademark, right of publicity or privacy or any other proprietary right under the laws of any jurisdiction, (g) certain sexually oriented materials or services, or (h) ammunition, firearms, or certain firearm parts or accessories, or (i) ,certain weapons or knives regulated under applicable law;') ?></li>
    <li><?= $this->translate('Relate to transactions that (a) show the personal information of third parties in violation of applicable law, (b) support pyramid or ponzi schemes, matrix programs, other “get rich quick” schemes or certain multi-level marketing programs, (c) are associated with purchases of real property, annuities or lottery contracts, lay-away systems, off-shore banking or transactions to finance or refinance debts funded by a credit card, (d) are by payment processors to collect payments on behalf of merchants, (e), are associated with the following Money Service Business activities: the sale of traveler’s checks or money orders, currency exchanges or check cashing,or (f) provide certain credit repair or debt settlement services;') ?></li>
    <li><?= $this->translate('Involve the sales of products or services identified by government agencies to have a high likelihood of being fraudulen;') ?></li>
    <li><?= $this->translate('Violate applicable laws or industry regulations regarding the sale of (a) tobacco products, or (b) prescription drugs and devices;') ?></li>
    <li><?= $this->translate('Involve gambling, gaming and/or any other activity with an entry fee and a prize, including, but not limited to casino games, sports betting, horse or greyhound racing, lottery tickets, other ventures that facilitate gambling, games of skill (whether or not it is legally defined as a lottery) and sweepstakes unless the operator has obtained prior approval from HarvestHand and the operator and customers are located exclusively in jurisdictions where such activities are permitted by law.;') ?></li>
</ul>

<h4><?= $this->translate('Violations of the Acceptable Use Policy') ?></h4>

<p><?= $this->translate(
        'We encourage you to report violations of this Acceptable Use Policy to HarvestHand immediately. If you have a question about whether a type of use of HarvestHand may violate the Acceptable Use Policy, you can email HarvestHand at: <a href="mailto:%1$s">%1$s</a>.',
        'team@harvesthand.com'
    ) ?></p>


<a id="privacy"></a>
<h3><?= $this->translate('Privacy Policy') ?></h3>

<p><?= $this->translate('HarvestHand.com is owned and operated by HarvestHand New Media Communities (“HarvestHand,” “we,” or “us”). HarvestHand provides software to manage Community Shared Agriculture (CSA) farm member management, ecommerce, and marketing. HarvestHand also provides an online community space for people to share and connect around values-based approaches to food production, distribution, consumption, and community. Our Privacy Policy explains how we collect, use, disclose, and protect information that applies to our Service, and your choices about the collection and use of your information. Capitalized terms that are not defined in this Privacy Policy have the meaning given them in our Terms of Use.') ?></p>

<h4><?= $this->translate('How We Collect and Use Information') ?></h4>

<dl>
    <dt><?= $this->translate('Personally Identifiable Information') ?></dt>
    <dd><?= $this->translate('We collect information that can be used to identify you as an individual (“Personally Identifiable Information”) only when you provide such information directly to us in connection with the Service.') ?></dd>

    <dt><?= $this->translate('Types of Personally Identifiable Information you provide us directly') ?></dt>
    <dd><?= $this->translate('You aren\'t required to provide us with any Personally Identifiable Information in order to visit and browse HarvestHand.com If you choose to sign up for a User account, we may collect certain Personally Identifiable Information, including your username, first and last name, phone number, and e-mail address. If you sign up for our e-mail newsletter, we will collect your e-mail address. If you elect to make a donation or purchase merchandise through the Service, you may also provide us or a trusted third party provider with the financial information required to process and fulfill your transaction. ') ?></dd>
</dl>

<h4><?= $this->translate('Sharing of Your Information') ?></h4>

<p><?= $this->translate('We will not sell, trade, or otherwise transfer your personally identifiable information to parties outside of HarvestHand without your consent, except as noted below') ?></p>

<dl>
    <dt><?= $this->translate('Who you may choose to share your User Content with') ?></dt>
    <dd><?= $this->translate('If you elect to post something in a public area of our Service (for example, by commenting on a post), any Personally Identifiable Information or content that you voluntarily disclose for posting to the Service, such as User Content, becomes available to the public, as controlled by any applicable privacy settings. If you remove information that you posted to the Service, copies may remain viewable in cached and archived pages of the Service, or if other Users have copied or saved that information.') ?></dd>

    <dt><?= $this->translate('Instances where we are required to share your Personally Identifiable Information') ?></dt>
    <dd><?= $this->translate('HarvestHand will disclose Personally Identifiable Information where required to do so by law or subpoena.') ?></dd>

    <dt><?= $this->translate('Non-Personally Identifiable Information') ?></dt>
    <dd><?= $this->translate('We may share Non-Personally Identifiable Information, including information obtained through tools such as cookies, log files, device identifiers, location data and clear gifs (such as anonymous usage data, referring/exit pages and URLs, platform types, number of clicks, etc.): (i) in any manner permitted for Personally Identifiable Information; and (ii) with our third-party business partners for the purposes described in the section above on “How We Collect and Use Information.” We may also aggregate or otherwise strip data of all personally identifying characteristics and may share that aggregated, anonymized data with third parties.') ?></dd>
</dl>

<h4><?= $this->translate('How We Store and Protect Your Information') ?></h4>

<dl>
    <dt><?= $this->translate('Compromise of information') ?></dt>
    <dd><?= $this->translate('In the event that any information under our control is compromised as a result of a breach of security, HarvestHand will take reasonable steps to investigate the situation and where appropriate, notify those individuals whose information may have been compromised and take other steps, in accordance with any applicable laws and regulations.') ?></dd>
</dl>

<h4><?= $this->translate('Your Choices About Your Information') ?></h4>

<dl>
    <dt><?= $this->translate('Opting out of collection of Personally Identifiable Information') ?></dt>
    <dd><?= $this->translate('You may, of course, decline to submit any Personally Identifiable Information through the Service, in which case HarvestHand may not be able to provide certain services to you.') ?></dd>

    <dt><?= $this->translate('Opting out of collection of Non-Personally Identifiable Information') ?></dt>
    <dd><?= $this->translate('Please refer to your mobile device or browser’s technical information for instructions on how to delete and disable cookies, and other tracking/recording tools. Note that disabling cookies on your mobile device or browser prevents HarvestHand or its business partners from tracking your browser’s activities in relation to using HarvestHand. However, doing so may disable many of the features available through the Service.') ?></dd>
</dl>

<h4><?= $this->translate('Children\'s Privacy') ?></h4>

<p>
    <?= $this->translate('HarvestHand does not knowingly collect personal information from children under the age of 13. If we learn we have collected personal information on a child under the age of 13 without proper consent, we will delete that data from our systems. If you believe that we might have any information from or about a child under 13, please contact us at team@harvesthand.com') ?>
</p>

<h4><?= $this->translate('Other Web Sites and Services') ?></h4>

<p>
    <?= $this->translate('We are not responsible for the practices employed by websites or services linked to or from the Service, including the information or content contained therein. Please remember that when you use a link to go from the Service to another website, our Privacy Policy does not apply to third-party websites or services. Your browsing and interaction on any third-party website or service, including those that have a link on our website, are subject to that third party’s own rules and policies. In addition, you agree that we are not responsible and we do not control over any third-parties that you authorize to access your User Content. If you are using a third-party website or service (like Facebook) and you allow such a third-party access to your User Content you do so at your own risk. This Privacy Policy does not apply to information we collect by other means (including offline) or from other sources other than through the Service.') ?>
</p>

<h4><?= $this->translate('Changes to Our Privacy Policy') ?></h4>

<p>
    <?= $this->translate('HarvestHand may, in its sole discretion, modify or update this Privacy Policy from time to time, and so you should review this page periodically. When we change the policy in a material manner we will update the ’last modified’ date at the bottom of this page.') ?>
</p>

<a id="terms"></a>
<h3><?= $this->translate('Terms Of Use') ?></h3>

<p>
    <?= $this->translate('HarvestHand.com is owned and operated by HarvestHand New Media Communities (“HarvestHand,” “we,” or “us”). HarvestHand provides software to manage Community Shared Agriculture (CSA) farm member management, e-commerce, and marketing. HarvestHand also provides an online community space for people to share and connect around values-based approaches to food production, distribution, consumption, and community.') ?>
</p>

<p>
    <?= $this->translate('These terms of use (this “Agreement”) govern your access to and use of our our mobile services, web site, and any software provided on or in connection with the HarvestHand service (collectively the “Service”), so please read the Agreement carefully before using the Service.') ?>
</p>

<p>
    <?= $this->translate('By accessing or using the Service, you agree to be bound by this Agreement and by our Privacy Policy, whether or not you are a registered user of our Service. This Agreement applies to all visitors, users, and others who access the Service (“Users”).') ?>
</p>

<h4><?= $this->translate('Sharing Your Content') ?></h4>

<dl>
    <dt><?= $this->translate('Your content') ?></dt>
    <dd><?= $this->translate('HarvestHand may now or in the future allow you to post content on the Service, including comments, photos, videos, and other materials. Any content a User submits, posts, displays, or otherwise makes available on the Service, including all Intellectual Property Rights (defined below) therein, is referred to as “User Content.” You retain ownership of your User Content.') ?></dd>


    <dt><?= $this->translate('How HarvestHand and other Users can use your content') ?></dt>
    <dd><?= $this->translate('You own all of the User Content you post or publish (“post”) on the Service. Subject to your publish settings, you grant us a non-exclusive, royalty-free, transferable, sub-licensable, worldwide license to use, modify, reproduce, display and distribute your User Content on the Service for the purposes of operating and providing the Service to you and our Users (“User Content License”). Subject to your publish settings, you also hereby grant to HarvestHand and to each User of the Service, a non-exclusive license to access, use, reproduce, distribute and display your User Content as permitted by the functionality of the Service. You understand and agree that HarvestHand Service is a public platform and other Users may search for, see, use, and/or re-post any User Content that you make publicly available through the Service.') ?></dd>


    <dt><?= $this->translate('Your responsibilities') ?></dt>
    <dd>
        <dl>

            <dt><?= $this->translate('HarvestHand Acceptable Use Policy') ?></dt>
            <dd><?= $this->translate('To keep HarvestHand running smoothly for all of our Users, you agree that you will use the Service only in a manner consistent with the HarvestHand Acceptable Use Policy.') ?></dd>

            <dt><?= $this->translate('') ?></dt>
            <dd><?= $this->translate('') ?></dd>
        </dl>
    </dd>


    <dt><?= $this->translate('') ?></dt>
    <dd><?= $this->translate('') ?></dd>


</dl>
