<?php
    if (empty($this->farmer) || $this->farmer->role != HH_Domain_Farmer::ROLE_MEMBER) {
        $title = $this->translate('New Account');
        $new = true;

    } else {
        $title = $this->translate('Edit Account');
        $new = false;
    }

    $this->headTitle($title);

    $this->loader()->append('jquery_validate');
?>

<?php $this->placeholder('foot')->captureStart() ?>
<script type="text/javascript">
    $(document).ready(function(){
        $("#customer").validate({
            rules: {
                "farmer[password]" : {
                    minlength : 4
                },
                "farmer[userName]" : {
                    remote : "/customers/usernameunique"
                },
                "passwordConfirm" : {
                    equalTo : "#farmer_password"
                }
            },
            messages : {
                "farmer[userName]" : {
                    remote : function() {
                        return $.format(
                            "<?= $this->translate('The user name {0} is already in use'); ?>",
                            $("#farmer_userName").val()
                        );
                    }
                },
                "passwordConfirm" : {
                    equalTo : "<?= $this->translate('Your passwords are not the same'); ?>"
                }
            },
            errorContainer: $("#formError")
        });

        $("#city").autocomplete({
            source: function(request, response) {
                $.get("/customers/locale",
                    {
                        country : $("#country").val(),
                        subdivision : $("#state").val(),
                        unlocode: request.term
                    },
                    function(unlocodes) {
                        response(unlocodes);
                    },
                    'json'
                );
            }
        });
    });
</script>
<?php $this->placeholder('foot')->captureEnd() ?>

<h2><?= $title ?></h2>

<form id="customer" action="/customers/customer" method="post" accept-charset="utf-8" class="cmxform large">

    <section id="formError" class="error ui-widget ui-state-error ui-corner-all" style="<?= (!empty($this->errors)) ? '' : 'display:none;' ?>">
        <div>
            z<i class="fa fa-exclamation-triangle"></i>
            <strong><?= $this->translate('Oh No!'); ?></strong>
            <?= $this->translate('Something is not right with what you entered.  Check below for hints on how to fix things up.'); ?>
        </div>
    </section>

    <input id="country" type="hidden" name="country" value="<?= $this->getFormValue('country') ?>" />

    <fieldset>
        <legend><?= $this->translate('Contact Info') ?></legend>

        <p>
            <label for="firstName" class="required" title="<?= $this->translate('Please enter your first name'); ?>">
                <?= $this->translate('First Name'); ?>:
                <abbr title="<?= $this->translate('This field is required'); ?>">*</abbr>
            </label>
            <input
                id="firstName"
                name="firstName"
                type="text"
                title="<?= $this->translate('Please enter your first name'); ?>"
                value="<?= $this->getFormValue('firstName'); ?>"
                class="required large"
                maxlength="100" />

            <?php if (!empty($this->errors['firstName'])) { ?>
            <label for="firstName" class="error">
                <?= implode('; ', $this->errors['firstName']) ?>
            </label>
            <?php } ?>
        </p>

        <p>
            <label for="lastName" class="required" title="<?= $this->translate('Please enter your last name'); ?>">
                <?= $this->translate('Last Name'); ?>:
                <abbr title="<?= $this->translate('This field is required'); ?>">*</abbr>
            </label>
            <input
                id="lastName"
                name="lastName"
                type="text"
                title="<?= $this->translate('Please enter your last name'); ?>"
                value="<?= $this->getFormValue('lastName'); ?>"
                class="required large"
                maxlength="100" />

            <?php if (!empty($this->errors['lastName'])) { ?>
            <label for="lastName" class="error">
                <?= implode('; ', $this->errors['lastName']) ?>
            </label>
            <?php } ?>
        </p>

        <p>
            <label for="address" class="required" title="<?= $this->translate('Please enter your address'); ?>">
                <?= $this->translate('Address'); ?>:
                <abbr title="<?= $this->translate('This field is required'); ?>">*</abbr>
            </label>
            <input
                id="address"
                name="address"
                type="text"
                title="<?= $this->translate('Please enter your address'); ?>"
                value="<?= $this->getFormValue('address'); ?>"
                class="large required"
                maxlength="255" />

            <?php if (!empty($this->errors['address'])) { ?>
            <label for="address" class="error">
                <?= implode('; ', $this->errors['address']) ?>
            </label>
            <?php } ?>
        </p>

        <p>
            <label for="address2" title="<?= $this->translate('Please enter your address'); ?>">
                <?= $this->translate('Address'); ?>:
            </label>
            <input
                id="address2"
                name="address2"
                type="text"
                title="<?= $this->translate('Please enter your address'); ?>"
                value="<?= $this->getFormValue('address2'); ?>"
                class="large"
                maxlength="255" />

            <?php if (!empty($this->errors['address2'])) { ?>
            <label for="address2" class="error">
                <?= implode('; ', $this->errors['address2']) ?>
            </label>
            <?php } ?>
        </p>

        <p>
            <label for="city" class="required" title="<?= $this->translate('Please enter your town or city'); ?>">
                <?= $this->translate('Town'); ?>:
                <abbr title="<?= $this->translate('This field is required'); ?>">*</abbr>
            </label>
            <input
                id="city"
                name="city"
                type="text"
                title="<?= $this->translate('Please enter the your town or city'); ?>"
                value="<?= $this->getFormValue('city'); ?>"
                class="large required"
                maxlength="100" />

            <?php if (!empty($this->errors['city'])) { ?>
            <label for="city" class="error">
                <?= implode('; ', $this->errors['city']) ?>
            </label>
            <?php } ?>
        </p>

        <p>
            <label for="state" class="required" title="<?= $this->translate('Please enter your state'); ?>">
                <?= $this->translate('State'); ?>:
                <abbr title="<?= $this->translate('This field is required'); ?>">*</abbr>
            </label>
            <?php
                $country = $this->getFormValue('country');

                if (!empty($country)) {
                    $country = substr($country, 0, 2);

                    $states = HH_Tools_Countries::getSubdivisions($country);
                }
            ?>
            <?php if (!empty($states)) { ?>
                <?=
                    $this->formSelect(
                        'state',
                        $this->getFormValue('state'),
                        array(
                            'id' => 'state',
                            'class' => 'required',
                            'title' => $this->translate('Please enter your state')
                        ),
                        array('' => '') + $states
                    );
                ?>
            <?php } else { ?>
                <input
                    id="state"
                    name="state"
                    type="text"
                    title="<?= $this->translate('Please enter your state'); ?>"
                    value="<?= $this->getFormValue('state'); ?>"
                    class="required"
                    maxlength="45" />
            <?php } ?>

            <?php if (!empty($this->errors['state'])) { ?>
            <label for="state" class="error">
                <?= implode('; ', $this->errors['state']) ?>
            </label>
            <?php } ?>
        </p>

        <p>
            <label for="zipCode" class="" title="<?= $this->translate('Please enter your zip code'); ?>">
                <?= $this->translate('Zip Code'); ?>:
            </label>
            <input
                id="zipCode"
                name="zipCode"
                type="text"
                title="<?= $this->translate('Please enter your zip code'); ?>"
                value="<?= $this->getFormValue('zipCode'); ?>"
                class=""
                maxlength="45" />

            <?php if (!empty($this->errors['zipCode'])) { ?>
            <label for="zipCode" class="error">
                <?= implode('; ', $this->errors['zipCode']) ?>
            </label>
            <?php } ?>
        </p>

        <p>
            <label for="email" class="required" title="<?= $this->translate('Please enter your email'); ?>">
                <?= $this->translate('Email'); ?>:
                <abbr title="<?= $this->translate('This field is required'); ?>">*</abbr>
            </label>
            <input
                id="email"
                name="email"
                type="text"
                title="<?= $this->translate('Please enter your email'); ?>"
                value="<?= $this->getFormValue('email'); ?>"
                class="email required"
                maxlength="255" />

            <?php if (!empty($this->errors['email'])) { ?>
            <label for="email" class="error">
                <?= implode('; ', $this->errors['email']) ?>
            </label>
            <?php } ?>
        </p>

        <p>
            <label for="telephone" title="<?= $this->translate('Please enter your telephone'); ?>">
                <?= $this->translate('Telephone'); ?>:
            </label>
            <input
                id="telephone"
                name="telephone"
                type="text"
                title="<?= $this->translate('Please enter your telephone'); ?>"
                value="<?= $this->getFormValue('telephone'); ?>"
                class="telephone"
                maxlength="20" />

            <?php if (!empty($this->errors['telephone'])) { ?>
            <label for="telephone" class="error">
                <?= implode('; ', $this->errors['telephone']) ?>
            </label>
            <?php } ?>
        </p>

        <p>
            <label for="fax" title="<?= $this->translate('Please enter your fax'); ?>">
                <?= $this->translate('Fax'); ?>:
            </label>
            <input
                id="fax"
                name="fax"
                type="text"
                title="<?= $this->translate('Please enter your fax'); ?>"
                value="<?= $this->getFormValue('fax'); ?>"
                class="fax"
                maxlength="20" />

            <?php if (!empty($this->errors['fax'])) { ?>
            <label for="fax" class="error">
                <?= implode('; ', $this->errors['fax']) ?>
            </label>
            <?php } ?>
        </p>

    </fieldset>

    <fieldset>
        <legend><?= $this->translate('Login Details') ?></legend>

        <p>
            <label for="farmer_userName" class="required" title="<?= $this->translate('Please enter a user name to log in with'); ?>">
                <?= $this->translate('User Name'); ?>:
                <?php if ($new) { ?>
                <abbr title="<?= $this->translate('This field is required'); ?>">*</abbr>
                <?php } ?>
            </label>
            
            <?php if ($new) { ?>
            
            <input
                id="farmer_userName"
                name="farmer[userName]"
                type="text"
                title="<?= $this->translate('Please enter a user name to log in with'); ?>"
                value="<?= $this->getFormValue('userName', 'farmer'); ?>"
                class="required"
                maxlength="50" />

            <?php } else { ?>
                <span>
                    <?= $this->getFormValue('userName', 'farmer'); ?>
                </span>
            <?php } ?>
            
            <?php if (!empty($this->errors['farmer']['userName'])) { ?>
            <label for="farmer_userName" class="error">
                <?= implode('; ', $this->errors['farmer']['userName']) ?>
            </label>
            <?php } ?>
        </p>

        <p>
            <label for="farmer_password" class="required" title="<?= $this->translate('Please enter a password to log in with'); ?>">
                <?= $this->translate('Password'); ?>:
                <?php if ($new) { ?>
                <abbr title="<?= $this->translate('This field is required'); ?>">*</abbr>
                <?php } ?>
            </label>
            <input
                id="farmer_password"
                name="farmer[password]"
                type="password"
                title="<?= $this->translate('Please enter a password to log in with'); ?>"
                value="<?= $this->getFormValue('password', 'farmer'); ?>"
                class="<?= ($new) ? 'required' : '' ?>"
                maxlength="32"
                autocomplete="off" />

            <?php if (!empty($this->errors['farmer']['password'])) { ?>
            <label for="farmer_password" class="error">
                <?= implode('; ', $this->errors['farmer']['password']) ?>
            </label>
            <?php } ?>
        </p>

        <p>
            <label for="passwordConfirm" class="required" title="<?= $this->translate('Please confirm your password'); ?>">
                <?= $this->translate('Confirm Password'); ?>:
                <?php if ($new) { ?>
                <abbr title="<?= $this->translate('This field is required'); ?>">*</abbr>
                <?php } ?>
            </label>
            <input
                id="passwordConfirm"
                name="passwordConfirm"
                type="password"
                title="<?= $this->translate('Please confirm your password'); ?>"
                value="<?= $this->getFormValue('passwordConfirm'); ?>"
                class="<?= ($new) ? 'required' : ''; ?>"
                maxlength="32"
                autocomplete="off" />
        </p>

    </fieldset>

    <fieldset>
        <legend><?= $this->translate('Secondary Contact') ?></legend>
        <p>
            <label for="secondaryFirstName" title="<?= $this->translate('Please enter a secondary contact first name'); ?>">
                <?= $this->translate('First Name'); ?>:
            </label>
            <input
                id="secondaryFirstName"
                name="secondaryFirstName"
                type="text"
                title="<?= $this->translate('Please enter a secondary contact first name'); ?>"
                value="<?= $this->getFormValue('secondaryFirstName'); ?>"
                class="large"
                maxlength="100" />

            <?php if (!empty($this->errors['secondaryFirstName'])) { ?>
            <label for="secondaryFirstName" class="error">
                <?= implode('; ', $this->errors['secondaryFirstName']) ?>
            </label>
            <?php } ?>
        </p>

        <p>
            <label for="secondaryLastName" title="<?= $this->translate('Please enter a secondary contact last name'); ?>">
                <?= $this->translate('Last Name'); ?>:
            </label>
            <input
                id="secondaryLastName"
                name="secondaryLastName"
                type="text"
                title="<?= $this->translate('Please enter a secondary contact last name'); ?>"
                value="<?= $this->getFormValue('secondaryLastName'); ?>"
                class="large"
                maxlength="100" />

            <?php if (!empty($this->errors['secondaryLastName'])) { ?>
            <label for="secondaryLastName" class="error">
                <?= implode('; ', $this->errors['secondaryLastName']) ?>
            </label>
            <?php } ?>
        </p>

        <p>
            <label for="secondaryEmail" title="<?= $this->translate('Please enter a secondary contact email'); ?>">
                <?= $this->translate('Email'); ?>:
            </label>
            <input
                id="secondaryEmail"
                name="secondaryEmail"
                type="text"
                title="<?= $this->translate('Please enter a secondary contact email'); ?>"
                value="<?= $this->getFormValue('email'); ?>"
                class="email"
                maxlength="255" />

            <?php if (!empty($this->errors['secondaryEmail'])) { ?>
            <label for="secondaryEmail" class="error">
                <?= implode('; ', $this->errors['secondaryEmail']) ?>
            </label>
            <?php } ?>
        </p>
    </fieldset>

    <p>
        <button type="submit" class="submit fieldset-align ui-button ui-widget ui-corner-all ui-button-text-only ui-state-default">
            <span class="ui-button-text">
                <i class="fa fa-check"></i>
                <?= $this->translate('Save!'); ?>
            </span>
        </button>
    </p>
</form>
