
<p>
    <?= $this->translate('Hi there,') ?>
</p>

<p>
    <?= $this->translate(
        'Someone, hopefully you, asked that your password be reset for %s.',
        $this->escape($this->farm->name)
    ) ?>
    
    <?= $this->translate('If you have no knowedge of this, please disregard this email.') ?>
</p>

<p>
    <?= $this->translate('If this is what you wish to do, please open the following link in your web browser:') ?>
</p>

<p>
    <a href="<?= $this->farm->getBaseUri() ?>customers/new_password/k/<?= $this->key ?>">
        <?= $this->farm->getBaseUri() ?>customers/new_password/k/<?= $this->key ?>
    </a>
</p>

<p>
    <?= $this->translate(
        'You\'ll then be asked to supply a new password.  From there you can log in (your user name is %s, just in case you forgot).',
        $this->escape($this->farmer->userName)
    ) ?>
</p>

<p>
    <?= $this->translate('If you need any help resetting your password, please reply to this email.  We\'ll help you out.') ?>
</p>


<p><?= $this->escape($this->farm->name) ?></p>