<?php
    $this->headTitle($this->translate('Reset Your Password'));

    $this->loader()->append('jquery_validate');
?>

<?php $this->placeholder('foot')->captureStart() ?>
<script type="text/javascript">
    $(document).ready(function(){
        if (top.location != self.location) {
            top.location = self.location;
        }
        
        $("#reset").validate({
            rules: {
                "password" : {
                    minlength : 4
                },
                "passwordConfirm" : {
                    equalTo : "#password"
                }
            },
            messages : {
                "passwordConfirm" : {
                    equalTo : "<?= $this->translate('Your passwords are not the same'); ?>"
                }
            },
            errorContainer: $("#formError")
        });
    });
</script>
<?php $this->placeholder('foot')->captureEnd() ?>

<h2><?= $this->translate('Reset Your Password'); ?></h2>

<form id="reset" 
      action="<?php echo $this->escape($this->Url()); ?>" 
      method="post" 
      class="cmxform"
      accept-charset="utf-8">

    <?php if (empty($_POST) && empty($this->badKey)) { ?>
    <section class="info ui-widget ui-state-highlight ui-corner-all">
        <div>
            <i class="fa fa-info-circle"></i>
            <strong><?= $this->translate('Almost Done.'); ?></strong>
            <?= $this->translate('Please enter your email and new password'); ?>
        </div>
    </section>

    <?php } else if (empty($_POST) && !empty($this->badKey)) { ?>
        <section id="formError" class="error ui-widget ui-state-error ui-corner-all">
            <div>
                <i class="fa fa-exclamation-triangle"></i>
                <strong><?= $this->translate('Oh No!'); ?></strong>
                <?= $this->translate('The link that you followed is no good!'); ?>
            </div>
        </section>
    
        <p>
            <?= $this->translate('The link that you followed in the password reset email is no longer valid.') ?>
            <?= $this->translate('The links are only good for a few hours.  Maybe it expired.') ?>
        </p>
        
        <p>
            <?= $this->translate('You can try to <a href="/customers/password_reset">start this process all over again</a>, or <a href="/contact">contact us</a> for help.') ?>
        </p>
    <?php } ?>

    <section id="formError" class="error ui-widget ui-state-error ui-corner-all" style="<?= (!empty($this->errors)) ? '' : 'display:none;' ?>">
        <div>
            <i class="fa fa-exclamation-triangle"></i>
            <strong><?= $this->translate('Oh No!'); ?></strong>
            <?= $this->translate('Something is not right with what you entered.  Check below for hints on how to fix things up.'); ?>
        </div>
    </section>
        
    <?php if (empty($this->badKey) && ((!empty($_POST) && !empty($this->errors)) || (empty($_POST)))) { ?>
        <p>
            <label for="email" class="required">
                <?= $this->translate('Email'); ?>
                <abbr title="<?= $this->translate('This field is required'); ?>">*</abbr>
            </label>
            <input 
                id="email"
                type="text"
                name="email"
                maxlength="255"
                placeholder="email@email.com"
                title="<?= $this->translate('Please enter your email address'); ?>"
                value="<?= (!empty($_POST['email'])) ? $this->escape($_POST['email']) : null; ?>"
                class="large required email<?= (!empty($this->errors['email'])) ? ' error' : ''; ?>" />

            <?php if (!empty($this->errors['email'])) { ?>
            <label for="email" class="error">
                <?= implode('; ', $this->errors['email']) ?>
            </label>
            <?php } ?>
        </p>

        <p>
            <label for="password" title="<?= $this->translate('Please enter a password to log in with'); ?>">
                <?= $this->translate('Password'); ?>:
            </label>
            <input
                id="password"
                name="password"
                type="password"
                title="<?= $this->translate('Please enter a password to log in with'); ?>"
                value="<?= $this->getFormValue('password'); ?>"
                class=""
                maxlength="30"
                autocomplete="off" />

            <?php if (!empty($this->errors['password'])) { ?>
            <label for="password" class="error">
                <?= implode('; ', $this->errors['password']) ?>
            </label>
            <?php } ?>
        </p>

        <p>
            <label for="passwordConfirm" title="<?= $this->translate('Please confirm your password'); ?>">
                <?= $this->translate('Confirm Password'); ?>:
            </label>
            <input
                id="passwordConfirm"
                name="passwordConfirm"
                type="password"
                title="<?= $this->translate('Please confirm your password'); ?>"
                value="<?= $this->getFormValue('passwordConfirm'); ?>"
                class=""
                maxlength="30"
                autocomplete="off" />
        </p>

        <p>
            <button type="submit" class="submit ui-button ui-widget ui-corner-all ui-button-text-only ui-state-default">
                <span class="ui-button-text">
                    <i class="fa fa-key"></i>
                    <?= $this->translate('Update Password'); ?>
                </span>
            </button>
        </p>
    <?php } else if (!empty($_POST) && empty($this->errors)) { ?>
        <section class="info ui-widget ui-state-highlight ui-corner-all">
            <div>
                <i class="fa fa-info-circle"></i>
                <strong><?= $this->translate('Done.'); ?></strong>
                <?= $this->translate('Your password has been updated!'); ?>
            </div>
        </section>
        
        <p>
            <?= $this->translate('You\'re now good to go.  Click here to <a href="/login">log in with your shiny new password</a>.'); ?>
        </p>
    <?php } ?>
</form>
