<?php
    $this->headTitle($this->translate('Reset Your Password'));

    $this->loader()->append('jquery_validate');
?>

<?php $this->placeholder('foot')->captureStart() ?>
<script type="text/javascript">
    $(document).ready(function(){
        if (top.location != self.location) {
            top.location = self.location;
        }
        
        $("#reset").validate();
    });
</script>
<?php $this->placeholder('foot')->captureEnd() ?>

<h2><?= $this->translate('Reset Your Password'); ?></h2>

<?php if ($this->sent == true) { ?>

    <section class="info ui-widget ui-state-highlight ui-corner-all">
        <div>
            <i class="fa fa-info-circle"></i>
            <strong><?= $this->translate('Thanks!'); ?></strong>
            <?= $this->translate('Now check your email.'); ?>
        </div>
    </section>

    <p>
        <?= $this->translate('We\'ve just sent you an email with instructions on how to change your password.'); ?>
    </p>
    
    <p>
        <?= $this->translate('If after 5 minutes you are still twiddling your thumbs waiting on this email, be sure dig around any spam folders for it.'); ?>
    </p>

    <p>
        <?= $this->translate('In the email you will find a special link.  You will need to follow this link to complete the password reset process.'); ?>
        <?= $this->translate('The link will remain active for the next 3 hours.'); ?>
    </p>
    
    <p>
        <?= $this->translate('If you get stuck, please <a href="/contact">contact us</a>.'); ?>
    </p>
    
<?php } else { ?>

    <form id="reset" 
          action="<?php echo $this->escape($this->Url()); ?>" 
          method="post" 
          class="cmxform"
          accept-charset="utf-8">

        <?php if (empty($_POST)) { ?>
        <section class="info ui-widget ui-state-highlight ui-corner-all">
            <div>
                <i class="fa fa-info-circle"></i>
                <strong><?= $this->translate('Can\'t log in?'); ?></strong>
                <?= $this->translate('Has your password been misplaced?'); ?>
            </div>
        </section>

        <p><?= $this->translate(
            'Give us your email address and we\'ll walk you through resetting your password.'
        ) ?></p>
        <?php } ?>

        <?php if ($this->errors !== false) { ?>
        <section id="formError" class="error ui-widget ui-state-error ui-corner-all" style="<?= (!empty($this->errors)) ? '' : 'display:none;' ?>">
            <div>
                <i class="fa fa-exclamation-triangle"></i>
                <strong><?= $this->translate('Oh No!'); ?></strong>
                <?= $this->translate('Something is not right with what you entered.  Check below for hints on how to fix things up.'); ?>
            </div>
        </section>
        <?php } ?>

        <p>
            <label for="email" class="required">
                <?= $this->translate('Email'); ?>
                <abbr title="<?= $this->translate('This field is required'); ?>">*</abbr>
            </label>
            <input 
                id="email"
                type="text"
                name="email"
                maxlength="255"
                placeholder="email@email.com"
                title="<?= $this->translate('Please enter your email address'); ?>"
                value="<?= (!empty($_POST['email'])) ? $this->escape($_POST['email']) : null; ?>"
                class="large required email<?= (!empty($this->errors['email'])) ? ' error' : ''; ?>" />

            <?php if (!empty($this->errors['email'])) { ?>
            <label for="email" class="error">
                <?= implode('; ', $this->errors['email']) ?>
            </label>
            <?php } ?>
        </p>


        <p>
            <button type="submit" class="submit ui-button ui-widget ui-corner-all ui-button-text-only ui-state-default">
                <span class="ui-button-text">
                    <i class="fa fa-envelope-o"></i>
                    <?= $this->translate('Send Email'); ?>
                </span>
            </button>
        </p>
    </form>
<?php } ?>
