<?php
    $this->headTitle($this->translate('You seem to be lost...'));
?>

<h1><?= $this->translate('Page not Found'); ?></h1>

<p><?= $this->translate('While you where out, we probably reorganized a few things.  The page you are looking for is no longer where it was.  Or maybe it was never here in the first place.  If you typed it in by hand, check your spelling.'); ?></p>

<figure style="display: block; width: 384px; margin: 0 auto; margin-top: 20px;">
    <img src="<?= $this->images ?>404.png" alt="404" width="384" height="384" />
</figure>