<?php
    $title = $this->translate('Customer Purchased Product');

    $this->loader()->append('jquery_dropdown');

    $this->headTitle($title);
?>

<?php $this->placeholder('foot')->captureStart() ?>
<script type="text/javascript">
    $(document).ready(function(){
        $('.dropdown-toggle').dropdown();
        $("body").delegate(".delete", "click", function(){
            return window.confirm("<?= $this->translate('Are you sure you want to delete this purchased product?  No turning back after a purchased product delete.'); ?>");
        });
    });
</script>
<?php $this->placeholder('foot')->captureEnd() ?>

<h2 style="display: inline-block; vertical-align: middle; margin-right: 15px; margin-bottom: 11px;">
    <span class="icon-menu icon-menu-members" style="float: left; margin: -10px 7px 0 0;"></span>
    <?= $title ?>
</h2>

<ul class="dropdown-container" style="display: inline-block; vertical-align: top;">
    <li class="dropdown btn-group">
        <a href="#"
            title="<?= $this->translate('Actions') ?>"
            class="btn dropdown-toggle"
            data-toggle="dropdown">
            <?= $this->translate('Actions') ?>
            <span class="caret"></span>
        </a>

        <ul class="dropdown-menu">
            <?php if (!$this->invoice->isEmpty() && !$this->invoice['paid'] && !$this->invoice['pending']) { ?>
            <li><a href="/admin/customers/addon?a=payment&id=<?= (int) $this->object->id ?>"><?= $this->translate('Mark Invoice as Paid') ?></a></li>
            <?php } ?>
            <?php if (!$this->invoice->isEmpty() && $this->invoice['pending']) { ?>
            <li><a href="/admin/customers/invoice?a=edit&id=<?= (int) $this->invoice->id ?>"><?= $this->translate('Review and Finalize Invoice') ?></a></li>
            <?php } ?>
            <li><a href="/admin/customers/addon?customerId=<?= (int) $this->object->customerId ?>"><?= $this->translate('New Product Purchase') ?></a></li>
            <?php if (!empty($this->customer->email) || !empty($this->customer->secondaryEmail)) { ?>
            <li><a href="/admin/customers/email?id=<?= (int) $this->object->customerId ?>"><?= $this->translate('Email Customer') ?></a></li>
            <?php } ?>
            <li class="divider"></li>
            <li><a class="delete" href="/admin/customers/addon?a=delete&id=<?= (int) $this->object->id ?>"
                   title="<?= $this->translate('Delete this addon') ?>"><?= $this->translate('Delete') ?></a></li>
        </ul>
    </li>
</ul>

<?php if (!empty($this->messages)) { ?>
    <section class="info ui-widget ui-state-highlight ui-corner-all">
        <div>
            <i class="fa fa-info-circle"></i>
            <strong><?= $this->translate('Hey!'); ?></strong>
            <?= $this->escape(implode('; ', $this->messages)); ?>
        </div>
    </section>
<?php } ?>

<?php if (!$this->invoice->isEmpty() && $this->invoice['pending']) { ?>
    <section class="info ui-widget ui-state-highlight ui-corner-all">
        <div>
            <i class="fa fa-info-circle"></i>
            <strong><?= $this->translate('Hey!'); ?></strong>
            <?= $this->translate(
                'This invoice requires that you <a href="%s">finalize it</a> before it is available for payment.',
                '/admin/customers/invoice?a=edit&id=' . (int) $this->invoice->id
            ) ?>
        </div>
    </section>
<?php } ?>

<dl class="cmxlist">
    <dt>
        <?= $this->translate('Customer') ?>:
    </dt>
    <dd>
        <a href="/admin/customers/customer?id=<?= $this->customer->id ?>">
            <?php if (!empty($this->customer->firstName)) { ?>
                <?= $this->escape($this->customer->firstName) ?>,
            <?php } ?>
            <?= $this->escape($this->customer->lastName) ?>
        </a>
    </dd>

    <dt>
        <?= $this->translate('Product') ?>:
    </dt>
    <dd>
        <a href="/admin/shares/addon?id=<?= $this->addon->id ?>">
            <?= $this->escape($this->addon->name) ?>
        </a>
    </dd>

    <dt>
        <?= $this->translate('Share Week') ?>:
    </dt>
    <dd>
        <?php
            list($year , $week) = explode('W', $this->object->week);

            $date = new Zend_Date();
            $date->setYear($year);
            $date->setWeek($week);
            $date->set(1, Zend_Date::WEEKDAY_8601);

            $range = $date->toString('yyyy-MM-dd') . ' - ';
            $date->set(7, Zend_Date::WEEKDAY_8601);
            $range .= $date->toString('yyyy-MM-dd');
        ?>
        <?= $this->escape($range); ?>
    </dd>

    <?php if (!$this->invoice->isEmpty()) { ?>
    <dt>
        <?= $this->translate('Invoice') ?>:
    </dt>

    <dd>
        <table style="width: 600px">
            <thead>
                <tr>
                    <th>
                        <?= $this->translate('Description') ?>
                    </th>
                    <th>
                        <?= $this->translate('Unit Price') ?>
                    </th>
                    <th>
                        <?= $this->translate('Quantity') ?>
                    </th>
                    <th>
                        <?= $this->translate('Total') ?>
                    </th>
                </tr>
            </thead>
            <tbody>
            <?php foreach ($this->invoice->getLines() as $line) { ?>
                <tr>
                    <td>
                        <?php if ($line['referenceId'] == $this->object['id']) { ?>
                        <?= $this->escape($line['description']) ?>
                        <?php } else { ?>
                        <a href="/admin/customers/addon?id=<?= (int) $line['referenceId'] ?>">
                            <?= $this->escape($line['description']) ?>
                        </a>
                        <?php } ?>
                    </td>
                    <td><?= $this->escape($line['unitPrice']) ?></td>
                    <td><?= $this->escape($line['quantity']) ?></td>
                    <td><?= $this->escape($line['total']) ?></td>
                </tr>
            <?php } ?>
            </tbody>
            <tfoot>
                <tr style="border-top: 1px solid #444;">
                    <td colspan="3">
                        <?= $this->translate('Sub-Total') ?>
                    </td>
                    <td>
                        <?= $this->escape($this->invoice['subTotal']) ?>
                    </td>
                </tr>
                <tr>
                    <td colspan="3">
                        <?= $this->translate('Tax') ?>
                    </td>
                    <td>
                        <?= $this->escape($this->invoice['tax']) ?>
                    </td>
                </tr>
                <tr style="<?= ($this->invoice['total'] == $this->invoice['outstandingAmount']) ? 'font-weight: bold;' : '' ?>">
                    <td colspan="3">
                        <?= $this->translate(
                            'Total (Due %s)',
                            $this->escape($this->invoice->dueDate->get('yyyy-MM-dd'))
                        ) ?>
                    </td>
                    <td>
                        <?= $this->escape($this->invoice['total']) ?>
                        <?php if (!$this->invoice->isEmpty() && $this->invoice['pending']) { ?>
                            (<?= $this->translate('Estimate') ?>)
                        <?php } ?>
                    </td>
                </tr>

                <?php if ($this->invoice['total'] != $this->invoice['outstandingAmount']) { ?>
                <tr style="font-weight: bold;">
                    <td colspan="3">
                        <?= $this->translate('Outstanding Amount Due') ?>
                    </td>
                    <td>
                        <?= $this->escape($this->invoice['outstandingAmount']) ?>
                    </td>
                </tr>
                <?php } ?>
            </tfoot>
        </table>
    </dd>

        <?php if ($this->invoice['paid']) { ?>

        <dt>
            <?= $this->translate('Payment') ?>:
        </dt>
        <dd>
            <?= $this->escape($this->object->payment) ?>
        </dd>

        <?php } ?>

    <?php } ?>

    <dt>
        <?= $this->translate('Added') ?>:
    </dt>
    <dd>
        <time datetime="<?= $this->escape($this->object->addedDatetime->get(Zend_Date::ISO_8601)) ?>"
              title="<?= $this->escape($this->object->addedDatetime->get(Zend_Date::ISO_8601)) ?>" pubdate="pubdate">
            <?= $this->escape($this->object->addedDatetime->get('yyyy-MM-dd')) ?>
        </time>
    </dd>

    <dt>
        <?= $this->translate('Updated') ?>:
    </dt>
    <dd>
        <time datetime="<?= $this->escape($this->object->updatedDatetime->get(Zend_Date::ISO_8601)) ?>"
              title="<?= $this->escape($this->object->updatedDatetime->get(Zend_Date::ISO_8601)) ?>">
            <?= $this->escape($this->object->updatedDatetime->get('yyyy-MM-dd')) ?>
        </time>
    </dd>
</dl>
