<?php
    $title = $this->translate('Customer');
    $this->loader()->append('jquery_dataTables')
        ->append('jquery_dropdown');

    $this->loadDatejs(Bootstrap::$locale);

    $this->headTitle($title);

    $this->loader()->append('jquery_validate');
?>

<?php $this->placeholder('foot')->captureStart() ?>
<script type="text/javascript">
    $(document).ready(function(){
        $( "#tabs" ).tabs({
            ajaxOptions: {
                error: function(xhr, status, index, anchor) {
                    $(anchor.hash).html(
                        '<section class="error ui-widget ui-state-error ui-corner-all">' +
                        '<div><i class="fa fa-exclamation-triangle"></i>' +
                        '<strong><?= addslashes($this->translate('Oh No!')); ?></strong> ' +
                        '<?= addslashes($this->translate('Couldn\'t load this tab. Please try reloading the page.')); ?>' +
                        '</div></section>'
                    );
                }
            }
        });

        $('.dropdown-toggle').dropdown();

        $(".dropdown-container").on("click", ".dropdown-menu a", function(event){
            if ($(this).hasClass('delete')) {
                return window.confirm("<?= $this->translate('PLEASE READ THIS IMPORTANT MESSAGE.  Are you sure you want to delete this customer?  All coresponding customer records (share orders, products, transactions, etc...) will be deleted too.  This is a severe thing to do.  You might want to disable this customer instead.  No turning back after a customer delete!'); ?>");
            }
        });
    });
</script>
<?php $this->placeholder('foot')->captureEnd() ?>

<h2 style="display: inline-block; vertical-align: middle; margin-right: 15px; margin-bottom: 11px;">
    <span class="icon-menu icon-menu-members" style="float: left; margin: -10px 7px 0 0;"></span>
    <?= $title ?>
</h2>

<ul class="dropdown-container" style="display: inline-block;">
    <li class="dropdown btn-group">
        <a href="#"
            title="<?= $this->translate('Actions') ?>"
            class="btn dropdown-toggle"
            data-toggle="dropdown">
            <?= $this->translate('Actions') ?>
            <span class="caret"></span>
        </a>

        <ul class="dropdown-menu">
            <li><a href="/admin/customers/customer?a=edit&id=<?= (int) $this->customer->id ?>"><?= $this->translate('Edit') ?></a></li>
            <?php if (!empty($this->customer->email) || !empty($this->customer->secondaryEmail)) { ?>
            <li><a href="/admin/customers/email?id=<?= (int) $this->customer->id ?>"><?= $this->translate('Email') ?></a></li>
            <?php } ?>
            <li><a href="/admin/customers/customer?format=vcf&id=<?= (int) $this->customer->id ?>"
                    title="<?= $this->translate('Used to import contacts into your email client') ?>"><?= $this->translate('Export vCard') ?></a></li>
            <li><a href="/admin/customers/subscription?customerId=<?= (int) $this->customer->id ?>"
                    title="<?= $this->translate('Add a new subscription for this customer') ?>"><?= $this->translate('New Subscription') ?></a></li>
            <li><a href="/admin/customers/addon?customerId=<?= (int) $this->customer->id ?>"
                   title="<?= $this->translate('Add a new purchased product for this customer') ?>"><?= $this->translate('New Product Purchase') ?></a></li>
            <?php if ($this->customer->balance > 0) { ?>
            <li><a href="/admin/customers/customer?a=payBalance&id=<?= (int) $this->customer->id ?>"
                   title="<?= $this->translate('Mark full balance due as paid') ?>"><?= $this->translate('Mark Balance as Paid') ?></a></li>
            <?php } ?>
            <li class="divider"></li>
            <li><a class="delete" href="/admin/customers/customer?a=delete&id=<?= (int) $this->customer->id ?>"><?= $this->translate('Delete') ?></a></li>
        </ul>
    </li>
</ul>

<section class="container_12">
    <article class="grid_11">

        <?php if (!empty($this->messages)) { ?>
            <section class="info ui-widget ui-state-highlight ui-corner-all">
                <div>
                    <i class="fa fa-info-circle"></i>
                    <strong><?= $this->translate('Hey!'); ?></strong>
                    <?= $this->escape(implode('; ', $this->messages)); ?>
                </div>
            </section>
        <?php } ?>

        <div id="tabs">
            <ul>
                <li>
                    <a href="#customer-tab">
                        <?= $this->translate('Customer') ?>
                    </a>
                </li>
                <li>
                    <a href="/admin/customers/purchase-history-shares/e/1?cid=<?= $this->customer->id ?>">
                        <?= $this->translate('Shares') ?>
                    </a>
                </li>
                <li>
                    <a href="/admin/customers/purchase-history-addons/e/1?cid=<?= $this->customer->id ?>">
                        <?= $this->translate('Products') ?>
                    </a>
                </li>
                <li>
                    <a href="/admin/customers/invoices-history/e/1?cid=<?= $this->customer->id ?>">
                        <?= $this->translate('Invoices') ?>
                    </a>
                </li>
                <li>
                    <a href="/admin/customers/transactions-history/e/1?cid=<?= $this->customer->id ?>">
                        <?= $this->translate('Payments') ?>
                    </a>
                </li>
                <li>
                    <a href="/admin/customers/vacations/e/1?cid=<?= $this->customer->id ?>">
                        <?= $this->translate('Vacations') ?>
                    </a>
                </li>
                <li>
                    <a href="/admin/customers/notes/e/1?cid=<?= $this->customer->id ?>">
                        <?= $this->translate('Notes') ?>
                    </a>
                </li>
            </ul>

            <div id="customer-tab">

                <h2><?= $this->translate('Contact Info') ?></h2>

                <dl class="cmxlist clearfix">
                    <dt>
                        <?= $this->translate('Customer #'); ?>:
                    </dt>
                    <dd>
                        <?= $this->escape($this->customer['id']) ?>
                    </dd>

                    <dt>
                        <?= $this->translate('First Name'); ?>:
                    </dt>
                    <dd>
                        <?= $this->escape($this->customer['firstName']) ?>
                    </dd>

                    <dt>
                        <?= $this->translate('Last Name'); ?>:
                    </dt>
                    <dd>
                        <?= $this->escape($this->customer['lastName']) ?>
                    </dd>

                    <dt>
                        <?= $this->translate('Address'); ?>:
                    </dt>
                    <dd>
                        <?= $this->escape($this->customer['address']) ?>
                    </dd>

                    <dt>
                        <?= $this->translate('Address'); ?>:
                    </dt>
                    <dd>
                        <?= $this->escape($this->customer['address2']) ?>
                    </dd>

                    <dt>
                        <?= $this->translate('Town'); ?>:
                    </dt>
                    <dd>
                        <?= $this->escape($this->customer['city']) ?>
                    </dd>

                    <dt>
                        <?= $this->translate('State / Province'); ?>:
                    </dt>
                    <dd>
                        <?= $this->escape($this->customer['state']) ?>
                    </dd>

                    <dt>
                        <?= $this->translate('Zip Code'); ?>:
                    </dt>
                    <dd>
                        <?= $this->escape($this->customer['zipCode']) ?>
                    </dd>

                    <dt>
                        <?= $this->translate('Email'); ?>:
                    </dt>
                    <dd>
                        <?php if (!empty($this->customer['email'])) { ?>
                        <a href="/admin/customers/email?id=<?= (int) $this->customer->id ?>">
                            <?= $this->escape($this->customer['email']) ?></a>
                        <a href="mailto:<?= $this->escape($this->customer['email']) ?>"
                           style="display: inline-block"
                           alt="<?= $this->escape('Send email with external email program') ?>">
                            <i class="fa fa-envelope"></i></a>
                        <?php } ?>
                    </dd>

                    <dt>
                        <?= $this->translate('Telephone'); ?>:
                    </dt>
                    <dd>
                        <?= $this->escape($this->customer['telephone']) ?>
                    </dd>

                    <dt>
                        <?= $this->translate('Fax'); ?>:
                    </dt>
                    <dd>
                        <?= $this->escape($this->customer['fax']) ?>
                    </dd>

                    <dt>
                        <?= $this->translate('Enabled'); ?>:
                    </dt>
                    <dd>
                        <?php if ($this->customer['enabled']) { ?>
                            <?= $this->translate('Yes') ?>
                        <?php } else { ?>
                            <?= $this->translate('No') ?>
                        <?php } ?>
                    </dd>
                </dl>

                <?php if (!empty($this->customer['secondaryFirstName'])
                    || !empty($this->customer['secondaryLastName'])
                    || !empty($this->customer['secondaryEmail'])) { ?>

                <h2><?= $this->translate('Secondary Contact') ?></h2>
                <dl class="cmxlist clearfix">
                    <dt>
                        <?= $this->translate('First Name'); ?>:
                    </dt>
                    <dd>
                        <?= $this->escape($this->customer['secondaryFirstName']) ?>
                    </dd>

                    <dt>
                        <?= $this->translate('Last Name'); ?>:
                    </dt>
                    <dd>
                        <?= $this->escape($this->customer['secondaryLastName']) ?>
                    </dd>

                    <dt>
                        <?= $this->translate('Email'); ?>:
                    </dt>
                    <dd>
                        <?= $this->escape($this->customer['secondaryEmail']) ?>
                    </dd>

                </dl>
                <?php } ?>

                <?php if ($this->customer->getFarmer() instanceof HH_Domain_Farmer) { ?>
                <h2><?= $this->translate('Login Details') ?></h2>
                <dl class="cmxlist clearfix">
                    <dt>
                        <?= $this->translate('User Name'); ?>:
                    </dt>
                    <dd>
                        <?= $this->escape($this->customer->getFarmer()->userName) ?>
                    </dd>

                </dl>
                <?php } ?>

                <h2><?= $this->translate('Current Balance') ?></h2>
                <dl class="cmxlist clearfix">
                    <dt>
                        <?= $this->translate('Total Due'); ?>:
                    </dt>
                    <dd>
                        <?= $this->escape($this->currency($this->customer['balance'])) ?>
                    </dd>

                </dl>

                <h2><?= $this->translate('Additional Info') ?></h2>
                <dl class="cmxlist clearfix">
                    <dt>
                        <?= $this->translate('Newsletter Opt-Out'); ?>:
                    </dt>
                    <dd>
                        <?= (int) $this->customer->getPreferences()->get('optOut', 'newsletter', 0) ?
                            $this->translate('Yes') :
                            $this->translate('No') ?>
                    </dd>
                    <?php if(!empty($this->customer->notes)){ ?>
                    <dt>
                        <?= $this->translate('Notes'); ?>:
                    </dt>
                    <dd>
                        <?= $this->escape($this->customer->notes) ?>
                    </dd>
                    <?php } ?>
                </dl>
            </div>
        </div>
    </article>
</section>