<?php
    $this->headTitle($this->translate('Customers'));

    $this->loader()->append('jquery_dataTables')
        ->append('jquery_dropdown');

    Bootstrap::getZendCurrency();
?>

<?php $this->placeholder('foot')->captureStart() ?>
<script type="text/javascript">
    $(document).ready(function(){

        $.fn.dataTableExt.aoFeatures.push({
            "fnInit": function(oSettings) {
                return $('<ul class="dataTables_add dropdown-container"><li class="dropdown btn-group">' +
                    '<a href="/admin/customers/customer" title="<?= $this->translate('Add new customer') ?>" class="btn">' +
                    '<?= addslashes($this->translate('Add')) ?></a>' +
                    '<button type="button" class="btn dropdown-toggle" data-toggle="dropdown">' +
                    '<span class="caret"></span></button>' +
                    '<ul class="dropdown-menu"><li><a href="/admin/customers/customers/format/csv" title="<?= $this->translate('Export to a spreadsheet program') ?>">' +
                    '<?= $this->translate('Export to CSV') ?></a></li>' +
                    '<li><a href="/admin/customers/customers/format/vcf" title="<?= $this->translate('Export to an email program') ?>">' +
                    '<?= $this->translate('Export as vCard') ?></a></li></ul></li></ul>')[0];
            },
            "cFeature": "a",
            "sFeature": "Add"
        });

        var table = $("#customers").dataTable({
            "bJQueryUI": true,
            "bAutoWidth": false,
            "bDeferRender": true,
            "bLengthChange": false,
            "bProcessing": true,
            "iDisplayLength": 50,
            "iDeferLoading": <?= $this->foundRows ?>,
            "aaSorting": <?= $this->DataTable(
                    'customers',
                    array(
                        'firstName',
                        'lastName',
                        'balance',
                        'addedDatetime',
                        'enabled'
                    )
                )->sorting($this->farmer, 'lastName') ?>,
            "aoColumns": [
                {
                    "sType": "html",
                    "mDataProp": "firstName",
                    "fnRender": function (oObj) {
                        if (!oObj.aData.hasOwnProperty("id")) {
                            return oObj.aData.firstName;
                        } else {
                            return '<a href="/admin/customers/customer?id=' + parseInt(oObj.aData.id) + '">' +
                                oObj.aData.firstName
                                    .replace(/&/g,'&amp;')
                                    .replace(/</g,'&lt;')
                                    .replace(/>/g,'&gt;') + '</a>';
                        }
                    }
                },
                {
                    "sType": "html",
                    "mDataProp": "lastName",
                    "fnRender": function (oObj) {
                        if (!oObj.aData.hasOwnProperty("id")) {
                            return oObj.aData.lastName;
                        } else {
                            return '<a href="/admin/customers/customer?id=' + parseInt(oObj.aData.id) + '">' +
                                oObj.aData.lastName
                                    .replace(/&/g,'&amp;')
                                    .replace(/</g,'&lt;')
                                    .replace(/>/g,'&gt;') + '</a>';
                        }
                    }
                },
                {
                    "sType": "text",
                    "mDataProp": "balance"
                },
                {
                    "sType": "string",
                    "mDataProp": "addedDatetime"
                },
                {
                    "sType": "string",
                    "mDataProp": "enabled",
                    "fnRender": function(oObj) {
                        if (!oObj.aData.hasOwnProperty("id")) {
                            return oObj.aData.enabled;
                        }
                        if (parseInt(oObj.aData.enabled) == true) {
                            return "<?= addslashes($this->translate('Yes')) ?>";
                         } else {
                             return "<?= addslashes($this->translate('No')) ?>";
                         }
                    }
                },
                {
                    "bSortable": false,
                    "bSearchable": false,
                    "mDataProp": "_actions",
                    "sClass": "right",
                    "fnRender": function (oObj) {
                        if (!oObj.aData.hasOwnProperty("id")) {
                            return oObj.aData._actions;
                        }

                        var menu = '<ul class="dropdown-container">' +
                            '<li class="dropdown btn-group">' +
                            '<a href="/admin/customers/customer?id=' + parseInt(oObj.aData.id) + '" ' +
                            'title="<?= $this->translate('View') ?>" class="btn">' +
                            '<?= $this->translate('View') ?>' +
                            '</a>' +
                            '<button type="button" class="btn dropdown-toggle" ' +
                            'data-toggle="dropdown">' +
                            '<span class="caret"></span>' +
                            '</button>' +
                            '<ul class="dropdown-menu">' +
                            '<li><a href="/admin/customers/customer?a=edit&id=' + parseInt(oObj.aData.id) + '"><?= $this->translate('Edit') ?></a></li>';

                        if (oObj.aData.email || oObj.aData.secondaryEmail) {
                            menu += '<li><a href="/admin/customers/email?id=' + parseInt(oObj.aData.id) + '"><?= $this->translate('Email') ?></a></li>';
                        }

                        menu += '<li><a href="/admin/customers/customer?format=vcf&id=' + parseInt(oObj.aData.id) + '"' +
                            ' title="<?= addslashes($this->translate('Used to import contacts into your email client')) ?>"><?= addslashes($this->translate('Export vCard')) ?></a></li>' +
                            '<li><a href="/admin/customers/subscription?customerId=' + parseInt(oObj.aData.id) + '" ' +
                            'title="<?= addslashes($this->translate('Add a new subscription for this customer')) ?>"><?= addslashes($this->translate('New Subscription')) ?></a></li>' +
                            '<li class="divider"></li>';

                        if (parseFloat(oObj.aData.balance.match(/\d+\.?\d*/g)) > 0) {
                            menu += '<li><a href="/admin/customers/customer?a=payBalance&r=s&id=' + parseInt(oObj.aData.id) + '"' +
                                'title="<?= addslashes($this->translate('Mark full balance due as paid')) ?>"><?= addslashes($this->translate('Mark Balance as Paid')) ?></a></li>';
                        }

                        menu += '<li><a class="delete" href="/admin/customers/customer?a=delete&id=' + parseInt(oObj.aData.id) + '"><?= $this->translate('Delete') ?></a></li>' +
                            '</ul></li></ul>';

                        return menu;
                    }
                }
            ],
            "bSortClasses": false,
            "sAjaxSource": "<?= addslashes($this->Url()) ?>",
            "bServerSide": true,
            "sDom": '<"H"af<"clear">r<"right"ip>>t<"F"<"right"ip>>'
        })
        .delegate("tbody tr", "mouseover mouseout", function(e) {
            if (e.type == "mouseover") {
                $(e.currentTarget).addClass('hover');
            } else {
                $(e.currentTarget).removeClass('hover');
            }
        })
        .delegate(".delete", "click", function(){
            return window.confirm("<?= $this->translate('PLEASE READ THIS IMPORTANT MESSAGE.  Are you sure you want to delete this customer?  All coresponding customer records (share orders, products, transactions, etc...) will be deleted too.  This is a severe thing to do.  You might want to disable this customer instead.  No turning back after a customer delete!'); ?>");
        })
        .fnSetFilteringDelay(1000);

        new FixedHeader(table);

        $('.dropdown-toggle').dropdown();
    });


</script>
<?php $this->placeholder('foot')->captureEnd() ?>

<h2>
    <span class="icon-menu icon-menu-members" style="float: left; margin: -10px 7px 0 0;"></span>
    <?= $this->translate('Customers') ?>
</h2>

<section class="container_12">
    <article class="grid_9">

        <?php if (!empty($this->messages)) { ?>
            <section class="info ui-widget ui-state-highlight ui-corner-all">
                <div>
                    <i class="fa fa-info-circle"></i>
                    <strong><?= $this->translate('Hey!'); ?></strong>
                    <?= $this->escape(implode('; ', $this->messages)); ?>
                </div>
            </section>
        <?php } ?>

        <?php if (count($this->customers)) { ?>

            <table id="customers" class="display">
                <thead>
                    <tr>
                        <th
                            width="23%"
                            title="<?= $this->translate('Customer First Name') ?>">
                                <?= $this->translate('First Name'); ?>
                        </th>
                        <th
                            width="23%"
                            title="<?= $this->translate('Customer Last Name') ?>">
                                <?= $this->translate('Last Name') ?>
                        </th>
                        <th
                            width="13%"
                            title="<?= $this->translate('Customer Balance Due') ?>">
                                <?= $this->translate('Balance') ?>
                        </th>
                        <th
                            width="16%"
                            title="<?= $this->translate('Date Customer Added') ?>">
                                <?= $this->translate('Added') ?>
                        </th>
                        <th
                            width="8%"
                            title="<?= $this->translate('Customer Status') ?>">
                                <?= $this->translate('On') ?>
                        </th>
                        <th
                            width="17%"
                            title="<?= $this->translate('Customer Actions') ?>">
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->customers as $customer) { ?>
                        <tr>
                            <td>
                                <a href="/admin/customers/customer?id=<?= (int) $customer->id ?>">
                                    <?= $this->escape($customer->firstName); ?>
                                </a>
                            </td>
                            <td>
                                <a href="/admin/customers/customer?id=<?= (int) $customer->id ?>">
                                    <?= $this->escape($customer->lastName); ?>
                                </a>
                            </td>
                            <td>
                                <?= $this->currency($customer['balance']) ?>
                            </td>
                            <td>
                                <?= $this->escape($customer->addedDatetime->toString('yyyy-MM-dd')); ?>
                            </td>
                            <td>
                                <?= ($customer->enabled) ?
                                        $this->translate('Yes') :
                                        $this->translate('No');
                                ?>
                            </td>
                            <td class="right">
                                <ul class="dropdown-container">
                                    <li class="dropdown btn-group">
                                        <a href="/admin/customers/customer?id=<?= (int) $customer->id ?>"
                                           title="<?= $this->translate('View') ?>"
                                           class="btn">
                                            <?= $this->translate('View') ?>
                                        </a>
                                        <button type="button"
                                                class="btn dropdown-toggle"
                                                data-toggle="dropdown">
                                            <span class="caret"></span>
                                        </button>

                                        <ul class="dropdown-menu">
                                            <li><a href="/admin/customers/customer?a=edit&id=<?= (int) $customer->id ?>"><?= $this->translate('Edit') ?></a></li>
                                            <?php if (!empty($customer->email) || !empty($customer->secondaryEmail)) { ?>
                                            <li><a href="/admin/customers/email?id=<?= (int) $customer->id ?>"><?= $this->translate('Email') ?></a></li>
                                            <?php } ?>
                                            <li><a href="/admin/customers/customer?format=vcf&id=<?= (int) $customer->id ?>"
                                                   title="<?= $this->translate('Used to import contacts into your email client') ?>"><?= $this->translate('Export vCard') ?></a></li>
                                            <li><a href="/admin/customers/subscription?customerId=<?= (int) $customer->id ?>"
                                                   title="<?= $this->translate('Add a new subscription for this customer') ?>"><?= $this->translate('New Subscription') ?></a></li>
                                            <li class="divider"></li>
                                            <?php if ($customer->balance > 0) { ?>
                                            <li><a href="/admin/customers/customer?a=payBalance&r=s&id=<?= (int) $customer->id ?>"
                                                   title="<?= $this->translate('Mark full balance due as paid') ?>"><?= $this->translate('Mark Balance as Paid') ?></a></li>
                                            <?php } ?>
                                            <li><a class="delete" href="/admin/customers/customer?a=delete&id=<?= (int) $customer->id ?>"><?= $this->translate('Delete') ?></a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </td>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>

        <?php } else { ?>

            <p><?=
                $this->translate(
                    'You haven\'t added any customers yet.  <a href="%s">Let\'s add one now.</a>',
                    '/admin/customers/customer'
                ); ?></p>

        <?php } ?>
    </article>

    <?= $this->render('admin-sub-nav.phtml'); ?>
</section>
