<?php
    $this->headTitle($this->translate('Customer Email'));
    
    $this->loader()->append('jquery_validate')
        ->append('ckeditor_ckeditor.js')
        ->append('ckeditor_adapters_jquery.js');
?>

<?php $this->placeholder('head')->captureStart() ?>
<script type="text/javascript">
    window.CKEDITOR_BASEPATH = '<?= (!empty($_SERVER['HTTPS'])) ? 'https://static.' : 'http://static.' ?><?= Bootstrap::$rootDomain ?>/_js/ckeditor/';
</script>
<?php $this->placeholder('head')->captureEnd() ?>

<?php $this->placeholder('foot')->captureStart() ?>
<script type="text/javascript">
    $(document).ready(function(){
        var config = {
            customConfig : '',
            toolbar:
            [
                ['Bold','Italic','Underline','Strike'],
                ['NumberedList','BulletedList','-','Outdent','Indent','Blockquote'],
                ['Link','Unlink'],
                ['Cut','Copy','Paste','PasteText','PasteFromWord'],
                ['Undo','Redo']
                ['RemoveFormat']
            ],
            colorButton_enableMore: false,
            disableNativeSpellChecker: false
        };

        $('#html').ckeditor(
            function(){
                var editor = $('#html').ckeditorGet();
                editor.on( "blur", function() {
                    this.updateElement();
                });
            },
            config
        );
        
        $.validator.addMethod(
            "ckeditorRequired",
            function(value, element) {
                var $element = $(element);
                
                $element.ckeditorGet().updateElement();
                
                return ($element.val().length) ? true: false;
            },
            '<?= addslashes($this->translate('This field is required')); ?>'
        );
        
        jQuery.validator.setDefaults({
            ignore: ''
        });
        
        $("#email").validate({
            rules: {
                "html" : "ckeditorRequired"
            },
            messages : {},
            errorContainer: $("#formError"),
            submitHandler: function(form) {
                $('#html').ckeditorGet().updateElement();
                form.submit();
            }
        });
    });
</script>
<?php $this->placeholder('foot')->captureEnd() ?>

<h2>
    <span class="icon-menu icon-menu-members" style="float: left; margin: -10px 7px 0 0;"></span>
    <?= $this->translate('Email') ?>
</h2>

<form id="email" action="/admin/customers/email?<?= http_build_query($_GET) ?>" method="post" accept-charset="utf-8" class="cmxform large">

    <section id="formError" class="error ui-widget ui-state-error ui-corner-all" style="<?= (!empty($this->errors)) ? '' : 'display:none;' ?>">
        <div>
            <i class="fa fa-exclamation-triangle"></i>
            <strong><?= $this->translate('Oh No!'); ?></strong>
            <?= $this->translate('Something is not right with what you entered.  Check below for hints on how to fix things up.'); ?>
        </div>
    </section>

    <fieldset>
        <legend><?= $this->translate('Header') ?></legend>
        
        <p>
            <label for="from" class="required" title="<?= $this->translate('Please select who this email is from'); ?>">
                <?= $this->translate('From'); ?>:
                <abbr title="<?= $this->translate('This field is required'); ?>">*</abbr>
            </label>
            <?=
                $this->formSelect(
                    'from',
                    $this->getFormValue('from'),
                    array(
                        'id' => 'from',
                        'class' => 'required',
                        'title' => $this->translate('Please select who this email is from')
                    ),
                    $this->from
                );
            ?>

            <?php if (!empty($this->errors['from'])) { ?>
            <label for="from" class="error">
                <?= implode('; ', $this->errors['from']) ?>
            </label>
            <?php } ?>
        </p>
        
        <p>
            <label for="to" class="required" title="<?= $this->translate('Please select the customer\'s email'); ?>">
                <?= $this->translate('To'); ?>:
                <abbr title="<?= $this->translate('This field is required'); ?>">*</abbr>
            </label>
            <?=
                $this->formSelect(
                    'to',
                    $this->getFormValue('to'),
                    array(
                        'id' => 'to',
                        'class' => 'required',
                        'title' => $this->translate('Please select the customer\'s email')
                    ),
                    $this->to
                );
            ?>

            <?php if (!empty($this->errors['to'])) { ?>
            <label for="to" class="error">
                <?= implode('; ', $this->errors['to']) ?>
            </label>
            <?php } ?>
        </p>
        
        <p>
            <label for="subject" class="required" title="<?= $this->translate('Please enter the subject of your email'); ?>">
                <?= $this->translate('Subject'); ?>:
                <abbr title="<?= $this->translate('This field is required'); ?>">*</abbr>
            </label>
            <input
                id="subject"
                name="subject"
                type="text"
                title="<?= $this->translate('Please enter the subject of your email'); ?>"
                value="<?= $this->getFormValue('subject'); ?>"
                class="required large"
                maxlength="100" />

            <?php if (!empty($this->errors['subject'])) { ?>
            <label for="subject" class="error">
                <?= implode('; ', $this->errors['subject']) ?>
            </label>
            <?php } ?>
        </p>
        
    </fieldset>
    
    <fieldset>
        <legend><?= $this->translate('Body') ?></legend>
        
        <p>
            <textarea
                id="html"
                name="html"
                title="<?= $this->translate('Enter the email body'); ?>"
                class="large"
                cols="10"
                rows="10"><?= $this->getFormValue('html'); ?></textarea>
            <?php if (!empty($this->errors['html'])) { ?>
            <label for="html" class="error">
                <?= implode('; ', $this->errors['html']) ?>
            </label>
            <?php } ?>
        </p>
    </fieldset>
    <p>
        <button type="submit" class="submit fieldset-align ui-button ui-widget ui-corner-all ui-button-text-icon-primary ui-state-default">
            <span class="ui-button-icon-primary ui-icon ui-icon-mail-closed"></span>
            <span class="ui-button-text">
                <?= $this->translate('Send!'); ?>
            </span>
        </button>
    </p>
</form>
