<?php
    $this->headTitle($this->translate('Customer Invoices'));

    $this->loader()->append('jquery_dataTables')
        ->append('jquery_dropdown');

    $this->loadDatejs(Bootstrap::$locale);
    
    Bootstrap::getZendCurrency();
?>

<?php $this->placeholder('foot')->captureStart() ?>
<script type="text/javascript">
    $(document).ready(function(){

        $.fn.dataTableExt.aoFeatures.push({
            "fnInit": function(oSettings) {
                return $('<ul class="dataTables_add dropdown-container"><li class="dropdown btn-group">' +
                    '<a href="#" title="<?= $this->translate('Actions') ?>" class="btn">' +
                    '<?= addslashes($this->translate('Actions')) ?></a>' +
                    '<button type="button" class="btn dropdown-toggle" data-toggle="dropdown">' +
                    '<span class="caret"></span></button>' +
                    '<ul class="dropdown-menu"><li><a href="/admin/customers/invoices/format/csv/year/<?= (int) $this->year ?>" title="<?= $this->translate('Export to a spreadsheet program') ?>">' +
                    '<?= $this->translate('Export to CSV') ?></a></li></ul></li></ul>')[0];
            },
            "cFeature": "a",
            "sFeature": "Add"
        });
        
        $.fn.dataTableExt.aoFeatures.push({
            "fnInit": function(oSettings) {
                return $(
                    '<form class="dataTables_year" action="/admin/customers/invoices" method="get" style="float: left; padding-right: 10px">' +
                    <?php if (count($this->years) > 1) { ?>
                        '<label for="year"><?= addslashes($this->translate('Year')); ?>: </label>' +
                        '<?=
                            addslashes(str_replace("\n", '', $this->formSelect(
                                'year',
                                $this->year,
                                array(),
                                $this->years
                            )));
                        ?>' +
                    <?php } ?>
                    '</form> '
                )[0];
            },
            "cFeature": "y",
            "sFeature": "Year"
        });
        
        var table = $("#invoices").dataTable({
            "bJQueryUI": true,
            "bAutoWidth": false,
            "bDeferRender": true,
            "bLengthChange": false,
            "bProcessing": true,
            "iDisplayLength": 50,
            "iDeferLoading": <?= $this->foundRows ?>,
            "aaSorting": [[2, "desc"]],
            "aoColumns": [ 
                {
                    "sType": "string",
                    "mDataProp": "id"
                },
                {
                    "sType": "text",
                    "mDataProp": "customer",
                    "fnRender": function (oObj) {
                        if (!oObj.aData.hasOwnProperty("DT_RowId")) {
                            return oObj.aData.customer;
                        } else {
                            return oObj.aData.customerLastName
                                .replace(/&/g,'&amp;')
                                .replace(/</g,'&lt;')
                                .replace(/>/g,'&gt;') + ", " +
                                oObj.aData.customerFirstName
                                .replace(/&/g,'&amp;')
                                .replace(/</g,'&lt;')
                                .replace(/>/g,'&gt;');
                        }
                    }
                },
                {
                    "sType": "text",
                    "mDataProp": "dueDate",
                    "fnRender": function (oObj) {
                        if (!oObj.aData.hasOwnProperty("DT_RowId")) {
                            return oObj.aData.dueDate;
                        } else {
                            return oObj.aData.dueDate.replace(/&/g,'&amp;')
                                    .replace(/</g,'&lt;')
                                    .replace(/>/g,'&gt;');
                        }
                    }
                },
                {
                    "sType": "text",
                    "mDataProp": "total"
                },
                {
                    "sType": "text",
                    "mDataProp": "outstandingAmount"
                },
                { 
                    "bSortable": false,
                    "bSearchable": false,
                    "mDataProp": "_actions",
                    "sClass": "right",
                    "fnRender": function (oObj) {
                        if (!oObj.aData.hasOwnProperty("DT_RowId")) {
                            return oObj.aData._actions;
                        }
                        var menu = '<ul class="dropdown-container">' +
                            '<li class="dropdown btn-group">' +
                            '<a href="/admin/customers/invoice?id=' + parseInt(oObj.aData.id) + '" ' +
                            'title="<?= addslashes($this->translate('View invoice')) ?>" class="btn"> ' +
                            '<?= addslashes($this->translate('View')) ?></a>' +
                            '<button type="button" class="btn dropdown-toggle" data-toggle="dropdown">' +
                            '<span class="caret"></span></button>' +
                            '<ul class="dropdown-menu">';
                        
                        if (oObj.aData.customerEmail || oObj.aData.customerSecondaryEmail) {
                            menu += '<li><a href="/admin/customers/email?id=' + parseInt(oObj.aData.customerId) + '"><?= addslashes($this->translate('Email')) ?></a></li>'
                        }

                        if (!parseInt(oObj.aData.paid) && !parseInt(oObj.aData.pending)) {

                            menu += '<li><a href="/admin/customers/invoice?a=payment&id=' + parseInt(oObj.aData.id) + '&type=<?= HHF_Domain_Transaction::TYPE_CASH ?>">' +
                                '<?= addslashes($this->translate('Mark Invoice as Paid by Cash')) ?>' +
                                '</a></li><li>' +
                                '<a href="/admin/customers/invoice?a=payment&id=' + parseInt(oObj.aData.id) + '&type=<?= HHF_Domain_Transaction::TYPE_CHEQUE ?>">' +
                                '<?= addslashes($this->translate('Mark Invoice as Paid by Cheque')) ?>' +
                                '</a></li>';
                        }

                        menu += '</ul></li></ul>';
                        
                        return menu;
                    }
                }
            ],
            "bSortClasses": false,
            "sAjaxSource": "<?= addslashes($this->Url()) ?>",
            "bServerSide": true,
            "sDom": '<"H"yaf<"clear">r<"right"ip>>t<"F"<"right"ip>>'
        })
        .delegate("tbody tr", "mouseover mouseout", function(e) {
            if (e.type == "mouseover") {
                $(e.currentTarget).addClass('hover');
            } else {
                $(e.currentTarget).removeClass('hover');
            }
        })
        .delegate(".delete", "click", function(){
            return window.confirm("<?= $this->translate('Are you sure you want to delete this invoice?  No turning back after an invoice delete.'); ?>");
        });
        
        new FixedHeader(table);
        
        $(".dataTables_year select").change(function(){
            window.location = '/admin/customers/invoices/year/' + $(this).val();
        });
        
        $('.dropdown-toggle').dropdown();
    });
</script>
<?php $this->placeholder('foot')->captureEnd() ?>

<h2>
    <span class="icon-menu icon-menu-members" style="float: left; margin: -10px 7px 0 0;"></span>
    <?= $this->translate('Customer Invoices') ?>
</h2>

<section class="container_12">
    <article class="grid_9">

        <?php if (!empty($this->messages)) { ?>
            <section class="info ui-widget ui-state-highlight ui-corner-all">
                <div>
                    <i class="fa fa-info-circle"></i>
                    <strong><?= $this->translate('Hey!'); ?></strong>
                    <?= $this->escape(implode('; ', $this->messages)); ?>
                </div>
            </section>
        <?php }?>

        <?php

         if (count($this->invoices)) { ?>
        
            <table id="invoices" class="display">
                <thead>
                    <tr>
                        <th
                            width="9%"
                            title="<?= $this->translate('Invoice ID') ?>">
                                <?= $this->translate('ID'); ?>
                        </th>
                        <th
                            width="30%"
                            title="<?= $this->translate('Customer') ?>">
                                <?= $this->translate('Customer'); ?>
                        </th>
                        <th
                            width="20%"
                            title="<?= $this->translate('Due Date') ?>">
                                <?= $this->translate('Due Date') ?>
                        </th>
                        <th
                            width="12%"
                            title="<?= $this->translate('Invoice Total') ?>">
                                <?= $this->translate('Total') ?>
                        </th>
                        <th
                            width="12%"
                            title="<?= $this->translate('Outstanding Amount') ?>">
                                <?= $this->translate('Due') ?>
                        </th>
                        <th
                            width="17%"
                            title="<?= $this->translate('Invoice Actions') ?>">
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->invoices as $invoice) { ?>
                        <tr>
                            <td>
                                <?= $this->escape($invoice['id']); ?>
                            </td>
                            <td>
                                <?=
                                    $this->escape(
                                        $invoice['customerLastName'] . ', ' 
                                        . $invoice['customerFirstName']
                                    );
                                ?>
                            </td>
                            <td>
                                <?= $this->escape($invoice['dueDate']->toString('yyyy-MM-dd')); ?>
                            </td>
                            <td>
                                <?= $this->currency($invoice['total']) ?>
                            </td>
                            <td>
                                <?= $this->currency($invoice['outstandingAmount']) ?>
                            </td>
                            <td class="right">
                                <ul class="dropdown-container">
                                    <li class="dropdown btn-group">
                                        <a href="/admin/customers/invoice?id=<?= (int) $invoice->id ?>"
                                           title="<?= $this->translate('View invoice') ?>"
                                           class="btn">
                                            <?= $this->translate('View') ?>
                                        </a>
                                        <button type="button"
                                                class="btn dropdown-toggle"
                                                data-toggle="dropdown">
                                            <span class="caret"></span>
                                        </button>

                                        <ul class="dropdown-menu">
                                            <?php if (!empty($invoice->customerEmail) || !empty($invoice->customerSecondaryEmail)) { ?>
                                            <li><a href="/admin/customers/email?id=<?= (int) $invoice->customerId ?>"><?= $this->translate('Email Customer') ?></a></li>
                                            <?php } ?>

                                            <?php if (!$invoice['paid'] && !$invoice['pending']) { ?>

                                            <li>
                                                <a href="/admin/customers/invoice?a=payment&id=<?= (int) $invoice['id'] ?>&type=<?= HHF_Domain_Transaction::TYPE_CASH ?>">
                                                    <?= $this->translate('Mark Invoice as Paid by Cash') ?>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="/admin/customers/invoice?a=payment&id=<?= (int) $invoice['id'] ?>&type=<?= HHF_Domain_Transaction::TYPE_CHEQUE ?>">
                                                    <?= $this->translate('Mark Invoice as Paid by Cheque') ?>
                                                </a>
                                            </li>

                                            <?php } ?>

                                        </ul>
                                    </li>
                                </ul>
                                
                            </td>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>

        <?php } else { ?>

            <p><?=
                $this->translate(
                    'You don\'t have any invoices yet.'
                ); ?></p>

        <?php } ?>
    </article>

    <?= $this->render('admin-sub-nav.phtml'); ?>
</section>
