<?php
    $title = $this->translate('Customer Invoice');

    $this->loader()->append('jquery_dropdown')
        ->append('jquery_ui_spinner');

    $this->headTitle($title);
?>

<?php $this->placeholder('foot')->captureStart() ?>
<script type="text/javascript">
    $(document).ready(function(){
        $('.dropdown-toggle').dropdown();

        $("body").delegate(".delete", "click", function(){
            return window.confirm("<?= $this->translate('Are you sure you want to delete this invoice?  No turning back after an invoice delete.'); ?>");
        });

        $(".dropdown-container").on('click', '#payment-cash', function(event) {
            event.preventDefault();

            var $this = $(this),
                horizontalPadding = 30,
                verticalPadding = 30;

            $("#type").val('<?= HHF_Domain_Transaction::TYPE_CASH ?>');

            $('#payment-apply').dialog({
                modal: true,
                title: $this.text(),
                autoOpen: true,
                width: 650,
                height: 200,
                resizable: true,
                autoResize: true,
                open: function() {
                    $(".amount").spinner({
                        max: '<?= $this->object['outstandingAmount'] ?>',
                        min: 0.01,
                        step: 0.01,
                        numberFormat: "n"
                    });
                }
            });

        }).on('click', '#payment-cheque', function(event) {
            event.preventDefault();

            var $this = $(this),
                horizontalPadding = 30,
                verticalPadding = 30;

            $("#type").val('<?= HHF_Domain_Transaction::TYPE_CHEQUE ?>');

            $('#payment-apply').dialog({
                modal: true,
                title: $this.text(),
                autoOpen: true,
                width: 650,
                height: 200,
                resizable: true,
                autoResize: true,
                open: function() {
                    $(".total").spinner({
                        max: '<?= $this->object['outstandingAmount'] ?>',
                        min: 0.01,
                        step: 0.01,
                        numberFormat: "n"
                    });
                }
            });

        });
    });
</script>
<?php $this->placeholder('foot')->captureEnd() ?>

<h2 style="display: inline-block; vertical-align: middle; margin-right: 15px; margin-bottom: 11px;">
    <span class="icon-menu icon-menu-members" style="float: left; margin: -10px 7px 0 0;"></span>
    <?= $title ?>
</h2>

<ul class="dropdown-container" style="display: inline-block; vertical-align: top;">
    <li class="dropdown btn-group">
        <a href="#"
            title="<?= $this->translate('Actions') ?>"
            class="btn dropdown-toggle"
            data-toggle="dropdown">
            <?= $this->translate('Actions') ?>
            <span class="caret"></span>
        </a>

        <ul class="dropdown-menu">
            <?php if (!$this->object->isEmpty() && !$this->object['paid'] && !$this->object['pending']) { ?>
            <li>
                <a href="/admin/customers/invoice?a=payment&id=<?= (int) $this->object->id ?>&type=<?= HHF_Domain_Transaction::TYPE_CASH ?>"
                    id="payment-cash">
                    <?= $this->translate('Mark Invoice as Paid by Cash') ?>
                </a>
            </li>
            <li>
                <a href="/admin/customers/invoice?a=payment&id=<?= (int) $this->object->id ?>&type=<?= HHF_Domain_Transaction::TYPE_CHEQUE ?>"
                    id="payment-cheque">
                    <?= $this->translate('Mark Invoice as Paid by Cheque') ?>
                </a>
            </li>
            <?php } ?>
            <?php if (!$this->object->isEmpty()) { ?>

            <li>
                <a href="/admin/customers/invoice?a=edit&id=<?= (int) $this->object->id ?>">
                    <?php if ($this->object['pending']) { ?>
                        <?= $this->translate('Review and Finalize Invoice') ?>
                    <?php } else { ?>
                        <?= $this->translate('Edit Invoice') ?>
                    <?php } ?>
                </a>
            </li>
                <?php if ($this->object['appliedToBalance'] && !$this->object['pending']) { ?>

                    <?php
                        $dueDate = new DateTime('@' . $this->object['dueDate']->getTimestamp());
                        $now = new DateTime();

                    ?>

                    <?php if ($dueDate > $now) { ?>
                        <li>
                            <a href="/admin/customers/invoice?a=unapply&id=<?= (int) $this->object->id ?>">
                                <?= $this->translate('Un-Apply From Balance') ?>
                            </a>
                        </li>
                    <?php } ?>

                <?php } ?>
            <?php } ?>
            <?php if (!empty($this->customer->email) || !empty($this->customer->secondaryEmail)) { ?>
            <li><a href="/admin/customers/email?id=<?= (int) $this->object->customerId ?>"><?= $this->translate('Email Customer') ?></a></li>
            <?php } ?>
        </ul>
    </li>
</ul>

<?php if (!empty($this->messages)) { ?>
    <section class="info ui-widget ui-state-highlight ui-corner-all">
        <div>
            <i class="fa fa-info-circle"></i>
            <strong><?= $this->translate('Hey!'); ?></strong>
            <?= $this->escape(implode('; ', $this->messages)); ?>
        </div>
    </section>
<?php } ?>

<?php if (!$this->object->isEmpty() && $this->object['pending']) { ?>
    <section class="info ui-widget ui-state-highlight ui-corner-all">
        <div>
            <i class="fa fa-info-circle"></i>
            <strong><?= $this->translate('Hey!'); ?></strong>
            <?= $this->translate(
                'This invoice requires that you <a href="%s">finalize it</a> before it is available for payment.',
                '/admin/customers/invoice?a=edit&id=' . (int) $this->object['id']
            ) ?>
        </div>
    </section>
<?php } ?>

<dl class="cmxlist">
    <dt>
        <?= $this->translate('Customer') ?>:
    </dt>
    <dd>
        <a href="/admin/customers/customer?id=<?= $this->customer->id ?>">
            <?php if (!empty($this->customer->firstName)) { ?>
                <?= $this->escape($this->customer->firstName) ?>,
            <?php } ?>
            <?= $this->escape($this->customer->lastName) ?>
        </a>
    </dd>

    <dt>
        <?= $this->translate('Invoice') ?>:
    </dt>

    <dd>
        <table style="width: 600px">
            <thead>
                <tr>
                    <th>
                        <?= $this->translate('Description') ?>
                    </th>
                    <th>
                        <?= $this->translate('Unit Price') ?>
                    </th>
                    <th>
                        <?= $this->translate('Quantity') ?>
                    </th>
                    <th>
                        <?= $this->translate('Total') ?>
                    </th>
                </tr>
            </thead>
            <tbody>
            <?php foreach ($this->object->getLines() as $line) { ?>
                <tr>
                    <td>
                        <?php if ($line['type'] == 'SHARE') { ?>
                        <a href="/admin/customers/subscription?id=<?= (int) $line['referenceId'] ?>">
                            <?= $this->escape($line['description']) ?>
                        </a>
                        <?php } else if ($line['type'] == 'ADDON') { ?>
                        <a href="/admin/customers/addon?id=<?= (int) $line['referenceId'] ?>">
                            <?= $this->escape($line['description']) ?>
                        </a>
                        <?php } else { ?>
                            <?= $this->escape($line['description']) ?>
                        <?php } ?>
                    </td>
                    <td><?= $this->escape($line['unitPrice']) ?></td>
                    <td><?= $this->escape($line['quantity']) ?></td>
                    <td><?= $this->escape($line['total']) ?></td>
                </tr>
            <?php } ?>
            </tbody>
            <tfoot>
                <tr style="border-top: 1px solid #444;">
                    <td colspan="3">
                        <?= $this->translate('Sub-Total') ?>
                    </td>
                    <td>
                        <?= $this->escape($this->object['subTotal']) ?>
                    </td>
                </tr>
                <tr>
                    <td colspan="3">
                        <?= $this->translate('Tax') ?>
                    </td>
                    <td>
                        <?= $this->escape($this->object['tax']) ?>
                    </td>
                </tr>
                <tr style="<?= ($this->object['total'] == $this->object['outstandingAmount']) ? 'font-weight: bold;' : '' ?>">
                    <td colspan="3">
                        <?= $this->translate(
                            'Total (Due %s)',
                            $this->escape($this->object->dueDate->get('yyyy-MM-dd'))
                        ) ?>
                    </td>
                    <td>
                        <?= $this->escape($this->object['total']) ?>
                    </td>
                </tr>

                <?php if ($this->object['total'] != $this->object['outstandingAmount']) { ?>
                <tr style="font-weight: bold;">
                    <td colspan="3">
                        <?= $this->translate('Outstanding Amount Due') ?>
                    </td>
                    <td>
                        <?= $this->escape($this->object['outstandingAmount']) ?>
                    </td>
                </tr>
                <?php } ?>
            </tfoot>
        </table>
    </dd>

    <?php if (!empty($this->object->message)) { ?>
    <dt>
        <?= $this->translate('Message') ?>:
    </dt>
    <dd>
        <?= $this->escape($this->object->message) ?>
    </dd>
    <?php } ?>

    <dt>
        <?= $this->translate('Applied to Balance') ?>:
    </dt>
    <dd>
        <?php
            if ($this->object->appliedToBalance) {
                echo $this->translate('Yes');
            } else {
                echo $this->translate('No');
            }
        ?>
    </dd>

    <dt>
        <?= $this->translate('Added') ?>:
    </dt>
    <dd>
        <time datetime="<?= $this->escape($this->object->addedDatetime->get(Zend_Date::ISO_8601)) ?>"
              title="<?= $this->escape($this->object->addedDatetime->get(Zend_Date::ISO_8601)) ?>" pubdate="pubdate">
            <?= $this->escape($this->object->addedDatetime->get('yyyy-MM-dd')) ?>
        </time>
    </dd>

    <dt>
        <?= $this->translate('Updated') ?>:
    </dt>
    <dd>
        <time datetime="<?= $this->escape($this->object->updatedDatetime->get(Zend_Date::ISO_8601)) ?>"
              title="<?= $this->escape($this->object->updatedDatetime->get(Zend_Date::ISO_8601)) ?>">
            <?= $this->escape($this->object->updatedDatetime->get('yyyy-MM-dd')) ?>
        </time>
    </dd>
</dl>

<form id="payment-apply"
      action="/admin/customers/invoice?a=payment&id=<?= (int) $this->object->id ?>"
      method="post"
      accept-charset="utf-8"
      class="cmxform large"
      style="display: none;">

    <input type="hidden" name="type" value="<?= HHF_Domain_Transaction::TYPE_CASH ?>" id="type" />

    <fieldset>
        <legend><?= $this->translate('Payment Amount') ?></legend>

        <p>
            <label
                for="total"
                title="<?= $this->translate(
                    'Please indicate the amount to pay against this invoice.'
                ) ?>">

                <?= $this->translate('Amount'); ?>:
            </label>

            <input
                id="total"
                type="text"
                name="total"
                value="<?= $this->object['outstandingAmount']  ?>"
                maxlength="20"
                class="number total"
                title="<?= $this->translate(
                    'Please indicate the amount to pay against this invoice.'
                ) ?>" />

            <?php if (!empty($this->errors['total'])) { ?>
                <label for="total" class="error">
                    <?= implode('; ', $this->errors['total']) ?>
                </label>
            <?php } ?>
        </p>

    </fieldset>


    <p>
        <button type="submit" class="submit fieldset-align ui-button ui-widget ui-corner-all ui-button-text-only ui-state-default">
            <span class="ui-button-text">
                <i class="fa fa-check"></i>
                <?= $this->translate('Save!'); ?>
            </span>
        </button>
    </p>
</form>
