<?php
    $this->headTitle($this->translate('Shares Purchase History'));

    $this->loader()->append('jquery_dataTables');
?>

<?php $this->placeholder('foot')->captureStart() ?>
<script type="text/javascript">
    $(document).ready(function(){

        var table = $("#shares").dataTable({
            "bJQueryUI": true,
            "bAutoWidth": false,
            "bDeferRender": true,
            "bLengthChange": false,
            "bProcessing": true,
            "iDisplayLength": 50,
            "iDeferLoading": <?= $this->foundRows ?>,
            "aaSorting": [[1, "desc"]],
            "aoColumns": [ 
                {
                    "sType": "text",
                    "mDataProp": "shareName",
                    "fnRender": function (oObj) {
                        if (!oObj.aData.hasOwnProperty("id")) {
                            return oObj.aData.shareName;
                        } else {
                            return oObj.aData.shareName.replace(/&/g,'&amp;')
                                    .replace(/</g,'&lt;')
                                    .replace(/>/g,'&gt;');
                        }
                    }
                },
                {
                    "sType": "int",
                    "mDataProp": "shareYear",
                    "fnRender": function (oObj) {
                        if (!oObj.aData.hasOwnProperty("id")) {
                            return oObj.aData.shareYear;
                        } else {
                            return parseInt(oObj.aData.shareYear);
                        }
                    }
                },
                {
                    "sType": "text",
                    "mDataProp": "locationName",
                    "fnRender": function (oObj) {
                        if (!oObj.aData.hasOwnProperty("id")) {
                            return oObj.aData.locationName;
                        } else {
                            return oObj.aData.locationName.replace(/&/g,'&amp;')
                                    .replace(/</g,'&lt;')
                                    .replace(/>/g,'&gt;');
                        }
                    }
                },
                {
                    "sType": "text",
                    "mDataProp": "quantity",
                    "fnRender": function (oObj) {
                        return parseInt(oObj.aData.quantity);
                    }
                },
                {
                    "sType": "text",
                    "mDataProp": "paidInFull",
                    "fnRender": function (oObj) {
                        if (!oObj.aData.hasOwnProperty("id")) {
                            return oObj.aData.paidInFull;
                        }
                        if (parseInt(oObj.aData.paidInFull) > 0) {
                            return '<?= addslashes($this->translate('Yes')) ?>';
                        } 
                        
                        if (parseInt(oObj.aData.paidInFull) < 0) {
                            return '<abbr title="' + ((parseInt(oObj.aData.paidInFull) * -1) + 1) + 
                                ' <?= addslashes($this->translate('Payments')) ?>" ' + 
                                'style="border-bottom: dotted 2px #444; cursor: help">' +
                                '<?= addslashes($this->translate('No')) ?></abbr>';
                        } else {
                            return '<?= addslashes($this->translate('No')) ?>';
                        }
                        
                        return '<?= addslashes($this->translate('No')) ?>';
                    }
                },
                { 
                    "bSortable": false,
                    "bSearchable": false,
                    "mDataProp": "_actions",
                    "sClass": "right",
                    "fnRender": function (oObj) {
                        if (!oObj.aData.hasOwnProperty("id")) {
                            return oObj.aData._actions;
                        }
                        var menu = '<ul class="dropdown-container">' +
                            '<li class="dropdown btn-group">' +
                            '<a href="/admin/customers/subscription?id=' + parseInt(oObj.aData.id) + '" ' +
                            'title="<?= addslashes($this->translate('View subscription')) ?>" class="btn"> ' +
                            '<?= addslashes($this->translate('View')) ?></a>' +
                            '<button type="button" class="btn dropdown-toggle" data-toggle="dropdown">' +
                            '<span class="caret"></span></button>' +
                            '<ul class="dropdown-menu">' +
                            '<li><a href="/admin/customers/subscription?a=edit&id=' + parseInt(oObj.aData.id) + '"' +
                            'title="<?= $this->translate('Edit subscription') ?>">' + 
                            '<?= addslashes($this->translate('Edit')) ?></a></li>';

                        menu += '<li class="divider"></li>' +
                            '<li><a class="delete" title="<?= addslashes($this->translate('Delete subscription')) ?>" ' +
                            'href="/admin/customers/customer?id=<?= (int) $this->customerId ?>&a=shareDelete&shareId=' + parseInt(oObj.aData.id) + '"><?= addslashes($this->translate('Delete')) ?></a></li>' +
                            '</ul></li></ul>';
                        
                        return menu;
                    }
                }
            ],
            "bSortClasses": false,
            "sAjaxSource": "<?= addslashes($this->Url()) ?>/d/1/cid/<?= $this->customerId ?>",
            "bServerSide": true,
            "sDom": '<"H"<"clear">r<"right"ip>>t<"F"<"right"ip>>'
        })
        .delegate("tbody tr", "mouseover mouseout", function(e) {
            if (e.type == "mouseover") {
                $(e.currentTarget).addClass('hover');
            } else {
                $(e.currentTarget).removeClass('hover');
            }
        }).delegate(".delete", "click", function(){
            return window.confirm("<?= $this->translate('Are you sure you want to delete this subscription?  No turning back after a subscription delete.'); ?>");
        });
    });
</script>
<?php $this->placeholder('foot')->captureEnd() ?>

<h2><?= $this->translate('Shares Purchase History') ?></h2>

<?php if (count($this->subscriptions)) { ?>

    <table id="shares" class="display" width="100%">
        <thead>
            <tr>
                <th
                    width="27%"
                    title="<?= $this->translate('Share') ?>">
                        <?= $this->translate('Share') ?>
                </th>
                <th
                    width="10%"
                    title="<?= $this->translate('Year') ?>">
                        <?= $this->translate('Year') ?>
                </th>
                <th
                    width="27%"
                    title="<?= $this->translate('Share Delivery Location') ?>">
                        <?= $this->translate('Location') ?>
                </th>
                <th
                    width="10%"
                    title="<?= $this->translate('Subscription Quantity') ?>">
                        <?= $this->translate('Qty') ?>
                </th>
                <th
                    width="10%"
                    title="<?= $this->translate('Paid In Full') ?>">
                        <?= $this->translate('Paid') ?>
                </th>
                <th
                    width="16%"
                    title="<?= $this->translate('Subscription Actions') ?>">
                </th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->subscriptions as $subscription) { ?>
                <tr>
                    <td>
                        <?= $this->escape($subscription->shareName); ?>
                    </td>
                    <td>
                        <?= (int) $subscription->shareYear; ?>
                    </td>
                    <td>
                        <?= $this->escape($subscription->locationName); ?>
                    </td>
                    <td>
                        <?= (int) $subscription->quantity ?>
                    </td>
                    <td>
                        <?php if ($subscription->paidInFull > 0) { ?>
                            <?= $this->translate('Yes') ?>
                        <?php } else { ?>
                            <?php if ($subscription->paidInFull < 0) { ?>
                            <abbr title="<?= $this->translate('%d Payments', (($subscription->paidInFull * -1) + 1)) ?>"
                                    style="border-bottom: dotted 2px #444; cursor: help">
                                <?= $this->translate('No') ?>
                            </abbr>
                            <?php } else { ?>
                                <?= $this->translate('No') ?>
                            <?php } ?>
                        <?php } ?>
                    </td>
                    <td class="right">
                        <ul class="dropdown-container">
                            <li class="dropdown btn-group">
                                <a href="/admin/customers/subscription?id=<?= (int) $subscription->id ?>"
                                    title="<?= $this->translate('View subscription') ?>"
                                    class="btn">
                                    <?= $this->translate('View') ?>
                                </a>
                                <button type="button"
                                        class="btn dropdown-toggle"
                                        data-toggle="dropdown">
                                    <span class="caret"></span>
                                </button>

                                <ul class="dropdown-menu">
                                    <li><a href="/admin/customers/subscription?a=edit&id=<?= (int) $subscription->id ?>"
                                        title="<?= $this->translate('Edit subscription') ?>">
                                            <?= $this->translate('Edit') ?>
                                        </a></li>
                                    <li class="divider"></li>
                                    <li><a class="delete" 
                                            title="<?= $this->translate('Delete subscription') ?>"
                                            href="/admin/customers/customer?id=<?= (int) $this->customerId ?>&a=shareDelete&shareId=<?= (int) $subscription->id ?>"><?= $this->translate('Delete') ?></a></li>
                                </ul>
                            </li>
                        </ul>

                    </td>
                </tr>
            <?php } ?>
        </tbody>
    </table>

    <?php 
        if ($this->embedded) { 
            echo $this->placeholder('foot');
        }
    ?>

<?php } else { ?>

    <p><?= $this->translate('This customer hasn\'t purchased any shares yet.'); ?></p>

<?php } ?>

