<?php
    $this->headTitle($this->translate('Products Purchase History'));

    $this->loader()->append('jquery_dataTables');
    
    $this->loadDatejs(Bootstrap::$locale);
?>

<?php $this->placeholder('foot')->captureStart() ?>
<script type="text/javascript">
    $(document).ready(function(){

        var table = $("#addons").dataTable({
            "bJQueryUI": true,
            "bAutoWidth": false,
            "bDeferRender": true,
            "bLengthChange": false,
            "bProcessing": true,
            "iDisplayLength": 50,
            "iDeferLoading": <?= $this->foundRows ?>,
            "aaSorting": [[0, "asc"]],
            "aoColumns": [ 
                {
                    "sType": "string",
                    "mDataProp": "week",
                    "fnRender": function (oObj) {
                        if (!oObj.aData.hasOwnProperty("id")) {
                            return oObj.aData.week;
                        } else {
                            var weekArray = oObj.aData.week.split("W");
                            var week = weekArray[1],
                                year = weekArray[0],
                                date = new Date(),
                                range = "";
                                
                                date.setYear(year);
                                date.setWeek(week);
                                
                                if (date.getDay() > 1) {
                                    date.setDate(date.getDate() - (date.getDay() - 1));
                                } else if (date.getDay() < 1) {
                                    date.setDate(date.getDate() + 1);
                                }
                                
                                range = date.toString("yyyy-MM-dd") + " - ";
                                
                                date.setDate(date.getDate() + 6);
                                
                                range += date.toString("yyyy-MM-dd");
                            
                            return range;
                        }
                    }
                },
                {
                    "sType": "text",
                    "mDataProp": "addonName",
                    "fnRender": function (oObj) {
                        if (!oObj.aData.hasOwnProperty("id")) {
                            return oObj.aData.addonName;
                        } else {
                            return oObj.aData.addonName.replace(/&/g,'&amp;')
                                    .replace(/</g,'&lt;')
                                    .replace(/>/g,'&gt;');
                        }
                    }
                },
                {
                    "sType": "text",
                    "mDataProp": "quantity",
                    "fnRender": function (oObj) {
                        return parseInt(oObj.aData.quantity);
                    }
                },
                {
                    "sType": "text",
                    "mDataProp": "paidInFull",
                    "fnRender": function (oObj) {
                        if (!oObj.aData.hasOwnProperty("id")) {
                            return oObj.aData.paidInFull;
                        }
                        if (parseInt(oObj.aData.paidInFull) == 1) {
                            return '<?= addslashes($this->translate('Yes')) ?>';
                        } 
                        return '<?= addslashes($this->translate('No')) ?>';
                    }
                },
                { 
                    "bSortable": false,
                    "bSearchable": false,
                    "mDataProp": "_actions",
                    "sClass": "right",
                    "fnRender": function (oObj) {
                        if (!oObj.aData.hasOwnProperty("id")) {
                            return oObj.aData._actions;
                        }
                        var menu = '<ul class="dropdown-container">' +
                            '<li class="dropdown btn-group">' +
                            '<a href="/admin/customers/addon?id=' + parseInt(oObj.aData.id) + '" ' +
                            'title="<?= addslashes($this->translate('View purchased product')) ?>" class="btn"> ' +
                            '<?= addslashes($this->translate('View')) ?></a>' +
                            '<button type="button" class="btn dropdown-toggle" data-toggle="dropdown">' +
                            '<span class="caret"></span></button>' +
                            '<ul class="dropdown-menu">';

                        menu += '<li class="divider"></li>' +
                            '<li><a class="delete" title="<?= addslashes($this->translate('Delete purchased product')) ?>" ' +
                            'href="/admin/customers/customer?id=<?= (int) $this->customerId ?>&a=addonDelete&addonId=' + parseInt(oObj.aData.id) + '"><?= addslashes($this->translate('Delete')) ?></a></li>' +
                            '</ul></li></ul>';
                        
                        return menu;
                    }
                }
            ],
            "bSortClasses": false,
            "sAjaxSource": "<?= addslashes($this->Url()) ?>/d/1/cid/<?= $this->customerId ?>",
            "bServerSide": true,
            "sDom": '<"H"<"clear">r<"right"ip>>t<"F"<"right"ip>>'
        })
        .delegate("tbody tr", "mouseover mouseout", function(e) {
            if (e.type == "mouseover") {
                $(e.currentTarget).addClass('hover');
            } else {
                $(e.currentTarget).removeClass('hover');
            }
        })
        .delegate(".delete", "click", function(){
            return window.confirm("<?= $this->translate('Are you sure you want to delete this purchased product?  No turning back after a purchase product delete.'); ?>");
        });
    });
</script>
<?php $this->placeholder('foot')->captureEnd() ?>

<h2><?= $this->translate('Product Purchase History') ?></h2>

<?php if (count($this->addons)) { ?>

    <table id="addons" class="display" width="100%">
        <thead>
            <tr>
                <th
                    width="29%"
                    title="<?= $this->translate('Delivery week purchased') ?>">
                        <?= $this->translate('Week'); ?>
                </th>
                <th
                    width="35%"
                    title="<?= $this->translate('Product') ?>">
                        <?= $this->translate('Product') ?>
                </th>
                <th
                    width="10%"
                    title="<?= $this->translate('Purchased Quantity') ?>">
                        <?= $this->translate('Qty') ?>
                </th>
                <th
                    width="10%"
                    title="<?= $this->translate('Paid In Full') ?>">
                        <?= $this->translate('Paid') ?>
                </th>
                <th
                    width="16%"
                    title="<?= $this->translate('Product Actions') ?>">
                </th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->addons as $addon) { ?>
                <tr>
                    <td>
                        <?php
                            list($year , $week) = explode('W', $addon->week);

                            $date = new Zend_Date();
                            $date->setYear($year);
                            $date->setWeek($week);
                            $date->set(1, Zend_Date::WEEKDAY_8601);

                            $range = $date->toString('yyyy-MM-dd') . ' - ';
                            $date->set(7, Zend_Date::WEEKDAY_8601);
                            $range .= $date->toString('yyyy-MM-dd');
                        ?>
                        <?= $this->escape($range); ?>
                    </td>
                    <td>
                        <?= $this->escape($addon->addonName); ?>
                    </td>
                    <td>
                        <?= (int) $addon->quantity ?>
                    </td>
                    <td>
                        <?php if ($addon->paidInFull) { ?>
                            <?= $this->translate('Yes') ?>
                        <?php } else { ?>
                            <?= $this->translate('No') ?>
                        <?php } ?>
                    </td>
                    <td class="right">
                        <ul class="dropdown-container">
                            <li class="dropdown btn-group">
                                <a href="/admin/customers/addon?id=<?= (int) $addon->id ?>"
                                    title="<?= $this->translate('Edit product purchased') ?>"
                                    class="btn">
                                    <?= $this->translate('View') ?>
                                </a>
                                <button type="button"
                                        class="btn dropdown-toggle"
                                        data-toggle="dropdown">
                                    <span class="caret"></span>
                                </button>

                                <ul class="dropdown-menu">
                                    <li class="divider"></li>
                                    <li><a class="delete" 
                                            title="<?= $this->translate('Delete product purchased') ?>"
                                            href="/admin/customers/customer?id=<?= (int) $this->customerId ?>&a=addonDelete&addonId=<?= (int) $addon->id ?>"><?= $this->translate('Delete') ?></a></li>
                                </ul>
                            </li>
                        </ul>

                    </td>
                </tr>
            <?php } ?>
        </tbody>
    </table>

    <?php 
        if ($this->embedded) { 
            echo $this->placeholder('foot');
        }
    ?>

<?php } else { ?>

    <p><?= $this->translate('This customer hasn\'t purchased any products yet.'); ?></p>

<?php } ?>

