<?php
    $this->headTitle($this->translate('Subscritions'));

    $this->loader()->append('jquery_dataTables')
        ->append('jquery_dropdown');

    Bootstrap::getZendCurrency();
?>

<?php $this->placeholder('foot')->captureStart() ?>
<script type="text/javascript">
    $(document).ready(function(){

        $.fn.dataTableExt.aoFeatures.push({
            "fnInit": function(oSettings) {
                return $('<ul class="dataTables_add dropdown-container"><li class="dropdown btn-group">' +
                    '<a href="/admin/customers/subscription" title="<?= $this->translate('Add new share subscription') ?>" class="btn">' +
                    '<?= addslashes($this->translate('Add')) ?></a>' +
                    '<button type="button" class="btn dropdown-toggle" data-toggle="dropdown">' +
                    '<span class="caret"></span></button>' +
                    '<ul class="dropdown-menu"><li><a href="/admin/customers/subscriptions/format/csv/year/<?= $this->year ?>" title="<?= $this->translate('Export to a spreadsheet program') ?>">' +
                    '<?= $this->translate('Export to CSV') ?></a></li></ul></li></ul>')[0];
            },
            "cFeature": "a",
            "sFeature": "Add"
        });
        
        $.fn.dataTableExt.aoFeatures.push({
            "fnInit": function(oSettings) {
                return $(
                    '<form class="dataTables_year" action="/admin/customers/subscriptions" method="get" style="float: left; padding-right: 10px">' +
                    <?php if (count($this->years) > 1) { ?>
                        '<label for="year"><?= addslashes($this->translate('Year')); ?>: </label>' +
                        '<?=
                            addslashes(str_replace("\n", '', $this->formSelect(
                                'year',
                                $this->year,
                                array(),
                                $this->years
                            )));
                        ?>' +
                    <?php } ?>
                    '</form> '
                )[0];
            },
            "cFeature": "y",
            "sFeature": "Year"
        });
        
        var table = $("#subscriptions").dataTable({
            "bJQueryUI": true,
            "bAutoWidth": false,
            "bDeferRender": true,
            "bLengthChange": false,
            "bProcessing": true,
            "iDisplayLength": 50,
            "iDeferLoading": <?= $this->foundRows ?>,
            "aaSorting": [[0, "asc"]],
            "aoColumns": [ 
                {
                    "sType": "text",
                    "mDataProp": "customer",
                    "fnRender": function (oObj) {
                        if (!oObj.aData.hasOwnProperty("id")) {
                            return oObj.aData.customer;
                        } else {
                            return oObj.aData.customerLastName
                                .replace(/&/g,'&amp;')
                                .replace(/</g,'&lt;')
                                .replace(/>/g,'&gt;') + ", " +
                                oObj.aData.customerFirstName
                                .replace(/&/g,'&amp;')
                                .replace(/</g,'&lt;')
                                .replace(/>/g,'&gt;');
                        }
                    }
                },
                {
                    "sType": "text",
                    "mDataProp": "shareName",
                    "fnRender": function (oObj) {
                        if (!oObj.aData.hasOwnProperty("id")) {
                            return oObj.aData.shareName;
                        } else {
                            return oObj.aData.shareName.replace(/&/g,'&amp;')
                                    .replace(/</g,'&lt;')
                                    .replace(/>/g,'&gt;');
                        }
                    }
                },
                {
                    "sType": "text",
                    "mDataProp": "locationName",
                    "fnRender": function (oObj) {
                        if (!oObj.aData.hasOwnProperty("id")) {
                            return oObj.aData.locationName;
                        } else {
                            return oObj.aData.locationName.replace(/&/g,'&amp;')
                                    .replace(/</g,'&lt;')
                                    .replace(/>/g,'&gt;');
                        }
                    }
                },
                {
                    "sType": "text",
                    "mDataProp": "quantity",
                    "fnRender": function (oObj) {
                        return parseInt(oObj.aData.quantity);
                    }
                },
                {
                    "sType": "text",
                    "mDataProp": "paidInFull",
                    "fnRender": function (oObj) {
                        if (!oObj.aData.hasOwnProperty("id")) {
                            return oObj.aData.paidInFull;
                        }
                        if (parseInt(oObj.aData.paidInFull) > 0) {
                            return '<?= addslashes($this->translate('Yes')) ?>';
                        } 
                        
                        if (parseInt(oObj.aData.paidInFull) < 0) {
                            return '<abbr title="' + ((parseInt(oObj.aData.paidInFull) * -1) + 1) + 
                                ' <?= addslashes($this->translate('Payments')) ?>" ' + 
                                'style="border-bottom: dotted 2px #444; cursor: help">' +
                                '<?= addslashes($this->translate('No')) ?></abbr>';
                        } else {
                            return '<?= addslashes($this->translate('No')) ?>';
                        }
                        
                        return '<?= addslashes($this->translate('No')) ?>';
                    }
                },
                { 
                    "bSortable": false,
                    "bSearchable": false,
                    "mDataProp": "_actions",
                    "sClass": "right",
                    "fnRender": function (oObj) {
                        if (!oObj.aData.hasOwnProperty("id")) {
                            return oObj.aData._actions;
                        }
                        var menu = '<ul class="dropdown-container">' +
                            '<li class="dropdown btn-group">' +
                            '<a href="/admin/customers/subscription?id=' + parseInt(oObj.aData.id) + '" ' +
                            'title="<?= addslashes($this->translate('View subscription')) ?>" class="btn"> ' +
                            '<?= addslashes($this->translate('View')) ?></a>' +
                            '<button type="button" class="btn dropdown-toggle" data-toggle="dropdown">' +
                            '<span class="caret"></span></button>' +
                            '<ul class="dropdown-menu">';
                        
                        if (oObj.aData.customerEmail || oObj.aData.customerSecondaryEmail) {
                            menu += '<li><a href="/admin/customers/email?id=' + parseInt(oObj.aData.customerId) + '"><?= addslashes($this->translate('Email Customer')) ?></a></li>'
                        }

                        menu += '<li class="divider"></li>' +
                            '<li><a class="delete" title="<?= addslashes($this->translate('Delete subscription')) ?>" ' +
                            'href="/admin/customers/subscription?a=delete&id=' + parseInt(oObj.aData.id) + '"><?= addslashes($this->translate('Delete')) ?></a></li>' +
                            '</ul></li></ul>';
                        
                        return menu;
                    }
                }
            ],
            "bSortClasses": false,
            "sAjaxSource": "<?= addslashes($this->Url()) ?>",
            "bServerSide": true,
            "sDom": '<"H"yaf<"clear">r<"right"ip>>t<"F"<"right"ip>>'
        })
        .delegate("tbody tr", "mouseover mouseout", function(e) {
            if (e.type == "mouseover") {
                $(e.currentTarget).addClass('hover');
            } else {
                $(e.currentTarget).removeClass('hover');
            }
        })
        .delegate(".delete", "click", function(){
            return window.confirm("<?= $this->translate('Are you sure you want to delete this subscription?  No turning back after a subscription delete.'); ?>");
        });
        
        new FixedHeader(table);
        
        $(".dataTables_year select").change(function(){
            window.location = '/admin/customers/subscriptions/year/' + $(this).val();
        });
        
        $('.dropdown-toggle').dropdown();
    });
</script>
<?php $this->placeholder('foot')->captureEnd() ?>

<h2>
    <span class="icon-menu icon-menu-members" style="float: left; margin: -10px 7px 0 0;"></span>
    <?= $this->translate('Customer Share Subscriptions') ?>
</h2>

<section class="container_12">
    <article class="grid_9">

        <?php if (!empty($this->messages)) { ?>
            <section class="info ui-widget ui-state-highlight ui-corner-all">
                <div>
                    <i class="fa fa-info-circle"></i>
                    <strong><?= $this->translate('Hey!'); ?></strong>
                    <?= $this->escape(implode('; ', $this->messages)); ?>
                </div>
            </section>
        <?php } ?>

        <?php if (count($this->subscriptions)) { ?>
        
            <table id="subscriptions" class="display">
                <thead>
                    <tr>
                        <th
                            width="23%"
                            title="<?= $this->translate('Customer') ?>">
                                <?= $this->translate('Customer'); ?>
                        </th>
                        <th
                            width="22%"
                            title="<?= $this->translate('Share') ?>">
                                <?= $this->translate('Share') ?>
                        </th>
                        <th
                            width="22%"
                            title="<?= $this->translate('Share Delivery Location') ?>">
                                <?= $this->translate('Location') ?>
                        </th>
                        <th
                            width="8%"
                            title="<?= $this->translate('Subscription Quantity') ?>">
                                <?= $this->translate('Qty') ?>
                        </th>
                        <th
                            width="9%"
                            title="<?= $this->translate('Paid In Full') ?>">
                                <?= $this->translate('Paid') ?>
                        </th>
                        <th
                            width="16%"
                            title="<?= $this->translate('Subscription Actions') ?>">
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->subscriptions as $subscription) { ?>
                        <tr>
                            <td>
                                <?php 
                                    echo $this->escape(
                                        $subscription->customerLastName . ', ' 
                                        . $subscription->customerFirstName
                                    );
                                ?>
                            </td>
                            <td>
                                <?= $this->escape($subscription->shareName); ?>
                            </td>
                            <td>
                                <?= $this->escape($subscription->locationName); ?>
                            </td>
                            <td>
                                <?= (int) $subscription->quantity ?>
                            </td>
                            <td>
                                <?php if ($subscription->paidInFull > 0) { ?>
                                    <?= $this->translate('Yes') ?>
                                <?php } else { ?>
                                    <?php if ($subscription->paidInFull < 0) { ?>
                                    <abbr title="<?= $this->translate('%d Payments', (($subscription->paidInFull * -1) + 1)) ?>"
                                          style="border-bottom: dotted 2px #444; cursor: help">
                                        <?= $this->translate('No') ?>
                                    </abbr>
                                    <?php } else { ?>
                                        <?= $this->translate('No') ?>
                                    <?php } ?>
                                <?php } ?>
                            </td>
                            <td class="right">
                                <ul class="dropdown-container">
                                    <li class="dropdown btn-group">
                                        <a href="/admin/customers/subscription?id=<?= (int) $subscription->id ?>"
                                           title="<?= $this->translate('View subscription') ?>"
                                           class="btn">
                                            <?= $this->translate('View') ?>
                                        </a>
                                        <button type="button"
                                                class="btn dropdown-toggle"
                                                data-toggle="dropdown">
                                            <span class="caret"></span>
                                        </button>

                                        <ul class="dropdown-menu">
                                            <li><a href="/admin/customers/subscription?a=edit&id=<?= (int) $subscription->id ?>"
                                                title="<?= $this->translate('Edit subscription') ?>">
                                                    <?= $this->translate('Edit') ?>
                                                </a></li>
                                            <?php if (!empty($subscription->customerEmail) || !empty($subscription->customerSecondaryEmail)) { ?>
                                            <li><a href="/admin/customers/email?id=<?= (int) $subscription->customerId ?>"><?= $this->translate('Email Customer') ?></a></li>
                                            <?php } ?>
                                            <li class="divider"></li>
                                            <li><a class="delete" 
                                                   title="<?= $this->translate('Delete subscription') ?>"
                                                   href="/admin/customers/subscription?a=delete&id=<?= (int) $subscription->id ?>"><?= $this->translate('Delete') ?></a></li>
                                        </ul>
                                    </li>
                                </ul>
                                
                            </td>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>

        <?php } else { ?>

            <p><?=
                $this->translate(
                    'You haven\'t added any subscriptions yet.  <a href="%s">Let\'s add one now.</a>',
                    '/admin/customers/subscription'
                ); ?></p>

        <?php } ?>
    </article>

    <?= $this->render('admin-sub-nav.phtml'); ?>
</section>
