<?php
    $this->headTitle($this->translate('Admin Users'));

    $this->loader()->append('jquery_dataTables');
    
    $primary = $this->farm->isPrimaryFarmer($this->farmer);
?>

<?php $this->placeholder('foot')->captureStart() ?>
<script type="text/javascript">
    $(document).ready(function(){

        $.fn.dataTableExt.aoFeatures.push({
            "fnInit": function(oSettings) {
                <?php if ($primary) { ?>
                return $('<ul class="dataTables_add dropdown-container"><li class="dropdown btn-group">' +
                    '<a href="/admin/default/options_user" title="<?= $this->translate('Add user') ?>" class="btn">' +
                    '<?= addslashes($this->translate('Add')) ?></a></li></ul>')[0];
                <?php } else { ?>
                    return '';
                <?php } ?>
            },
            "cFeature": "a",
            "sFeature": "Add"
        });
        
        var table = $("#users").dataTable({
            "bJQueryUI": true,
            "bAutoWidth": false,
            "bDeferRender": true,
            "bLengthChange": false,
            "bProcessing": true,
            "iDisplayLength": 50,
            "iDeferLoading": <?= $this->foundRows ?>,
            "aaSorting": [[2, "asc"]],
            "aoColumns": [ 
                {
                    "sType": "html",
                    "mDataProp": "firstName",
                    "fnRender": function (oObj) {
                        if (!oObj.aData.hasOwnProperty("id")) {
                            return oObj.aData.firstName;
                        } else {
                            return '<a href="/admin/default/options_user?id=' + 
                                parseInt(oObj.aData.id) + '">' + oObj.aData.firstName
                                    .replace(/&/g,'&amp;')
                                    .replace(/</g,'&lt;')
                                    .replace(/>/g,'&gt;') + '</a>';
                        }
                    }
                },
                {
                    "sType": "html",
                    "mDataProp": "lastName",
                    "fnRender": function (oObj) {
                        if (!oObj.aData.hasOwnProperty("id")) {
                            return oObj.aData.lastName;
                        } else {
                            return '<a href="/admin/default/options_user?id=' + 
                                parseInt(oObj.aData.id) + '">' + oObj.aData.lastName
                                    .replace(/&/g,'&amp;')
                                    .replace(/</g,'&lt;')
                                    .replace(/>/g,'&gt;') + '</a>';
                        }
                    }
                },
                {
                    "sType": "html",
                    "mDataProp": "userName",
                    "fnRender": function(oObj) {
                        if (!oObj.aData.hasOwnProperty("id")) {
                            return oObj.aData.userName;
                        } else {
                            return '<a href="/admin/default/options_user?id=' + 
                                parseInt(oObj.aData.id) + '">' + oObj.aData.userName
                                    .replace(/&/g,'&amp;')
                                    .replace(/</g,'&lt;')
                                    .replace(/>/g,'&gt;') + '</a>';
                        }
                    }
                },
                {
                    "sType": "date",
                    "mDataProp": "addedDatetime",
                    "fnRender": function(oObj) {
                        return oObj.aData.addedDatetime;
                    }
                },
                { 
                    "bSortable": false,
                    "bSearchable": false,
                    "mDataProp": "_actions",
                    "sClass": "right",
                    "fnRender": function (oObj) {
                        if (!oObj.aData.hasOwnProperty("id")) {
                            return oObj.aData._actions;
                        }
                        return '<form action="/admin/default/options_user" method="get">' +
                            '<input type="hidden" name="id" value="' + parseInt(oObj.aData.id) + '" />' +
                            '<button title="<?= $this->translate('Edit') ?>"' +
                            'type="submit"' +
                            'class="ui-button ui-widget ui-corner-all ui-button-icon-only ui-state-default">' +
                            '<span class="ui-button-icon-primary ui-icon ui-icon-pencil"></span>' +
                            '<span class="ui-button-text"><?= $this->translate('Edit') ?></span>' +
                            '</button></form>' +
                            '<form action="/admin/default/options_user" method="post" class="delete" style="padding-top: 5px">' +
                            '<input type="hidden" name="id" value="' + parseInt(oObj.aData.id)+ '" />' +
                            '<input type="hidden" name="a" value="delete" />' +
                            '<button type="submit"' +
                            'title="<?= $this->translate('Delete') ?>"' +
                            'class="ui-button ui-widget ui-corner-all ui-button-icon-only ui-state-default">' +
                            '<span class="ui-button-icon-primary ui-icon ui-icon-trash"></span>' +
                            '<span class="ui-button-text"><?= $this->translate('Delete') ?></span>' +
                            '</button></form>';
                    }
                }
            ],
            "bSortClasses": false,
            "sAjaxSource": "<?= addslashes($this->Url()) ?>",
            "bServerSide": true,
            "sDom": '<"H"af<"clear">r<"right"ip>>t<"F"<"right"ip>>'
        })
        .delegate("tbody tr", "mouseover mouseout", function(e) {
            if (e.type == "mouseover") {
                $(e.currentTarget).addClass('hover');
            } else {
                $(e.currentTarget).removeClass('hover');
            }
        })
        .delegate(".delete", "submit", function(){
            return window.confirm("<?= $this->translate('Are you sure you want to delete this user?  No turning back after a user delete.'); ?>");
        })
        .fnSetFilteringDelay(1000);
        
	new FixedHeader(table);
    });
</script>
<?php $this->placeholder('foot')->captureEnd() ?>

<h2>
    <span class="icon-menu icon-menu-users" style="float: left; margin: -10px 7px 0 0;"></span>
    <?= $this->translate('Administrative Users') ?>
</h2>

<section class="container_12">
    <article class="grid_11">

        <?php if (!empty($this->messages)) { ?>
            <section class="info ui-widget ui-state-highlight ui-corner-all">
                <div>
                    <i class="fa fa-info-circle"></i>
                    <strong><?= $this->translate('Hey!'); ?></strong>
                    <?= $this->escape(implode('; ', $this->messages)); ?>
                </div>
            </section>
        <?php } ?>

        <?php if (count($this->users)) { ?>
        
            <table id="users" class="display">
                <thead>
                    <tr>
                        <th
                            width="25%"
                            title="<?= $this->translate('User First Name') ?>">
                                <?= $this->translate('First Name'); ?>
                        </th>
                        <th
                            width="25%"
                            title="<?= $this->translate('User Last Name') ?>">
                                <?= $this->translate('Last Name') ?>
                        </th>
                        <th
                            width="25%"
                            title="<?= $this->translate('User Name') ?>">
                                <?= $this->translate('User Name') ?>
                        </th>
                        <th
                            width="22%"
                            title="<?= $this->translate('Date User Added') ?>">
                                <?= $this->translate('Added') ?>
                        </th>
                        <th
                            width="10%"
                            title="<?= $this->translate('User Actions') ?>">
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->users as $user) { ?>
                        <tr>
                            <td>
                                <?php if ($primary || $this->farmer->id == $user->id) { ?>
                                <a href="/admin/default/options_user?id=<?= (int) $user->id ?>">
                                    <?= $this->escape($user->firstName); ?>
                                </a>
                                <?php } else { ?>
                                    <?= $this->escape($user->firstName); ?>
                                <?php } ?>
                            </td>
                            <td>
                                <?php if ($primary || $this->farmer->id == $user->id) { ?>
                                <a href="/admin/default/options_user?id=<?= (int) $user->id ?>">
                                    <?= $this->escape($user->lastName); ?>
                                </a>
                                <?php } else { ?>
                                    <?= $this->escape($user->lastName); ?>
                                <?php } ?>
                            </td>
                            <td>
                                <?php if ($primary || $this->farmer->id == $user->id) { ?>
                                <a href="/admin/default/options_user?id=<?= (int) $user->id ?>">
                                    <?= $this->escape($user->userName); ?>
                                </a>
                                <?php } else { ?>
                                    <?= $this->escape($user->userName); ?>
                                <?php } ?>
                            </td>
                            <td>
                                <?= $this->escape($user->addedDatetime->toString(Zend_Date::DATE_MEDIUM)); ?>
                            </td>
                            <td class="right">
                                <?php if ($primary || $this->farmer->id == $user->id) { ?>
                                <form action="/admin/default/options_user" method="get">
                                    <input type="hidden" name="id" value="<?= (int) $user->id ?>" />
                                    <button
                                        title="<?= $this->translate('Edit administrative user') ?>"
                                        type="submit"
                                        class="ui-button ui-widget ui-corner-all ui-button-icon-only ui-state-default">
                                        <span class="ui-button-icon-primary ui-icon ui-icon-pencil"></span>
                                        <span class="ui-button-text"><?= $this->translate('Edit') ?></span>
                                    </button>
                                </form>
                                <?php } ?>

                                <?php if ($primary && !$this->farm->isPrimaryFarmer($user)) { ?>
                                <form action="/admin/default/options_user" method="post" class="delete">
                                    <input type="hidden" name="id" value="<?= (int) $user->id ?>" />
                                    <input type="hidden" name="a" value="delete" />
                                    <button
                                        type="submit"
                                        title="<?= $this->translate('Delete administrative user') ?>"
                                        class="ui-button ui-widget ui-corner-all ui-button-icon-only ui-state-default">
                                        <span class="ui-button-icon-primary ui-icon ui-icon-trash"></span>
                                        <span class="ui-button-text"><?= $this->translate('Delete') ?></span>
                                    </button>
                                </form>
                                <?php } ?>
                            </td>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>

        <?php } else { ?>

            <p><?=
                $this->translate(
                    'You haven\'t added any users yet.  <a href="%s">Let\'s add one now.</a>',
                    '/admin/default/options_user'
                ); ?></p>

        <?php } ?>
    </article>
</section>
