<?php
    $title = $this->translate('Edit Farm Info');

    $this->headTitle($title);

    $this->loader()->append('jquery_validate')
        ->append('hhf_modules_default_admin_options_farm');
?>

<?php $this->placeholder('foot')->captureStart() ?>
<script type="text/javascript">
    hhf.modules.default.admin.options.farm.init({
        city: {
            url: "<?= addslashes($this->Url()) ?>",
            country: '<?= addslashes($this->getFormValue('country', 'farm')) ?>'
        }
    });
</script>
<?php $this->placeholder('foot')->captureEnd() ?>

<h2>
    <span class="icon-menu icon-menu-dashboard" style="float: left; margin: -10px 7px 0 0;"></span>
    <?= $title ?>
</h2>

<section class="container_12">
    <article class="grid_11">

        <form id="farm" 
              action="/admin/default/options_farm?<?= http_build_query($_GET) ?>" 
              method="post" 
              accept-charset="utf-8" 
              class="cmxform large">

            <input type="hidden"
                   name="farm[country]"
                   value="<?= $this->getFormValue('country', 'farm'); ?>" />
            
            <section id="formError" 
                     class="error ui-widget ui-state-error ui-corner-all" 
                     style="<?= (!empty($this->errors)) ? '' : 'display:none;' ?>">
                <div>
                    <i class="fa fa-exclamation-triangle"></i>
                    <strong><?= $this->translate('Oh No!'); ?></strong>
                    <?= $this->translate('Something is not right with what you entered.  Check below for hints on how to fix things up.'); ?>
                </div>
            </section>            

            <fieldset>
                <legend><?= $this->translate('Farm Mailing Address') ?></legend>

                <p>
                    <label for="farm_name" class="required" title="<?= $this->translate('Please enter the name of your farm'); ?>">
                        <?= $this->translate('Name'); ?>:
                        <abbr title="<?= $this->translate('This field is required'); ?>">*</abbr>
                    </label>
                    <input
                        id="farm_name"
                        name="farm[name]"
                        type="text"
                        title="<?= $this->translate('Please enter the name of your farm'); ?>"
                        value="<?= $this->getFormValue('name', 'farm'); ?>"
                        class="required"
                        maxlength="255" />

                    <?php if (!empty($this->errors['farm']['name'])) { ?>
                    <label for="farm_name" class="error">
                        <?= implode('; ', $this->errors['farm']['name']) ?>
                    </label>
                    <?php } ?>
                </p>

                <p>
                    <label for="farm_address" class="required" title="<?= $this->translate('Please enter the address of your farm'); ?>">
                        <?= $this->translate('Address'); ?>:
                        <abbr title="<?= $this->translate('This field is required'); ?>">*</abbr>
                    </label>
                    <input
                        id="farm_address"
                        name="farm[address]"
                        type="text"
                        title="<?= $this->translate('Please enter the address of your farm'); ?>"
                        value="<?= $this->getFormValue('address', 'farm'); ?>"
                        class="required"
                        maxlength="100" />

                    <?php if (!empty($this->errors['farm']['address'])) { ?>
                    <label for="farm_address" class="error">
                        <?= implode('; ', $this->errors['farm']['address']) ?>
                    </label>
                    <?php } ?>
                </p>

                <p>
                    <label for="farm_address2" title="<?= $this->translate('Please enter the address of your farm'); ?>">
                        <?= $this->translate('Address'); ?>:
                    </label>
                    <input
                        id="farm_address2"
                        name="farm[address2]"
                        type="text"
                        title="<?= $this->translate('Please enter the address of your farm'); ?>"
                        value="<?= $this->getFormValue('address2', 'farm'); ?>"
                        class=""
                        maxlength="100" />

                    <?php if (!empty($this->errors['farm']['address2'])) { ?>
                    <label for="farm_address2" class="error">
                        <?= implode('; ', $this->errors['farm']['address2']) ?>
                    </label>
                    <?php } ?>
                </p>

                <p>
                    <label for="farm_city" class="required" title="<?= $this->translate('Please enter the town that your farm is located in'); ?>">
                        <?= $this->translate('Town'); ?>:
                        <abbr title="<?= $this->translate('This field is required'); ?>">*</abbr>
                    </label>
                    <input
                        id="farm_city"
                        name="farm[city]"
                        type="text"
                        title="<?= $this->translate('Please enter the town that your farm is located in'); ?>"
                        value="<?= $this->getFormValue('city', 'farm'); ?>"
                        class="required"
                        maxlength="100" />

                    <?php if (!empty($this->errors['farm']['city'])) { ?>
                    <label for="farm_city" class="error">
                        <?= implode('; ', $this->errors['farm']['city']) ?>
                    </label>
                    <?php } ?>
                </p>

                <p>
                    <label for="farm_state" class="required" title="<?= $this->translate('Please enter the state your farm is located in'); ?>">
                        <?= $this->translate('State'); ?>:
                        <abbr title="<?= $this->translate('This field is required'); ?>">*</abbr>
                    </label>
                    <?php
                        $country = $this->getFormValue('country', 'farm');

                        if (!empty($country)) {
                            $country = substr($country, 0, 2);

                            $states = HH_Tools_Countries::getSubdivisions($country);
                        }
                    ?>
                    <?php if (!empty($states)) { ?>
                        <?=
                            $this->formSelect(
                                'farm[state]',
                                $this->getFormValue('state', 'farm'),
                                array(
                                    'id' => 'farm_state',
                                    'class' => 'required',
                                    'title' => $this->translate('Please enter the state your farm is located in')
                                ),
                                array('' => '') + $states
                            );
                        ?>
                    <?php } else { ?>
                        <input
                            id="farm_state"
                            name="farm[state]"
                            type="text"
                            title="<?= $this->translate('Please enter the state your farm is located in'); ?>"
                            value="<?= $this->getFormValue('state', 'farm'); ?>"
                            class="required"
                            maxlength="45" />
                    <?php } ?>

                    <?php if (!empty($this->errors['farm']['state'])) { ?>
                    <label for="farm_state" class="error">
                        <?= implode('; ', $this->errors['farm']['state']) ?>
                    </label>
                    <?php } ?>
                </p>

                <p>
                    <label for="farm_zipCode" class="required" title="<?= $this->translate('Please enter your farm\'s zip code'); ?>">
                        <?= $this->translate('Zip Code'); ?>:
                        <abbr title="<?= $this->translate('This field is required'); ?>">*</abbr>
                    </label>
                    <input
                        id="farm_zipCode"
                        name="farm[zipCode]"
                        type="text"
                        title="<?= $this->translate('Please enter your farm\'s zip code'); ?>"
                        value="<?= $this->getFormValue('zipCode', 'farm'); ?>"
                        class="required"
                        maxlength="45" />

                    <?php if (!empty($this->errors['farm']['zipCode'])) { ?>
                    <label for="farm_zipCode" class="error">
                        <?= implode('; ', $this->errors['farm']['zipCode']) ?>
                    </label>
                    <?php } ?>
                </p>

            </fieldset>
            
            <fieldset>
                <legend><?= $this->translate('Additional Contact Info') ?></legend>
                
                <p>
                    <label for="farm_email" class="required" title="<?= $this->translate('Please enter your farm\'s email'); ?>">
                        <?= $this->translate('Email'); ?>:
                        <abbr title="<?= $this->translate('This field is required'); ?>">*</abbr>
                    </label>
                    <input
                        id="farm_email"
                        name="farm[email]"
                        type="text"
                        title="<?= $this->translate('Please enter your farm\'s email'); ?>"
                        value="<?= $this->getFormValue('email', 'farm'); ?>"
                        class="required"
                        maxlength="150" />

                    <?php if (!empty($this->errors['farm']['email'])) { ?>
                    <label for="farm_email" class="error">
                        <?= implode('; ', $this->errors['farm']['email']) ?>
                    </label>
                    <?php } ?>
                </p>
                
                <p>
                    <label for="farm_telephone" title="<?= $this->translate('Please enter your farm\'s telephone number'); ?>">
                        <?= $this->translate('Telephone'); ?>:
                    </label>
                    <input
                        id="farm_telephone"
                        name="farm[telephone]"
                        type="text"
                        title="<?= $this->translate('Please enter your farm\'s telephone number'); ?>"
                        value="<?= $this->getFormValue('telephone', 'farm'); ?>"
                        maxlength="20" />

                    <?php if (!empty($this->errors['farm']['telephone'])) { ?>
                    <label for="farm_email" class="error">
                        <?= implode('; ', $this->errors['farm']['telephone']) ?>
                    </label>
                    <?php } ?>
                </p>
                
                <p>
                    <label for="farm_fax" title="<?= $this->translate('Please enter your farm\'s fax number'); ?>">
                        <?= $this->translate('Fax'); ?>:
                    </label>
                    <input
                        id="farm_fax"
                        name="farm[fax]"
                        type="text"
                        title="<?= $this->translate('Please enter your farm\'s fax number'); ?>"
                        value="<?= $this->getFormValue('fax', 'farm'); ?>"
                        maxlength="20" />

                    <?php if (!empty($this->errors['farm']['fax'])) { ?>
                    <label for="farm_email" class="error">
                        <?= implode('; ', $this->errors['farm']['fax']) ?>
                    </label>
                    <?php } ?>
                </p>
                
            </fieldset>

            <fieldset>
                <legend><?= $this->translate('Misc.') ?></legend>

                <p>
                    <label for="farm-type_1" class="required">
                        <?= $this->translate('I\'m a Distribution Network'); ?>:
                        <abbr title="<?= $this->translate('This field is required'); ?>">*</abbr>
                    </label>

                    <input
                        id="farm-type_0"
                        type="radio"
                        name="farm[type]"
                        value=""
                        class="required"
                        title="<?= $this->translate('Don\'t allow farms or vendors to publish products to you'); ?>"
                        <?= (stripos($this->getFormValue('type-farm'), HH_Domain_Farm::TYPE_DISTRIBUTOR) === false ? 'checked="checked"' : '') ?> />
                    <label for="farm-type_0" class="radio" title="<?= $this->translate('Don\'t allow farms or vendors to publish products to you'); ?>">
                        <?= $this->translate('No'); ?>
                    </label>
                    <input
                        id="farm-type_1"
                        type="radio"
                        name="farm[type]"
                        value="<?= $this->escape(HH_Domain_Farm::TYPE_DISTRIBUTOR) ?>"
                        title="<?= $this->translate('Allow farms or vendors to publish products to you for sale'); ?>"
                        <?php
                        $value = $this->getFormValue('type', 'farm');
                        if (stripos($value, HH_Domain_Farm::TYPE_DISTRIBUTOR) !== false) {
                            echo 'checked="checked"';
                        }
                        ?> />
                    <label for="farm-type_1" class="radio" title="<?= $this->translate('Allow farms or vendors to publish products to you for sale'); ?>">
                        <?= $this->translate('Yes'); ?>
                    </label>

                    <span class="tooltip"
                          title="<?= $this->translate('Should HarvestHand farms or vendors be able to publish products to your farm?'); ?>">
                        [?]
                    </span>

                    <?php if (!empty($this->errors['farm']['type'])) { ?>
                        <label for="farm-type_1" class="error">
                            <?= implode('; ', $this->errors['farm']['type']) ?>
                        </label>
                    <?php } ?>
                </p>

            </fieldset>

            <p>
                <button type="submit" class="submit fieldset-align ui-button ui-widget ui-corner-all ui-button-text-only ui-state-default">
                    <span class="ui-button-text">
                        <i class="fa fa-check"></i>
                        <?= $this->translate('Save!'); ?>
                    </span>
                </button>
            </p>
        </form>
    </article>
</section>
