<?php
/**
 * Created by PhpStorm.
 * User: ray
 * Date: 6/10/15
 * Time: 1:03 PM
 */

?>
<style>

    h2, .title {
        margin-top: 22px;
        text-align: center;
    }
    .title > p {
        margin: 0;
    }
    h3 {
        margin-bottom: 2px;
    }
    h4 {
        font-size: 22px;
    }
    .btn {
        padding: 8px 0;
    }
    .btn, .duncan, .ray {
        width: 100%;
        margin: 6px;
    }
    .video {
        text-align: center;
        margin: auto;
    }
</style>

<div class="container_12">
    <div class="grid_12">
    <div class="grid_7">
        <h2>Welcome, to the <b>HarvestHand Community</b>!</h2>

        <p>Let's get started! Below are the tasks to complete in order to start automating sign-ups with your
            HarvestHand account. We are here to support you along the way!</p>

        <div class="video">
            <iframe width="560" height="315"
                    src="http://www.youtube.com/embed/JIjflFZNuyY?vq=hd1080&modestbranding=1&autoplay=1&fs=0&rel=0&showinfo=0&theme=light&autohide=0"
                    frameborder="0"></iframe>
        </div>

        <p>If at any point you need help with something, email or call <b>the team</b>
            <i>(team@harvesthand.com or 902-542-3277).</i></p>

        <h2><b>Getting Started</b></h2>
        <h4>1. Set up <a href="/admin/shares/location" target="_blank"><b>Locations</b></a>, <a
                href="/admin/shares/share" target="_blank"><b>Shares</b></a>, and
            <a href="/admin/shares/addon" target="_blank"><b>Products</b></a></h4>

        <p>Start with locations, then shares and products.</p>

        <h4>2. Create <a href="/admin/website" target="_blank"><b>Website Content</b></a></h4>

        <p>Create new pages and blog posts about your farm, your values, CSA information, what you grow etc.</p>

        <h4>3. Check-In Call with <b>The Team</b></h4>

        <p><i><b>(1-902-542-3277)</b></i></p>

        <p>Together we'll test share signup, review your website, and or connect your domain.
            These are the default settings for your account. If you want to accept online payments, we’ll help you
            integrate
            online payment with Paypal quickly.</p>

        <h4>4. Promotion</h4>

        <p>Share your new website with your friends, family, and customers. Write a blog post announcing your new
            website
            and or sign-up. If Facebook and or Twitter are connected it will auto update those pages when published.
            We'll
            also announce your website through the HarvestHand community via email newsletter, Facebook, and
            Twitter.</p>

        <br>

        <p class="lead">See our <a href="/admin/default/support" target="_blank"><b>Support Tab</b></a> for <b>More
                Videos</b> to help with
            your ongoing
            management.</p>

    </div>
    <div class="grid_4" style="padding-left: 16px;">
        <h2>Quick Links</h2>
        <a href="/admin/default/support" class="btn">Video Tutorials</a>
        <a href="/admin/website" class="btn">Setup a Website</a>
        <a href="/admin/shares/location" class="btn">Shares and Pickup Locations</a>
        <a href="/admin/shares/addon" class="btn">Share Add-ons</a>

        <br>

        <div class="title">
        <h3>The Team</h3>
        <p><small>team@harvesthand.com<br>902-542-3277</small></p>
        </div>

    </div>
    </div>
</div>
